### ISSUE TITLE
python listen_bucket_notification errors

### ISSUE THREAD

**Issue by armsby** [minio/minio-py#1005]
im trying to read everts using python but I keep getting an error from the minio sdk

## Expected Behavior
list events for the selected bucket

## Current Behavior
Traceback (most recent call last):
  File "eventlisten.py", line 26, in <module>
    for events in iter:
  File "/usr/local/lib/python3.5/dist-packages/minio/api.py", line 667, in listen_bucket_notification
    query=query, preload_content=False)
  File "/usr/local/lib/python3.5/dist-packages/minio/api.py", line 2190, in _url_open
    query=query)
  File "/usr/local/lib/python3.5/dist-packages/minio/helpers.py", line 293, in get_target_url
    queryencode(ordered_query.get(component_key, '')))
  File "/usr/local/lib/python3.5/dist-packages/minio/compat.py", line 104, in queryencode
    return quote(query).replace('/', '%2F')
  File "/usr/local/lib/python3.5/dist-packages/minio/compat.py", line 94, in quote
    resource.encode('utf-8') if isinstance(resource, str) else resource,
  File "/usr/lib/python3.5/urllib/parse.py", line 733, in quote
    return quote_from_bytes(string, safe)
  File "/usr/lib/python3.5/urllib/parse.py", line 758, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes

## Steps to Reproduce (for bugs)
use the example from the webside

## Your Environment
version RELEASE.2020-09-23T20-02-13Z
using the official docker image

**Comment by vadmeste** [comment]
@armsby Thanks for reporting this. I will check.

**Comment by vadmeste** [comment]
@armsby not able to reproduce in python 2 or 3. You are probably using an old version of minio-py. Could you upgrade to the latest and try again ?

**Comment by armsby** [comment]
I have just verified with pip3 
Requirement already satisfied: minio in /usr/local/lib/python3.5/dist-packages (6.0.0)

but I must have done something wrong then

**Comment by armsby** [comment]
I just made a new installation on a new server

pip3 install minio
Collecting minio
  Downloading https://files.pythonhosted.org/packages/36/fb/5f8f2768ae1a39e434abc570eac2f950770d64d6d714c914775b729fa507/minio-6.0.0-py2.py3-none-any.whl (72kB)
    100% |████████████████████████████████| 81kB 3.1MB/s
Collecting urllib3 (from minio)
  Downloading https://files.pythonhosted.org/packages/56/aa/4ef5aa67a9a62505db124a5cb5262332d1d4153462eb8fd89c9fa41e5d92/urllib3-1.25.11-py2.py3-none-any.whl (127kB)
    100% |████████████████████████████████| 133kB 6.2MB/s
Collecting pytz (from minio)
  Downloading https://files.pythonhosted.org/packages/4f/a4/879454d49688e2fad93e59d7d4efda580b783c745fd2ec2a3adf87b0808d/pytz-2020.1-py2.py3-none-any.whl (510kB)
    100% |████████████████████████████████| 512kB 3.4MB/s
Collecting certifi (from minio)
  Downloading https://files.pythonhosted.org/packages/5e/c4/6c4fe722df5343c33226f0b4e0bb042e4dc13483228b4718baf286f86d87/certifi-2020.6.20-py2.py3-none-any.whl (156kB)
    100% |████████████████████████████████| 163kB 10.7MB/s
Collecting configparser (from minio)
  Downloading https://files.pythonhosted.org/packages/08/b2/ef713e0e67f6e7ec7d59aea3ee78d05b39c15930057e724cc6d362a8c3bb/configparser-5.0.1-py3-none-any.whl
Collecting python-dateutil (from minio)
  Downloading https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl (227kB)
    100% |████████████████████████████████| 235kB 8.2MB/s
Collecting six>=1.5 (from python-dateutil->minio)
  Downloading https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Installing collected packages: urllib3, pytz, certifi, configparser, six, python-dateutil, minio
Successfully installed certifi-2020.6.20 configparser-5.0.1 minio-6.0.0 python-dateutil-2.8.1 pytz-2020.1 six-1.15.0 urllib3-1.25.11
armsby@dnode1:~$ python3 eventlisten.py
{'QueueConfigurations': [{'Id': None, 'Arn': 'arn:minio:sqs::1:mqtt', 'Events': ['s3:ObjectCreated:*', 's3:ObjectRemoved:*']}]}
Traceback (most recent call last):
  File "eventlisten.py", line 26, in <module>
    for events in iter:
  File "/home/armsby/.local/lib/python3.6/site-packages/minio/api.py", line 667, in listen_bucket_notification
    query=query, preload_content=False)
  File "/home/armsby/.local/lib/python3.6/site-packages/minio/api.py", line 2190, in _url_open
    query=query)
  File "/home/armsby/.local/lib/python3.6/site-packages/minio/helpers.py", line 293, in get_target_url
    queryencode(ordered_query.get(component_key, '')))
  File "/home/armsby/.local/lib/python3.6/site-packages/minio/compat.py", line 104, in queryencode
    return quote(query).replace('/', '%2F')
  File "/home/armsby/.local/lib/python3.6/site-packages/minio/compat.py", line 94, in quote
    resource.encode('utf-8') if isinstance(resource, str) else resource,
  File "/usr/lib/python3.6/urllib/parse.py", line 825, in quote
    return quote_from_bytes(string, safe)
  File "/usr/lib/python3.6/urllib/parse.py", line 850, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes

**Comment by vadmeste** [comment]
@armsby could you paste eventlisten.py ?

**Comment by armsby** [comment]
from minio import Minio
from minio.error import ResponseError
import pprint

minio = Minio('mys3.local',
              access_key='key',
              secret_key='access',
              secure=True)

bucket_list = minio.list_buckets()
for bucket in bucket_list:
    print(bucket.name, bucket.creation_date)

config = minio.get_bucket_notification("mytest")
print(config)


iter = minio.listen_bucket_notification(
    "mytest",
    events=('s3:ObjectCreated:*', 's3:ObjectAccessed:*', 's3:ObjectRemoved:*', 's3:ReducedRedundancyLostObject')
)

for events in iter:
    print(events)

**Comment by vadmeste** [comment]
It looks like 's3:ReducedRedundancyLostObject' is not recognized

**Comment by harshavardhana** [comment]
We don't have such notification in MinIO

**Comment by armsby** [comment]
I found the issue the documentation say events=('s3:ObjectCreated:*', 's3:ObjectAccessed:*') it works with events=['s3:ObjectCreated:*', 's3:ObjectAccessed:*']

I should have seen that, but I followed the documentation

**Comment by harshavardhana** [comment]
> I found the issue the documentation say events=('s3:ObjectCreated:_', 's3:ObjectAccessed:_') it works with events=['s3:ObjectCreated:_', 's3:ObjectAccessed:_']
> 
> I should have seen that, but I followed the documentation

Thanks
