### ISSUE TITLE
Cross Account AWS S3 Access Denied

### ISSUE THREAD

**Issue by NickLavrov** [minio/minio-py#1006]
I have an IAM user in Account A and a bucket in Account B. I put a bucket policy on Account B that allows the user `s3:*` actions on the bucket. The policy on the IAM user allows all s3 actions as well. If I run this from the AWS cli, it works:

```
AWS_ACCESS_KEY_ID=MYKEY AWS_SECRET_ACCESS_KEY=MYSECRET aws s3api get-bucket-location --bucket account-b-bucket
```

However, this minio python code gives an error:

```
from minio import Minio
def get_client():
    return Minio("s3.amazonaws.com",
                 access_key="MYKEY",
                 secret_key="MYSECRET",
                 secure=True)
bucket="account-b-bucket"
get_client().bucket_exists(bucket)
```

The error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/minio/api.py", line 404, in bucket_exists
    self._url_open('HEAD', bucket_name=bucket_name)
  File "/usr/local/lib/python3.8/site-packages/minio/api.py", line 2185, in _url_open
    region = self._get_bucket_region(bucket_name)
  File "/usr/local/lib/python3.8/site-packages/minio/api.py", line 2063, in _get_bucket_region
    region = self._get_bucket_location(bucket_name)
  File "/usr/local/lib/python3.8/site-packages/minio/api.py", line 2105, in _get_bucket_location
    raise ResponseError(response, method, bucket_name).get_exception()
minio.error.AccessDenied: AccessDenied: message: Access Denied
```

I see it fails the HEAD request, but I can run the command through the CLI just fine:

```
AWS_ACCESS_KEY_ID=MYKEY AWS_SECRET_ACCESS_KEY=MYSECRET aws s3api head-bucket --bucket account-b-bucket
```

This is using Minio 6.0.0. The bucket is in us-west-2, if that matters.

Because I can run the corresponding commands via the AWS cli, I suspect a bug in the python minio client. 

The minio initialization is working because if I try this on a bucket that's in Account A, it works:

```
bucket="account-a-bucket"
get_client().bucket_exists(bucket)
>>True
get_client().bucket_exists("ajklsdahjfasksadkhjlfsdkh") //clearly a fake bucket
>>False
```

**Comment by harshavardhana** [comment]
Not sure why is this considered `minio-py` problem?

**Comment by harshavardhana** [comment]
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python3.8/site-packages/minio/api.py", line 404, in bucket_exists
>     self._url_open('HEAD', bucket_name=bucket_name)
>   File "/usr/local/lib/python3.8/site-packages/minio/api.py", line 2185, in _url_open
>     region = self._get_bucket_region(bucket_name)
>   File "/usr/local/lib/python3.8/site-packages/minio/api.py", line 2063, in _get_bucket_region
>     region = self._get_bucket_location(bucket_name)
>   File "/usr/local/lib/python3.8/site-packages/minio/api.py", line 2105, in _get_bucket_location
>     raise ResponseError(response, method, bucket_name).get_exception()
> minio.error.AccessDenied: AccessDenied: message: Access Denied

Provide `trace_on` ?

**Comment by NickLavrov** [comment]
@harshavardhana I think it's a minio-py problem because I do not get AccessDenied when I use the AWS CLI to do the same exact API calls. Therefore, I suspect minio-py is at fault, but there could be other issues!

How do you enabled `trace_on`?

**Comment by harshavardhana** [comment]
```py
from minio import Minio
def get_client():
    return Minio("s3.amazonaws.com",
                 access_key="MYKEY",
                 secret_key="MYSECRET",
                 secure=True)
bucket="account-b-bucket"
clnt = get_client()
clnt.trace_on(sys.stdout)
clnt.bucket_exists(bucket)
```

**Comment by NickLavrov** [comment]
Trace output:

```
client.bucket_exists("<bucket-name-redacted>")
---------START-HTTP---------
GET /<bucket-name-redacted>?location= HTTP/1.1
Host: s3.amazonaws.com
X-Amz-Date: 20201019T220618Z
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
Authorization: AWS4-HMAC-SHA256 Credential=<REDACTED>/20201019/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*

HTTP/1.1 403
X-Amz-Request-Id: EC8FA33CC65F6482
X-Amz-Id-2: Jre/SVDcMcsLGny8zvM05/<REDACTED>/gqSelc=
Content-Type: application/xml
Transfer-Encoding: chunked
Date: Mon, 19 Oct 2020 22:06:17 GMT
Server: AmazonS3
b''---------END-HTTP---------
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/minio/api.py", line 404, in bucket_exists
    self._url_open('HEAD', bucket_name=bucket_name)
  File "/usr/local/lib/python3.8/site-packages/minio/api.py", line 2185, in _url_open
    region = self._get_bucket_region(bucket_name)
  File "/usr/local/lib/python3.8/site-packages/minio/api.py", line 2063, in _get_bucket_region
    region = self._get_bucket_location(bucket_name)
  File "/usr/local/lib/python3.8/site-packages/minio/api.py", line 2105, in _get_bucket_location
    raise ResponseError(response, method, bucket_name).get_exception()
minio.error.AccessDenied: AccessDenied: message: Access Denied
```

NOTE: I made a bucket in account b in us-east-1, and it DOES work. So, why does it not work for buckets in us-west-2?

`client.bucket_exists("account-b-bucket-us-east-1") >> True`

**Comment by NickLavrov** [comment]
If I init the minio client with `region="us-west-2"`, then it can find the bucket, and 

`client.bucket_exists("account-b-bucket-us-east-1")` gives `minio.error.PermanentRedirect: PermanentRedirect: message: The bucket you are attempting to access must be addressed using the specified endpoint. Send all future requests to this endpoint.`

Do I need to init a minio client for each AWS region if I plan to access buckets from different regions?

**Comment by harshavardhana** [comment]
@NickLavrov of course that is what you do with `aws` CLI as well specify the right region URL or configure the region in `/.aws/config` 

You haven't enabled GetBucketLocation API which is the reason our calls fail. I don't think this is a minio-py issue.

**Comment by NickLavrov** [comment]
The IAM user has this permission:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "s3:*",
            "Resource": "*"
        }
    ]
}
```

And the bucket in account B has this policy:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::<accountID>:user/<username>"
            },
            "Action": "s3:*",
            "Resource": [
                "arn:aws:s3:::bucket-name-here/*",
                "arn:aws:s3:::bucket-name-here"
            ]
        }
    ]
}
```

So it does have `s3: GetBucketLocation` permissions. I didn't realize that this would be limited by region. On my AWS Cli, I do not have to change the region when I make a call to a bucket in another region.

```
AWS_ACCESS_KEY_ID=MYKEY AWS_SECRET_ACCESS_KEY=MYSECRET aws s3api get-bucket-location --bucket us-east-1-bucket
AWS_ACCESS_KEY_ID=MYKEY AWS_SECRET_ACCESS_KEY=MYSECRET aws s3api get-bucket-location --bucket us-west-2-bucket
```

In this regard, is the minio-py client different?

**Comment by harshavardhana** [comment]
> AWS_ACCESS_KEY_ID=MYKEY AWS_SECRET_ACCESS_KEY=MYSECRET aws s3api get-bucket-location --bucket us-east-1-bucket
> AWS_ACCESS_KEY_ID=MYKEY AWS_SECRET_ACCESS_KEY=MYSECRET aws s3api get-bucket-location --bucket us-west-2-bucket

You should provide `--debug` output which can provide information about which region your AWS CLI is using.

**Comment by NickLavrov** [comment]
I can see now I was changing the region in my AWS CLI calls (my default region was reset). Indeed this is not a minio-py issue. Thank you for your help.
