### ISSUE TITLE
Bucket Policy Documentation Outdated?

### ISSUE THREAD

**Issue by PGijsbers** [minio/minio-py#1013]
The [documentation](https://docs.minio.io/docs/python-client-api-reference#get_bucket_policy) reads:
![image](https://user-images.githubusercontent.com/15890747/97575583-3b6ee900-19ed-11eb-9958-e4bf58c54aba.png)

However the `minio` module does not have a `policy` submodule/attribute:

```python
>>> minio.policy.Policy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'minio' has no attribute 'policy'
```

Tested with `minio=='6.0.0'`.

**Comment by balamurugana** [comment]
@PGijsbers The problem with `docs.minio.io` had been fixed few days ago. Please refresh your browser to reload the page.

**Comment by balamurugana** [comment]
Fixed by https://github.com/minio/minio-py/pull/968

**Comment by PGijsbers** [comment]
I'm sorry, could you send me a direct link to the correct communication? The original link (https://docs.minio.io/docs/python-client-api-reference#get_bucket_policy) still has outdated information for me (tried private browsing, new browser).

**Comment by balamurugana** [comment]
@PGijsbers  Please refer https://github.com/minio/minio-py/blob/release/docs/API.md and `release` for correct sources  I see you are referring doclink of `get_bucket_policy()` for `set_bucket_policy()`. BTW `{set,get,delete}_bucket_policy()` methods are refactored for correctness in the `master` and will be available in the next major release.
