### ISSUE TITLE
minio endpoint with <domain>/url

### ISSUE THREAD

**Issue by ravisarath** [minio/minio-py#1014]
hi I am using a docker app with a single domain . i configured in nginx to redirect to minio while calling <domain>/url..
Now my issue is while connecting minio through my code getting an error 
`Invalid minio endpoint`

is there any way to solve my probelm

**Comment by balamurugana** [comment]
Please refer [examples](https://github.com/minio/minio-py/tree/release/examples) and [documentation](https://github.com/minio/minio-py/blob/release/docs/API.md)
