### ISSUE TITLE
stat_object() raises an error

### ISSUE THREAD

**Issue by michalb-dsg** [minio/minio-py#1029]
Hi!
I want to check whether a specific object in the bucket is a directory or not. I want to use `stat_object()` for this, but it raises `NoSuchKey` error when I pass a directory name (with or without slash). 
I see it returns `Object`, which contains `is_dir` attribute. When using `list_objects_v2()`, I get an iterator of `Object`s, and I can see the folder as an object there.
Even when using the CLI `stat` command, I get all the folder's content and not an error (or as the CLI returns an empty object sized 0kb instead of an error).

Could you please check it out?
Thanks in advance!

**Comment by balamurugana** [comment]
@michalb-dsg 

1. A zero sized object ending with `/` can be usually treated as directory for human understanding. It is up to the user whether he is looking such objects as directory or not.
2. You could use `stat_object()` to get such object's information like any other regular objects.
3. You could also use `list_objects()` get objects list where `common prefixes` are considered as directories. It doesn't mean they are existed as objects. It is just a human representation as directory from S3.
4. Practically you don't need to create _directory_ in S3 i.e. when uploading `/path/to/myobject`, `/path/to/` prefix is created automatically by S3 or S3 returns you `/path/to/` prefix as `common prefix`.
5. Some tools create common prefixes (A zero sized object ending with `/`) and upload objects under that.

**Comment by michalb-dsg** [comment]
Thank you for your quick answer @balamurugana, 
if I understand 2 correctly, I should be able to use `stat_object()` when I'm passing "folder name + /", but it raises `NoSuchKey` error instead.
I tried passing the folder name with and without slash and both options didn't work.

**Comment by balamurugana** [comment]
Point 4 is the answer i.e. you haven't created _directory_ object.
