### ISSUE TITLE
Add required policies in documentation

### ISSUE THREAD

**Issue by rsommerard** [minio/minio-py#1030]
I want to use the `presigned_get_object` method but I cannot see which permissions in my policy my user should have to be able to use this method.

If I try to call the `presigned_get_object` method with the policy bellow, minio returns me an `AccessDenied: AccessDenied: message: Access Denied`.

Policies that don't work:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:DeleteObject",
                "s3:GetObject",
                "s3:ListBucket",
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::my-dir",
                "arn:aws:s3:::my-dir/*"
            ]
        }
    ]
}
```

I cannot find anywhere which policies should be used to be able to use each client method.

**Comment by balamurugana** [comment]
@rsommerard For pre-signed operations, it is not required to set, bucket policies to be set. Just use it like
```py
client = Minio("play.min.io", access_key="Q3AM3UQ867SPQQA43P2F", secret_key="zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG")
url = client.presigned_get_object('my-bucketname', 'my-objectname')
print(url)
```

If you have bucket policy set to denote read-only objects, just construct url like `https://play.minio.io/my-bucketname/my-objectname` and use it directly.

**Comment by rsommerard** [comment]
In my case, I need to add this specific policy `s3:GetBucketLocation`.

**Comment by balamurugana** [comment]
For pre-signed/anonymous access URL, the location query does not require. What problems are you facing in using such URLs?

**Comment by rsommerard** [comment]
If I call the `presigned_get_object` I have an `AccessDenied` error.

**Comment by balamurugana** [comment]
Two options you have,

1. Set read access to GetBucketLocation S3 API for the access key (user id) using bucket policy.
2. Passing region to `Minio` constructor would not call `GetBucketLocation` API.
