### ISSUE TITLE
No support for port parameter in Minio constructor

### ISSUE THREAD

**Issue by u2ros** [minio/minio-py#1035]
The Minio constructor has no support for custom port parameter as for example javascript client.

https://github.com/minio/minio-py/blob/be40f7e07e3760f8fff58055994a30339bc8abdb/minio/api.py#L117

This causes issue for example if one uses default minio docker image to create a local object storage as it listens on port 9000

**Comment by u2ros** [comment]
I was able to circumvent this by making the port part of endpoint like to:

`client = Minio('{}:{}'.format(endpoint, port),...)`

Fix should be easy, I'll make a PR

**Comment by balamurugana** [comment]
@u2ros Just use endpoint like `SERVER:PORT` i.e. 
```py
client = Minio(
    "play.minio.io:9000",
    access_key="Q3AM3UQ867SPQQA43P2F",
    secret_key="zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG",
)
```
