### ISSUE TITLE
An HTTP Client raised and unhandled exception: Failed to parse: http://localhost:9000

### ISSUE THREAD

**Issue by ShinoNuma** [minio/minio-py#1040]
Hi,
For some reasons I get the error "An HTTP Client raised and unhandled exception: Failed to parse: http://localhost:9000" when I try to use the library boto3 and the library minio. I carefully follow the tutorial on the official website but it's not working at all... 

Here is the script I'm trying to use:

```
from minio import Minio
from minio.error import (ResponseError, BucketAlreadyOwnedByYou,
                         BucketAlreadyExists)
minioClient = Minio('localhost:9000/minio',
                  access_key='minioadmin',
                  secret_key='minioadmin',
                  secure=False)

try:
       minioClient.make_bucket("test", location="us-east-1")
except BucketAlreadyOwnedByYou as err:
       pass
except BucketAlreadyExists as err:
       pass
except ResponseError as err:
       raise
try:
       minioClient.fput_object('test', 'music.mp3', '/tmp/music.mp3')
except ResponseError as err:
       print(err)
```

And here is the error message:

```
Traceback (most recent call last):
  File "../testt.py", line 11, in <module>
    minioClient.make_bucket("test", location="us-east-1")
  File "/home/yoda/.local/lib/python3.8/site-packages/minio/api.py", line 327, in make_bucket
    response = self._http.urlopen(method, url,
  File "/usr/lib/python3/dist-packages/urllib3/poolmanager.py", line 318, in urlopen
    u = parse_url(url)
  File "/usr/lib/python3/dist-packages/urllib3/util/url.py", line 392, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
  File "<string>", line 3, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: http://localhost:9000/minio/test/
```

I don't know if it's related or not but I'm using python 3.8.5.
The error is similar when I'm using boto3 but somehow it works using version 1 of boto.

**Comment by balamurugana** [comment]
@ShinoNuma The endpoint argument should be `SERVER:PORT` not with a URL path like `localhost:9000/minio`.  `master` branch is fixed to validate this properly. We are planning to make a release soon.

**Comment by ShinoNuma** [comment]
The result is the same even I'm respecting the endpoint argument.

**Comment by ShinoNuma** [comment]
Ok I found my problem!
If this can help: 

pip3 install --upgrade urllib3
or 
pip install --upgrade urllib3
