### ISSUE TITLE
Unable to delete Folders/Files using remove_object

### ISSUE THREAD

**Issue by prabhuSub** [minio/minio-py#1042]
Hi All,
I am trying to list out all my objects and I could find some just files inside a folder. To delete one of those files within the folder in S3 I use the below line. The line returns nothing(no error)
`client.remove_object('my-bucketname', obj.object_name)`
Once executed, I list the Folders and Files again on `recursive=True`
But, still able to see the folder and files under lister there. I feel the remove_object not deleting the folder and files.

**Comment by prabhuSub** [comment]
Referred the example - https://github.com/minio/minio-py/blob/master/examples/remove_object.py

**Comment by harshavardhana** [comment]
@prabhuSub please provide an entire example of the code you wrote.

**Comment by balamurugana** [comment]
@prabhuSub Below example should work
```py
# Remove a prefix recursively.
delete_object_list = map(
    lambda x: DeleteObject(x.object_name),
    client.list_objects("my-bucket", "my/prefix/", recursive=True),
)
errors = client.remove_objects("my-bucket", delete_object_list)
for error in errors:
    print("error occured when deleting object", error)
```

If you still see the behaviour, reopen this issue with HTTP traces and server-side logs.

**Comment by prabhuSub** [comment]
below is a similar script I used. doesn't help. Rather gives me the error mentioned below.
The installed version of minio (6.0.2)

```
from minio import Minio
from minio.deleteobjects import DeleteObject

client = Minio('s3.amazonaws.com',
               access_key='YOUR-ACCESSKEYID',
               secret_key='YOUR-SECRETACCESSKEY')

# Remove a prefix recursively.
delete_object_list = map(
    lambda x: DeleteObject(x.object_name),
    client.list_objects("my-bucketname", "my-prefix", recursive=True),
)
errors = client.remove_objects("my-bucketname", delete_object_list)
for error in errors:
    print("error occured when deleting object", error)
```
```

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-12-4665305023ff> in <module>
      1 from minio import Minio
----> 2 from minio.deleteobjects import DeleteObject
      3 
      4 delete_object_list = map(
      5     lambda x: DeleteObject(x.object_name),

ModuleNotFoundError: No module named 'minio.deleteobjects'
```

**Comment by balamurugana** [comment]
@prabhuSub Actually you would need to take the logic, not the code as is. Refer https://github.com/minio/minio-py/blob/release/examples/remove_objects.py

**Comment by prabhuSub** [comment]
Agreed! Am working on it. Thank you for the references.
