### ISSUE TITLE
presigned_post_policy Access Denied. (Invalid according to Policy: Policy Condition failed)

### ISSUE THREAD

**Issue by zz40404991** [minio/minio-py#1047]
use examples/presigned_post_policy.py and myProj return the message:
<Error><Code>AccessDenied</Code><Message>Access Denied. (Invalid according to Policy: Policy Condition failed)</Message><BucketName>my-bucket</BucketName><Resource>/my-bucket</Resource><RequestId>164FEF9EB956B7A3</RequestId><HostId>129c19c9-4cf6-44ff-9f2d-4cb7611be894</HostId></Error>

**Comment by balamurugana** [comment]
Please share your code along with HTTP traces if available.

**Comment by zz40404991** [comment]
@balamurugana  I can get return form_data = client.presigned_post_policy(policy), error to:
 curl -X POST https:xxx.xxx.com:31077-F x-amz-algorithm=AWS4-HMAC-SHA256 -F x-amz-credential=AKIAIOSFODNN7EXAMPLE/20201215/us-east-1/s3/aws4_request -F x-amz-date=20201215T081331Z -F policy=b'eyJleHBpcmF0aW9uIjogIjIwMjAtMTItMjVUMDg6MTM6MzEuMzg1WiIsICJjb25kaXRpb25zIjogW1siZXEiLCAiJGJ1Y2tldCIsICJteS1idWNrZXRuYW1lIl0sIFsic3RhcnRzLXdpdGgiLCAiJGtleSIsICJteS9vYmplY3QvcHJlZml4LyJdLCBbImNvbnRlbnQtbGVuZ3RoLXJhbmdlIiwgMTA0ODU3NiwgMTA0ODU3NjBdLCBbImVxIiwgIiR4LWFtei1hbGdvcml0aG0iLCAiQVdTNC1ITUFDLVNIQTI1NiJdLCBbImVxIiwgIiR4LWFtei1jcmVkZW50aWFsIiwgIkFLSUFJT1NGT0ROTjdFWEFNUExFLzIwMjAxMjE1L3VzLWVhc3QtMS9zMy9hd3M0X3JlcXVlc3QiXSwgWyJlcSIsICIkeC1hbXotZGF0ZSIsICIyMDIwMTIxNVQwODEzMzFaIl1dfQ==' 
-F x-amz-signature=4416f602d2ee53b241e6dd91a94e30ad2f162776064cad001aa5eaa5622da19d -F file=@<FILE>

**Comment by balamurugana** [comment]
@zz40404991 It is hard to understand from presigned URL. Can you provide your python code?

**Comment by balamurugana** [comment]
Please reopen with appropriate information.
