### ISSUE TITLE
Error to run examples with pip=7.0.0

### ISSUE THREAD

**Issue by sanvir10** [minio/minio-py#1048]
I have python 3.6.9 on ubuntu 18.04 LTS, i created the example but when i try to execute it, i get this error:

```
python3 [file-uploader.py](https://pypi.org/project/minio/#description) 
Traceback (most recent call last):
  File "client-minio/new-file-uploader.py", line 1, in <module>
    from minio import Minio
  File "/home/sanvir/.local/lib/python3.6/site-packages/minio/__init__.py", line 45, in <module>
    from .api import Minio
  File "/home/sanvir/.local/lib/python3.6/site-packages/minio/api.py", line 60, in <module>
    from .select import SelectObjectReader, SelectRequest
ImportError: cannot import name 'SelectRequest'
```

**Comment by harshavardhana** [comment]
> I have python 3.6.9 on ubuntu 18.04 LTS, i created the example but when i try to execute it, i get this error:
> 
> ```
> python3 [file-uploader.py](https://pypi.org/project/minio/#description) 
> Traceback (most recent call last):
>   File "client-minio/new-file-uploader.py", line 1, in <module>
>     from minio import Minio
>   File "/home/sanvir/.local/lib/python3.6/site-packages/minio/__init__.py", line 45, in <module>
>     from .api import Minio
>   File "/home/sanvir/.local/lib/python3.6/site-packages/minio/api.py", line 60, in <module>
>     from .select import SelectObjectReader, SelectRequest
> ImportError: cannot import name 'SelectRequest'
> ```

Looks like you didn't upgrade your installation properly, do `pip uninstall minio` and `pip install minio==7.0.0`
