### ISSUE TITLE
can not properly resolved Error EnttiyTooLarge

### ISSUE THREAD

**Issue by yutianlong** [minio/minio-py#1050]
when  I set  more  than Maximum part size   the SDK will throw urllib3 exception and retry.  it should throw S3 error without retry

1. set max part 128M in MinIO server 
2. send put_object request with Parameters : part_size 200M ,file_size 190M
3. waiting requests

Actual results：
the response  return error：max retries exceeded with url: /bucketname/objectname

Expected Results：
return  EnttiyTooLarge error can be resolved with PYSDK  and not retry again

**Comment by yutianlong** [comment]
it will be ok in go sdk

**Comment by balamurugana** [comment]
Please share the sample code and HTTP traces by `trace_on()`

**Comment by yutianlong** [comment]
sorry  I am only a tester  cannot provide more info。this is return error: urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=9000): Max retries exceeded with url: /siyutest121423233312323/5e07ae12-57ea-400a-9?partNumber=1&uploadId=6f91ed6e-710e-4c07-9149-0954f43a4466 (Caused by ProtocolError('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))

**Comment by balamurugana** [comment]
@yutianlong As per the error, the server is not responding and the connection was aborted. Please check your server and network connectivity.

Reopen the issue with required information.
