### ISSUE TITLE
Question: what is the migration path for BucketAlreadyOwnedByYou and BucketAlreadyExists errors?

### ISSUE THREAD

**Issue by ell1e** [minio/minio-py#1051]
What is the migration path for BucketAlreadyOwnedByYou and BucketAlreadyExists errors? These imports just seem to be gone and I can't find a single relevant result on Google on what happened with them. Maybe it would be useful to add a note to `minio/error.py` at the top in the form of a code comment that gives some info on where they went, for people like me opening up the file and trying to figure out what happened.

**Comment by balamurugana** [comment]
Both `BucketAlreadyOwnedByYou`/`BucketAlreadyExists` errors are valid as per S3 specification. We should check for both error to find whether the bucket already exists.

`minio/error.py` does not handle anything specific to these errors. Please reopen the issue by provide what exactly you are expecting and what is missing now.

**Comment by ell1e** [comment]
@balamurugana `minio/error.py` used to define these names, now it doesn't. I get an `ImportError` when running my code and I'm not sure what I need to use now to handle those errors. Sorry for not being clear.

**Comment by balamurugana** [comment]
@ell1e The latest release v7 is a breaking release. Please refer [examples](https://github.com/minio/minio-py/tree/master/examples) and [API guide](https://github.com/minio/minio-py/blob/master/docs/API.md)

**Comment by ell1e** [comment]
I did, but this is **really tedious** to go through to find the new variant of what I am using if I don't know what name I am looking for. This is why a migration note would be great, instead of just dropping the new API with no info about how it relates to the old one. Is there one?

**Comment by ell1e** [comment]
One example: this uses make_bucket as I do: https://github.com/minio/minio-py/blob/master/examples/make_bucket.py

... but it doesn't handle any errors, while my code does. But what does that mean? Am I not supposed to handle BucketAlreadyOwnedByYou  for `make_bucket` anymore, or just differently? Or does the new `make_bucket` not throw any errors at all anymore? If there was some summary about the biggest changes like e.g. what I'm in general supposed to do about all the error names that are gone like `BucketAlreadyOwnedByYou` (has it been merged into `S3Error` by any chance?) that would be useful. Also, maybe `make_bucket.py` should be updated with error handling to show how that is supposed to be done.

**Comment by balamurugana** [comment]
How about below code?
```py
if not client.bucket_exists("my-bucket"):
    client.make_bucket("my-bucket")
```
To specific to make bucket, it is usually done only one in life time.  When error is concerned with APIs, there is nothing specific unless user wants to deal with S3 API.

minio-py v7 comes with lot of additions, improvements and correctness + detailed API guide and examples. Majority of older APIs do not break because of new additional parameters. However error handling is surely incompatible because previous versions did not provide right way of handling errors.

You could refer [README](https://github.com/minio/minio-py/blob/master/README.md) for basic `S3Error` handling.  `S3Error` has `code` property contain [S3 error[(https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html#ErrorCodeList)

**Comment by ell1e** [comment]
That code looks like a race condition waiting to happen, and therefore useless in production code. You really shouldn't suggest that to anyone, IMHO.

The only sane way is obviously to check S3Error, but only for the specific known error condition that it already exists. That was easily possible with `BucketAlreadyExists`, but now there's just opaque S3Error with no example code anywhere of how to check for a *specific* S3 error instead of just any. The README is kind of useless here as well because it doesn't check `code`. What is that even, a string?

A migration guide specifically for sane error handling, and updating your examples to handle errors would really help a lot.
