### ISSUE TITLE
about fput_object

### ISSUE THREAD

**Issue by BB-9E** [minio/minio-py#1058]
about the fput_object  function :  If the content_type is not set, will it affect the upload speed? I want to upload a large number of mp4 files

**Comment by balamurugana** [comment]
No. Upload speed is related to your client/server network and value in `num_parallel_uploads` with memory.

**Comment by BB-9E** [comment]
Thank you, I have a large number of files of about 400M, and it will take about three minutes to upload one. How to set part_size and num_parallel_uploads better, is the bigger the better?

**Comment by balamurugana** [comment]
It purely depends on your network bandwith/speed and your client memory. You would need to try with different higher values of those parameters.

**Comment by BB-9E** [comment]
OK, thank you~
