### ISSUE TITLE
AuthorizationHeaderMalformed when using bucket_exists

### ISSUE THREAD

**Issue by yensa** [minio/minio-py#1059]
I am currently working on a project which needs to access an S3 bucket, we are trying to update the minio version to the most recent one (7.0.1) from version 4.0.5. But we are facing an exception when using the `bucket_exists` function

```
S3Error: S3 operation failed; code: AuthorizationHeaderMalformed, message: The authorization header is malformed
; the region 'us-east-1' is wrong; expecting 'eu-west-1', resource: None, request_id: 14291FC7E3A74661, host_id: 
HtmUoenTlxefflsoP3lMhKisbjbwoogFe7ELe5dznUHRXO4y4w5hNNj/Cy8qRw+4TUDih2aZV7g=
```

Our bucket is located in `eu-west-1.compute.internal` and I can see that the error relates to the fact that minio queries Amazon using the `us-east-1` region, reading the code a little bit I saw that there was a big refactoring merged into minio that definitely could have an impact on that query https://github.com/minio/minio-py/pull/968.

**Comment by balamurugana** [comment]
@yensa `GetBucketLocation` S3 API is called if there is no region passed via constructor. The usage is something similar of
```py
        client = Minio(
            "AWS-ENDPOINT",
            access_key="Q3AM3UQ867SPQQA43P2F",
            secret_key="zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG",
            region="eu-west-1",
        )
```

If you still have the problem, please reopen the issue with your code and http traces using `Minio.trace_on(sys.stdout)`
