### ISSUE TITLE
The file upload algorithm may create a memory leak

### ISSUE THREAD

**Issue by mykola-mokhnach** [minio/minio-py#1062]
1. Get a large 4GB file
2. Try to upload it using this lib not using the multipart upload (e.g. as single data chunk):

```
result = client.fput_object(
    "my-bucket", "my-object", "my-filename",
    part_size=4 * 1024 * 1024 * 1024, # The maximum size of a single file is 5 GB, so this is fine
)
```

3. Check the memory usage on the destination machine

Actual result:
The library loads the whole file (all 4 GB) into RAM before uploading it, which causes OOM on machines where the amount of memory is low or if multiple parallel uploads are done.

Expected result:
I don't see any reason to read the whole stream into [memory](https://github.com/minio/minio-py/blob/cae7a58ecef451ce390478b76fc54927ae8bc6bd/minio/api.py#L1731) before passing it to urllib3 for this case, where a file is not uploaded in chunks and we know its size in advance (also could calculate hashsums without loading it into memory).

**Comment by harshavardhana** [comment]
The main reason is we need to either compute sha256 or md5sum 

Without that AWS S3 protocol doesn't work.

We know how to write efficiently, we just cannot circumvent the SPEC here.

You are allowed to set meaningful part size to control memory usage for this purpose alone, so set it to something meaningful and appropriate for your environment.

**Comment by mykola-mokhnach** [comment]
Thanks for the swift response @harshavardhana .

We still could compute sha/md5 of a file without loading it fully into the memory: https://stackoverflow.com/questions/1131220/get-md5-hash-of-big-files-in-python

I did several performance tests and it looks like for big files it is faster (sometimes much faster) to upload it as a whole rather than doing it in chunks. Each new chunk upload spends time opening and closing a new connection. Of course, it is possible to increase the count of parallel uploads, but then the overall memory consumption suffers, since each chunk must be fully loaded into the memory.

**Comment by harshavardhana** [comment]
> We still could compute sha/md5 of a file without loading it fully into the memory: https://stackoverflow.com/questions/1131220/get-md5-hash-of-big-files-in-python

You cannot do that without serializing your uploads @mykola-mokhnach we wish to upload at least 4 parts in parallel. That article is misleading because md5sum should be calculated before the upload can start - its not something we need its something that API needs. So if you want to spend time doing md5sum of 5GiB object before uploading just to save memory is useless. 

That is why you have multiple smaller parts you should use to upload. 

> I did several performance tests and it looks like for big files it is faster (sometimes much faster) to upload it as a whole rather than doing it in chunks. Each new chunk upload spends time opening and closing a new connection. Of course, it is possible to increase the count of parallel uploads, but then the overall memory consumption suffers, since each chunk must be fully loaded into the memory.

There is nothing you can do about that A seekable file is not going to be possible to upload efficiently - you cannot seek to multiple offsets concurrently so memory efficiency is not possible. 

The fundamental reason is S3 API is not forgiving, all other SDKs boto3, aws-sdks do the same implementation. 

We have at this for 6yrs now explored every single option available to optimize, it's just not possible.

**Comment by mykola-mokhnach** [comment]
Sorry, for the distraction. I would like to demonstrate my workaround code, which was used to test the actual upload performance:

```
        file_id = str(uuid.uuid4())
        file_name = os.path.basename(file_info.path)

        headers = {
            'Content-Length': str(file_info.size),
        }
        md5_base64 = ''
        sha256_hex = _UNSIGNED_PAYLOAD
        if self._config.secure:
            md5_base64 = base64.b64encode(file_info.md5.digest()).decode('utf-8')
        else:
            sha256_hex = file_info.sha256.hexdigest()
        if md5_base64:
            headers['Content-Md5'] = md5_base64
        with open(file_info.path, 'rb') as body:
            start = time.perf_counter()
            # noinspection PyProtectedMember
            self._minio_client()._url_open(
                'PUT',
                bucket_name=self._config.bucket,
                object_name=to_object_name(file_id),
                headers=headers,
                body=body,
                content_sha256=sha256_hex
            )
        duration = time.perf_counter() - start
        return self.stat_file(file_id), duration
```

The code uses the older version of minio-py (v. 5). When I upload a 4 GB file using it then no memory is used and the performance is actually only limited by the width of my upload channel, whenever the standard `fput_object` call takes 2-3 times more time with default settings (not even talking about the memory usage). md5 and sha256 of the file are precalculated using the buffering approach similar to the one from SO solution above. BTW, these are calculated in no-time, because the speed of sequential disk read is very high.

@harshavardhana I understand the hard work you and the team are doing to support the project and I really appreciate it. I am also being an active open-source contributor and would like to find a way to make the framework even better than it is now.
