### ISSUE TITLE
Using compose_object with small objects gives a `ValueError`

### ISSUE THREAD

**Issue by TheBlusky** [minio/minio-py#1064]
According to specification (https://docs.min.io/docs/python-client-api-reference.html#compose_object)

`compose_object` is supposed to `Create an object by combining data from different source objects using server-side copy.`

However, when using it with source with small objects, it gives the following error:

`ValueError: source {bucket}/{path}: size 3 must be greater than 5242880`

This errors seams to be from the following code : https://github.com/minio/minio-py/blob/cae7a58ecef451ce390478b76fc54927ae8bc6bd/minio/api.py#L1342-L1352

Is it a bug, or is this limit is necessary ?

**Comment by balamurugana** [comment]
@TheBlusky AWS S3 specification does not support < 5 MiB objects (except last part) in server side copy in multipart upload. For smaller objects, you would need to download/concatenate locally and upload accordingly
