### ISSUE TITLE
Unable to set Retention on Object while creating an Object

### ISSUE THREAD

**Issue by anaik91** [minio/minio-py#1065]
Unable to set Retention on Object while creating an Object. 

Below is the code .

```
date = datetime.utcnow().replace(
    hour=0, minute=0, second=0, microsecond=0,
) + timedelta(days=30)
tags = Tags(for_object=True)
tags["User"] = "jsmith"
result = client.put_object(
    "my-bucket", "my-object", io.BytesIO(b"hello"), 5,
    tags=tags,
    retention=Retention(GOVERNANCE, date),
    legal_hold=True,
)

```

I am Getting the below error 
```
if retention and retention.mode():
TypeError: 'str' object is not callable
```

**Comment by balamurugana** [comment]
Please try the fix https://github.com/minio/minio-py/pull/1066 and let me know whether it is working for you

**Comment by anaik91** [comment]
@balamurugana how can I test this?

**Comment by balamurugana** [comment]
@anaik91 Just get the entire PR and use the sources instead of released source. I usually set `PYTHONPATH` to the source.
