### ISSUE TITLE
Test Connection to MINIO server at init

### ISSUE THREAD

**Issue by adr-arroyo** [minio/minio-py#1068]
**Is your feature request related to a problem? Please describe.**
When initializing the MINIO Client (__python__) there is no test of the connection to check if input parameters (i.e.: url, user, password,...) are correct. Moreover, the default `urllib3.PoolManager` object in the MINIO API has a default __timeout__ equal to `urllib3.Timeout.DEFAULT_TIMEOUT`, which, when the input parameters such as URL or password are wrong, __does not return any error and leaves the user waiting an infinite time in any request to the server after initializing the client__. 

This leaves to devs to create an object of type `urllib3.PoolManager` to define their own timeout to test the connection. However, the problem is that __if we set that timeout quite short (just like any connection test), when downloading "big" objects, the MINIO Client returns a Timeout error__. 

**Describe the solution you'd like**
The solution should be to include inside the MINIO client init a test of the parameters and the connection, throwing an error when they are wrong, and leaving the control of the time to wait as input parameter for the user.

**Describe alternatives you've considered**
The solution to this passes through defining two `urllib3.PoolManager` objects, one for testing (which is done by the API user for example with a `minio_client.list_buckets()`) and the other one for the rest of operations with a greater TIMEOUT. 

Thank you!

**Comment by balamurugana** [comment]
@adr-arroyo

1. I see the default timeout is working for unavailable endpoint. As the default timeout in `urllib3` uses system's socket timeout, your system might have configuration issues which might lead to wait in infinite time.
2. In my system, the timeout is 22s approx. I am going to change this to 5m in a upcoming patch.
3. It is a bad idea to do connection check in the constructor. This defeats the purpose of lazy eval. If your requirement is still wanted to check the endpoint at constructor level, check yourself before calling the constructor or inherit `Minio` object and do your own.
4. Your custom `urllib3.PoolManager` has wrongly configured `urllib3.Timeout` object. Please refer `urllib3` documentation carefully.

**Comment by adr-arroyo** [comment]
Hello @balamurugana , thanks for the answer.

Even though I agree that maybe the constructor is not the best place to check anything, I still find it weird that no test at all is done. I, of course, already did it myself in my code but I thought it would better be coded somewhere inside the  library.  

As for the `urllib3` object, I just took the same as in the MINIO library, which is:

```
_http = urllib3.PoolManager(
            timeout=urllib3.Timeout.DEFAULT_TIMEOUT,
            maxsize=minio.helpers.MAX_POOL_SIZE,
            cert_reqs='CERT_REQUIRED',
            ca_certs=ca_certs,
            retries=urllib3.Retry(
                total=5,
                backoff_factor=0.2,
                status_forcelist=[500, 502, 503, 504]
            )
        )
```
 
However, in order to set up a specific short timeout, I  just used:

```
_http = urllib3.PoolManager(
            timeout=1,
            maxsize=minio.helpers.MAX_POOL_SIZE,
            cert_reqs='CERT_REQUIRED',
            ca_certs=ca_certs,
            retries=urllib3.Retry(
                total=3,
                backoff_factor=0.2,
                status_forcelist=[500, 502, 503, 504]
            )
        )
```

This lead to the issue of downloading a big object. So what I do is init MINIO with this object, do a simple `list_buckets()` and then re-init MINIO with the previous `urllib3` object.

Thanks anyway!
