### ISSUE TITLE
Does put_object() accepts both io.RawIOBase and io.BytesIO as type of data argument?

### ISSUE THREAD

**Issue by bmy4415** [minio/minio-py#1070]
Hi I'm new to minio python sdk.

I was trying to upload json to S3 using minio. According to [API Reference](https://docs.min.io/docs/python-client-api-reference.html#put_object), `data` argument accepts io.RawIOBase type.

But it seems that `data` accepts `io.BytesIO` too which is not subclass of `io.RawBaseIO`. See this [stackoverflow question](https://stackoverflow.com/questions/55223401/minio-python-client-upload-bytes-directly).

I also found that when I used `io.StringIO` instead of `io.BytesIO`, it fails.

FYI I attach my code block.

```python
# Assume that type of content is 'dict'
# io.BytesIO works
content = json.dumps(content, ensure_ascii=False).encode('utf-8') # convert dict to bytes
client.put_object('my-bucket', 'my-object', io.BytesIO(content), -1, part_size=50*1024*1024, content_type='application/json') 

# io.StringIO does not work
content = json.dumps(content, ensure_ascii=False) # convert to str
client.put_object('my-bucket', 'my-object', io.StringIO(content), part_size=50*1024*1024, content_type='application/json')

File "/usr/local/lib/python3.7/site-packages/minio/api.py", line 1792, in put_object
  raise exc
File "/usr/local/lib/python3.7/site-packages/minio/api.py", line 1732, in put_object
  data, part_size + 1, one_byte, progress=progress,
File "/usr/local/lib/python3.7/site-packages/minio/helpers.py", line 162, in read_part_data
  part_data += data
TypeError: can't concat str to bytes
```

How about adding `io.BytesIO` to type of `data` argument of function `put_object()`?

**Comment by balamurugana** [comment]
Actually the documentation has incorrect information. `data` must have callable `read()` and `read()` must return bytes-like object. I will send the fix accordingly.
