### ISSUE TITLE
make_bucket raises AttributeError toxml

### ISSUE THREAD

**Issue by voegtlel** [minio/minio-py#1072]
Hi there,

```py
minio = Minio(
    "localhost",
    access_key="123",
    secret_key="456",
    secure=False,
    region="myregion",
)
minio.make_bucket("test", location="myregion")
```
The call to `make_bucket` raises the following exception:
```
...
  File "site-packages\minio\api.py", line 618, in make_bucket
    body = marshal(element)
  File "site-packages\minio\xml.py", line 99, in marshal
    return getbytes(obj.toxml(None))
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'toxml'
```
(Tested with 7.0.1, worked before with 6.0.2)
My guess is that there is actually a structured element missing, because `toxml` is not documented for `Element`.

Thanks!

**Comment by balamurugana** [comment]
Please try the PR https://github.com/minio/minio-py/pull/1073 and let me know whether it is working for you.

**Comment by voegtlel** [comment]
That was quick :) Yes, the fix works for me, thanks!

**Comment by voegtlel** [comment]
Sorry to reopen this, but is there any due to expect a release with this fix? I cannot update to 7 until this is in, but the code changes are already in place.

**Comment by balamurugana** [comment]
New minor release will be made soon.
