### ISSUE TITLE
Two process try to get_file(the same file 'xx.npy') at the same time will fail!

### ISSUE THREAD

**Issue by gai1995** [minio/minio-py#1074]
A strange thing happens, when I use multiprocessing and call the minio.fget_object for a same file (xx.npy), one success, the other would fail. 
More, this would make the .npy file can not be load by numpy(though one process has get the file successfully!), cause an error "ValueError: Cannot load file containing pickled data when allow_pickle=False".
If just single process to get the file ,everything is ok! So, what's wrong with this? Anyone can help me?

**Comment by balamurugana** [comment]
@gai1995 Not sure why same file is downloaded using two processes in parallel . If this is your requirement, use `tmp_file_path` argument appropriately.

```py
fget_object(bucket_name, object_name, file_path, request_headers=None, ssec=None, version_id=None, extra_query_params=None, tmp_file_path=None)
```
