### ISSUE TITLE
Missing a "create user"

### ISSUE THREAD

**Issue by arnists** [minio/minio-py#1078]
I expected to find something akin to the command `mc admin user add`. Am I grossly misunderstanding something in the documentation?

**Comment by balamurugana** [comment]
Please follow PR https://github.com/minio/minio-py/pull/1076

**Comment by raphaelauv** [comment]
https://github.com/minio/minio-py/blob/b3ba3bf99fe6b9ff2b28855550d6ab5345c134e3/minio/minioadmin.py#L77
