### ISSUE TITLE
AssumeRoleProvider shouldn't require scheme

### ISSUE THREAD

**Issue by hardbyte** [minio/minio-py#1079]
Creating a minio client requires the host and port:

```
minio.Minio("minio-host:minio-port", ...)
```

But creating an `AssumeRoleProvider` requires the STS endpoint including scheme e.g.

```
AssumeRoleProvider("http://minio-host:minio-port")
```

This seems to add an unnecessary stumbling block for users.

**Comment by balamurugana** [comment]
It is a design choice to make argument simple in `AssumeRoleProvider` and arguments in `Minio` are kept for backward compatibility.

**Comment by hardbyte** [comment]
Ok sure. I've been testing for the last half hour and it seems like perhaps AssumeRoleProvider doesn't work in the latest release (7.0.1)

**Comment by balamurugana** [comment]
Please share the error you are getting including HTTP traces using `Minio.trace_on()`. You could also check your AssumeRoleProvider` working by directly calling `AssumeRoleProvider.retrieve()`
