### ISSUE TITLE
Severely degraded upload speed since v7

### ISSUE THREAD

**Issue by harpener** [minio/minio-py#1084]
Hi guys,

with upgrade to version 7, we have seen a major upload slowdown. Files having several GBs took several hours instead of minutes to be uploaded.

We are using Python 3.8, data are uploaded from files stored on local disk, having size up to several GBs, different data in multiple processes, up to 15 processes per server, 48 processes in total.

With Minio library, we use `fput_object` method. We use a progress class for logging, which we have to adjust because we expected the logs to be after upload, not after file read. We use part size 1 GB, we used to have 5 GB, but since v7 it started throwing exceptions with 32b environment limitation (i.e. only up to 4 GB).

We noticed that the files are read in very small chunks, especially when it was halved in v7: https://github.com/minio/minio-py/blob/7.0.0/minio/helpers.py#L157
As we suspected this is the issue, we increased the value to 500 MB using a forked project and the speed degradation was gone.

I can imagine that combined with moved progress, one could display a progress graph updated very often, but is it the only reason why there is such a small read size value? It would be a big help if it was increased or parametrized. Or maybe if you have some other advice.

Thank you for your answer.

**Comment by balamurugana** [comment]
@harpener I am able to reproduce the issue and will send a fix
