### ISSUE TITLE
Unable to set bucket Versioning

### ISSUE THREAD

**Issue by recklessop** [minio/minio-py#1096]
I am trying to enable Versioning on a bucket with the python SDK, and I am getting an error.

When i "get" the current versioning status works fine, so I know I'm connected. I have tried the minio python module from pip as well as installing it from github. 

Both result in the error below. Any ideas?

Thanks!

Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from minio import Minio
>>> from minio.error import S3Error
>>> client = Minio("minio1", access_key="mykey", secret_key="mysecret",)
>>> config = client.set_bucket_versioning("backups", VersioningConfig(ENABLED))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'VersioningConfig' is not defined
>>> config = client.get_bucket_versioning("backups")
>>> print(config.status)
Off
>>>

**Comment by balamurugana** [comment]
import relevant items from `versionconfig`

**Comment by recklessop** [comment]
If there is more to update then documentation needs updated on the minio site.

**Comment by harshavardhana** [comment]
> If there is more to import then documentation needs updated on the minio site.

Excellent idea feel free to send a fix with the update @recklessop
