### ISSUE TITLE
int 0 in Python is not None

### ISSUE THREAD

**Issue by Sug2077** [minio/minio-py#1105]
I found a serious bug while writing scripts use minio-python-sdk 7.0.2

Int 0 in Python is not None, then delete-markers always return False

![image](https://user-images.githubusercontent.com/23712755/113117027-a8a6d480-9240-11eb-910d-5192c73017a6.png)

**Comment by Sug2077** [comment]
> Value `0` is a valid size. Why are you getting `0` instead of `None`?

delete-marker's size is 0B
![image](https://user-images.githubusercontent.com/23712755/113122654-6b454580-9246-11eb-8b20-dac402b13af3.png)

**Comment by balamurugana** [comment]
@Sug2077 `mc` tool may display for consistency. What are you getting in the XML?

**Comment by Sug2077** [comment]
> @Sug2077 `mc` tool may display for consistency. What are you getting in the XML?

Pycharm debug mode
![image](https://user-images.githubusercontent.com/23712755/113127716-a5651600-924b-11eb-9ac9-5c3d2b9c3234.png)

**Comment by Sug2077** [comment]
![image](https://user-images.githubusercontent.com/23712755/113127923-e2310d00-924b-11eb-82bc-64b3701a211b.png)

**Comment by balamurugana** [comment]
Enable `http` trace by `Minio.trace_on(sys.stdout)` and paste your result.

**Comment by Sug2077** [comment]
---------START-HTTP---------
GET /test2?delimiter=%2F&max-keys=1000&prefix=&versions= HTTP/1.1
Host: 10.2.4.207:9001
User-Agent: MinIO (Windows; AMD64) minio-py/7.0.2
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20210331T102834Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210331/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*

HTTP/1.1 200
Accept-Ranges: bytes
Content-Length: 709
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Server: MinIO
Vary: Origin
X-Amz-Request-Id: 16716691219B34BC
X-Xss-Protection: 1; mode=block
Date: Wed, 31 Mar 2021 10:28:34 GMT

<?xml version="1.0" encoding="UTF-8"?>
<ListVersionsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>test2</Name><Prefix></Prefix><KeyMarker></KeyMarker><NextVersionIdMarker></NextVersionIdMarker><VersionIdMarker></VersionIdMarker><MaxKeys>1000</MaxKeys><Delimiter>/</Delimiter><IsTruncated>false</IsTruncated><DeleteMarker><Key>1.jpg</Key><LastModified>2021-03-31T09:13:07.155Z</LastModified><ETag></ETag><Size>0</Size><Owner><ID>02d6176db174dc93cb1b899f7c6078f08654445fe8cf1b6ce98d8855f66bdbf4</ID><DisplayName>minio</DisplayName></Owner><StorageClass>STANDARD</StorageClass><IsLatest>true</IsLatest><VersionId>faec50c4-8463-4fd0-9f1b-5d92484d7576</VersionId></DeleteMarker></ListVersionsResult>
----------END-HTTP----------

**Comment by balamurugana** [comment]
I see below non-standard values. What is your S3 server? If `minio`, please upgrade the server and try again.

```
<ETag/>
<Size>0</Size>
```

**Comment by Sug2077** [comment]
mc version and minio version 
```
C:\Users\sug_gao\Pictures\test>mc -v
mc version RELEASE.2021-03-23T05-46-11Z

C:\Users\sug_gao\Pictures\test>mc admin info minio1
●  10.2.4.207:9001
   Uptime: 1 day
   Version: 2021-03-26T00:00:41Z
   Network: 1/1 OK
   Drives: 4/4 OK

6.6 MiB Used, 2 Buckets, 2 Objects
4 drives online, 0 drives offline

C:\Users\sug_gao\Pictures\test>mc mb minio1/test1
Bucket created successfully `minio1/test1`.

C:\Users\sug_gao\Pictures\test>mc version enable minio1/test1
minio1/test1 versioning is enabled

C:\Users\sug_gao\Pictures\test>mc cp ./1.jpg minio1/test1
./1.jpg:              6.56 MiB / 6.56 MiB [=============================================================] 2.63 MiB/s 2s
C:\Users\sug_gao\Pictures\test>mc ls --versions minio1/test1
[2021-04-01 08:41:38 CST] 6.6MiB eceb6107-7227-40dd-8c09-0a2c55384bd8 v1 PUT 1.jpg

C:\Users\sug_gao\Pictures\test>mc rm minio1/test1/1.jpg
Removing `minio1/test1/1.jpg`.

C:\Users\sug_gao\Pictures\test>mc ls --versions minio1/test1
[2021-04-01 08:42:17 CST]     0B 5da0c136-e50d-4913-9dba-6c39fc6432e5 v2 DEL 1.jpg
[2021-04-01 08:41:38 CST] 6.6MiB eceb6107-7227-40dd-8c09-0a2c55384bd8 v1 PUT 1.jpg
```
minio-python-sdk
```
Name: minio
Version: 7.0.2
Summary: MinIO Python SDK for Amazon S3 Compatible Cloud Storage
Home-page: https://github.com/minio/minio-py
Author: MinIO, Inc.
Author-email: dev@min.io
License: Apache License 2.0
Location: c:\users\sug_gao\anaconda3\envs\py37\lib\site-packages
Requires: urllib3, certifi
Required-by:

```
http trace
```
---------START-HTTP---------
GET /test1?location= HTTP/1.1
Host: 10.2.4.207:9001
User-Agent: MinIO (Windows; AMD64) minio-py/7.0.2
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20210401T004438Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210401/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*

HTTP/1.1 200
Accept-Ranges: bytes
Content-Length: 128
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Server: MinIO
Vary: Origin
X-Amz-Request-Id: 1671954826AD72E0
X-Xss-Protection: 1; mode=block
Date: Thu, 01 Apr 2021 00:44:38 GMT

<?xml version="1.0" encoding="UTF-8"?>
<LocationConstraint xmlns="http://s3.amazonaws.com/doc/2006-03-01/"></LocationConstraint>
----------END-HTTP----------
---------START-HTTP---------
GET /test1?delimiter=%2F&max-keys=1000&prefix=&versions= HTTP/1.1
Host: 10.2.4.207:9001
User-Agent: MinIO (Windows; AMD64) minio-py/7.0.2
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20210401T004438Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210401/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*

HTTP/1.1 200
Accept-Ranges: bytes
Content-Length: 1114
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Server: MinIO
Vary: Origin
X-Amz-Request-Id: 16719548271B59A4
X-Xss-Protection: 1; mode=block
Date: Thu, 01 Apr 2021 00:44:38 GMT

<?xml version="1.0" encoding="UTF-8"?>
<ListVersionsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>test1</Name><Prefix></Prefix><KeyMarker></KeyMarker><NextVersionIdMarker></NextVersionIdMarker><VersionIdMarker></VersionIdMarker><MaxKeys>1000</MaxKeys><Delimiter>/</Delimiter><IsTruncated>false</IsTruncated><DeleteMarker><Key>1.jpg</Key><LastModified>2021-04-01T00:42:17.563Z</LastModified><ETag></ETag><Size>0</Size><Owner><ID>02d6176db174dc93cb1b899f7c6078f08654445fe8cf1b6ce98d8855f66bdbf4</ID><DisplayName>minio</DisplayName></Owner><StorageClass>STANDARD</StorageClass><IsLatest>true</IsLatest><VersionId>5da0c136-e50d-4913-9dba-6c39fc6432e5</VersionId></DeleteMarker><Version><Key>1.jpg</Key><LastModified>2021-04-01T00:41:38.292Z</LastModified><ETag>&#34;815e846f2246528b881a4ed654b7bc0f&#34;</ETag><Size>6874691</Size><Owner><ID>02d6176db174dc93cb1b899f7c6078f08654445fe8cf1b6ce98d8855f66bdbf4</ID><DisplayName>minio</DisplayName></Owner><StorageClass>STANDARD</StorageClass><IsLatest>false</IsLatest><VersionId>eceb6107-7227-40dd-8c09-0a2c55384bd8</VersionId></Version></ListVersionsResult>
----------END-HTTP----------
```

**Comment by balamurugana** [comment]
Try this PR https://github.com/minio/minio-py/pull/1106

**Comment by Sug2077** [comment]
> Try this PR #1106

It works , Thank you !
