### ISSUE TITLE
Freature Request: I dont see progress bar fget_object ?

### ISSUE THREAD

**Issue by AkshayAwate** [minio/minio-py#1110]
when i download some files using minio-py using fget_object(), I cant see the progress and how much time it takes to download a file or files.
it is good for some small file but large file, it is take a long time while downloading around more than 100MB's.
so user's doesn't know it is in progress or not.

so could you add option like progress_use  in python minio client?

thanks in advance.

**Comment by balamurugana** [comment]
For custom usage like progress bar etc, please use `get_object()` and handle the returned stream as per your requirement. `get_object()` returns [HTTPResponse](https://urllib3.readthedocs.io/en/latest/reference/urllib3.response.html) and you could have your own way how to show progress bar on every read of the response.
