### ISSUE TITLE
Refresh Token during the upload

### ISSUE THREAD

**Issue by colorzzr** [minio/minio-py#1112]
Hi all!

I integrated MinIO with Keycloak and sdk will use a temporary access token to call the MinIO API. I try to upload a large file(~20GB). But I ran into a situation that if the temporary token expired during uploading, the whole upload process will freeze. Is there any function I can use to refresh/fetch a new token and continue uploading?

Thanks!

**Comment by balamurugana** [comment]
You could use one of suitable credential [provider](https://github.com/minio/minio-py/blob/master/minio/credentials/providers.py). If none suits, write your custom provider and use it accordingly.
