### ISSUE TITLE
breakpoint resume in progress.

### ISSUE THREAD

**Issue by lang07123** [minio/minio-py#1113]
the follow code show size abnormal if breakpoint resume .
[https://github.com/minio/minio-py/blob/master/examples/progress.py](https://github.com/minio/minio-py/blob/master/examples/progress.py)

**Comment by balamurugana** [comment]
Feel free to send a fix

**Comment by lang07123** [comment]
> 
> 
> Feel free to send a fix

how to get breakpoint size ?

`
minio 7.0.3 hint
AttributeError: 'Minio' object has no attribute 'list_incomplete_uploads'
`
sorry for my english .. thanks very much.

**Comment by balamurugana** [comment]
1. Could you clarify what you mean by breakpoint size?
2. Use `_list_multipart_uploads()` internal method. Better to inherit `Minio` for your custom requirements.

**Comment by lang07123** [comment]
>     1. Could you clarify what you mean by breakpoint size?
        **Exception occurs when i use `Minio.fput_object`, how to get uploaded size.**

>     2. Use `_list_multipart_uploads()` internal method. Better to inherit `Minio` for your custom requirements.
        When i aborting  `Minio.fput_object`, the following code returns the empty list
       `client = Minio("192.168.12.34:9000", access_key="minioadmin", secret_key="minioadmin", secure=False,)`
       `objects = client._list_multipart_uploads("lang", "OM-SrvAdmin-Dell-Web-LX-9.3.0-3465_A00.tar.gz")
        print(objects.uploads)`
        **[]
        [Finished in 0.3s]**

**Comment by balamurugana** [comment]
`fput_object()` and `put_object()` never leave stale/incomplete uploads. Go through [api.py](https://github.com/minio/minio-py/blob/master/minio/api.py) for private methods for your custom needs.

**Comment by lang07123** [comment]
> 
> 
> `fput_object()` and `put_object()` never leave stale/incomplete uploads. Go through [api.py](https://github.com/minio/minio-py/blob/master/minio/api.py) for private methods for your custom needs.

thanks very much. I ' ll study it again。
