### ISSUE TITLE
Maybe progress update should be put in _put_object after.

### ISSUE THREAD

**Issue by lang07123** [minio/minio-py#1115]
Minio.fput_object progress update callback in ` read_part_data(data, part_size, progress=progress,)` after.
When file less than 5M  and put_objcet retrying ,will give the illusion of success. Because retrying is long time, but file progress size already 100%.

sorry for my english.

```
client = Minio("xxx:9000", access_key="ggms",secret_key="xxx",secure=False,)
client.fput_object(
	"ggms", "123.py", "C:\\Users\\admin\\Desktop\\minio\\process.py",
	progress=Progress()
)
return: 
123.py: |####################| 0.01 MB/0.01 MB 100% [elapsed: 00:00 left: 00:00,  6.78 MB/sec]
...
...
...
TimeoutError: [WinError 10060] xxxx xxxx xxxx
...
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='172.27.209.115', port=9000): Max retries exceeded with 
```
This problem is more serious with the custom progress.

**Comment by balamurugana** [comment]
Use `put_object()` for more controlled data reads for progress. However `progress.py` in `examples` is a guideline for how a progress bar implementation can be. If you are looking for more controlled progress bar, you would need to have your own progress bar implementation.
