### ISSUE TITLE
How to properly timeout a notification listener?

### ISSUE THREAD

**Issue by neuneck** [minio/minio-py#1117]
I need to load an object from MinIO as soon as it is uploaded. For that, I use the MinIO python client's `Minio.listen_bucket_notification()` and listen for the "s3:ObjectCreated:*" event. The client only listens for a single object.

It can happen that the file does not get created in time. So I want to stop listening for this notification after a while. Looking at the implementation (https://github.com/minio/minio-py/blob/master/minio/api.py#L868), I don't see an option for a timeout, or any proper way for me to close the response and release the connection to MinIO from the outside.

What is the proper way to time out a MinIO client's `listen_bucket_notification()` iterator?

**Comment by balamurugana** [comment]
ATM I couldn't able to find a solution other than writing your own `listen_bucket_notification()` using `Minio._execute()`. A sample code would be something like
```py
def listen_bucket_notification(minio_client, bucket_name, prefix='', suffix='',
                               events=('s3:ObjectCreated:*',
                                       's3:ObjectRemoved:*',
                                       's3:ObjectAccessed:*')):
    check_bucket_name(bucket_name)
    if minio_client._base_url.is_aws_host:
        raise ValueError(
            "ListenBucketNotification API is not supported in Amazon S3",
        )

    response = minio_client._execute(
        "GET",
        bucket_name,
        query_params={
            "prefix": prefix or "",
            "suffix": suffix or "",
            "events": events,
        },
        preload_content=False,
    )

    try:
        for line in response.stream():
            line = line.strip()
            if not line:
                continue
            if hasattr(line, 'decode'):
                line = line.decode()
            event = json.loads(line)
            if event['Records']:
                # TODO: handle the event and break the loop if needed
    except JSONDecodeError:
        pass  # Ignore this exception.
    finally:
        response.close()
        response.release_conn()
```

**Comment by neuneck** [comment]
I don't think I understand. Would I call this in a loop, practically polling the API for the event to show up? 

I don't know MinIO's REST api, to be honest. Is one of the elements here blocking until an event occurs? Or will the default implementation's loop just poll the minio API for events?

**Comment by balamurugana** [comment]
When `GET` request is called, MinIO server starts writing event data as JSON in the HTTP response indefinitely i.e. it never closes the connection. In the response, the server may send empty lines to keep the connection alive.

**Comment by balamurugana** [comment]
@neuneck You could try this PR https://github.com/minio/minio-py/pull/1118

**Comment by neuneck** [comment]
That looks great. Then all I'd have to do is make sure I can cancel the event loop / leave the context after the timeout.

**Comment by neuneck** [comment]
Unfortunately, it raises an AttributeError from l. 802.

To reproduce: create a minio server using the example docker deployment (https://docs.min.io/docs/minio-docker-quickstart-guide.html)

Run
```py
from minio.api import Minio

minio_client = Minio(endpoint="127.0.0.1:9000",
                     access_key="AKIAIOSFODNN7EXAMPLE",
                     secret_key="wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
                     secure=False)

minio_client.make_bucket("example")

with minio_client.listen_bucket_notification("example") as events:
    for event in events:
        print("event")
```

For me this gives
```
Traceback (most recent call last):
  File "/tmp/minio_test.py", line 11, in <module>
    for event in events:
  File "/home/julian/projects/minio-py/minio/datatypes.py", line 802, in __next__
    return self._get_records() or self.__next__()
  File "/home/julian/projects/minio-py/minio/datatypes.py", line 786, in _get_records
    line = self._stream.next().strip()
AttributeError: 'generator' object has no attribute 'next'
```

**Comment by neuneck** [comment]
Replacing
```py
self._stream.next().strip()
```
in line 786 with
```py
next(self._stream).strip()
```
fixes this issue.

**Comment by neuneck** [comment]
Spent some more time with it and with the fix I proposed in my previous comment, this PR produces the behavior I wanted.

For future reference, in case someone else comes in with the same question: I used the Minio client in combination with the TimeoutIterator from the iterators package (https://github.com/leangaurav/pypi_iterator):

This is the code snipped I used to check it works and cleans up the connection:
```py
from minio.api import Minio
from iterators import TimeoutIterator

minio_client = Minio(endpoint="127.0.0.1:9000",
                     access_key="AKIAIOSFODNN7EXAMPLE",
                     secret_key="wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
                     secure=False)


if not minio_client.bucket_exists("example"):
    minio_client.make_bucket("example")

with minio_client.listen_bucket_notification("example") as events:
    it = TimeoutIterator(events, timeout=5)
    for event in it:
        if event is it.get_sentinel():
            print("Sentinel received")
            break
        else:
            print("event")

print(events)
print(events._response)
```

**Comment by neuneck** [comment]
FYI: I also verified that using the `events` object directly, i.e. not as a context manager will leak the connection. Running
```
from minio.api import Minio
from iterators import TimeoutIterator

minio_client = Minio(endpoint="127.0.0.1:9000",
                     access_key="AKIAIOSFODNN7EXAMPLE",
                     secret_key="wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
                     secure=False)


if not minio_client.bucket_exists("example"):
    minio_client.make_bucket("example")

events = minio_client.listen_bucket_notification("example")
it = TimeoutIterator(events, timeout=5)
for event in it:
    if event is it.get_sentinel():
        print("Sentinel received")
        break
    else:
        print("event")

print(events)
print(events._response)
```
Gives 
```
Sentinel received
<minio.datatypes.EventIterable object at 0x7f5c9991ab80>
<urllib3.response.HTTPResponse object at 0x7f5c998cc5e0>
```
Whereas the code above gives 
```
Sentinel received
<minio.datatypes.EventIterable object at 0x7f294a781b80>
None
```

**Comment by neuneck** [comment]
Thank you for the quick action @balamurugana
