### ISSUE TITLE
Running on vmware host directly

### ISSUE THREAD

**Issue by Sx3** [minio/minio-py#1130]
I am trying to install the setup.py on a VMware host
Version: 6.7.0 Update 3 (Build 17499825)
it comes with Python 3.5.9

when I try to install minio-py
```
git clone https://github.com/minio/minio-py
cd minio-py
python setup.py install
```

it throws
```
Traceback (most recent call last):
  File "setup.py", line 20, in <module>
    from setuptools import setup
ImportError: No module named 'setuptools'
```

Basically, I am trying to upload a file from VMware host datastore to minio self-hosted cloud.
any directions?

**Comment by balamurugana** [comment]
@Sx3 You would need to have `setuptools` and respective python packages. My recommendation is to install via `pip` like `pip3 install minio` or download the release from [pypi](https://pypi.org/project/minio/)
