### ISSUE TITLE
How to inform MinIO server that a listener is no longer needed?

### ISSUE THREAD

**Issue by neuneck** [minio/minio-py#1135]
Relates to https://github.com/minio/minio-py/issues/1117

I can now continue the control flow in my Python code and close (interrupt) the listener connection to MinIO from the client side. In our distributed, erasure coding, versioning server deployment, this does not seem to clear up the server side of the listener, though. Over time we accrue a lot of connections between the MinIO instances, a behavior we don't see if we _don't_ listen from the python client. 

How can I, from the client side, set a _time to live_ for the listener on the server side, or alternatively, inform the server that a specific listener is no longer needed?

**Comment by balamurugana** [comment]
`ListenBucketNotification` works like below
MinIO server side:
1. Accepts client request and sends `chunked` value to `Transfer-Encoding` header and starts sending event data
2. If no event data, it sends empty JSON to keep the connection alive
3. If any I/O error on sending data, the connection is dropped at server side.

`minio-py` client side:
1. `Minio.listen_bucket_notification()` returns a iterator object.
2. When the iterator is read, it sends the request to the server and starts reading event data
3. If event data is read, it is returned. If empty JSON is read, it keeps reading data till event data is read.
4. If there is an error in reading data, it starts step (2)

You could stop reading iterator any time and call `EventIterable.__exit__()` to cleanup underneath connections. If you see more than one connection at server from a same python code, means you have a leaky connections and you haven't cleaned those connections properly.
