### ISSUE TITLE
put_object fails for writeonly user

### ISSUE THREAD

**Issue by lbgr0** [minio/minio-py#1137]
I have set up a local minio copy. created a new bucked named "images" with the policy set to upload. 
I further created a testUser with writeonly policy. 

uploading of files using the mc client from a terminal works fine, however using the python API I get a

> S3Error: S3 operation failed; code: AccessDenied, message: Access Denied., resource: /images, request_id: 16968C7542A286F4, host_id: 12daddb9-7e86-4d43-af92-afd337fb3cac, bucket_name: images

when setting the users policy to write+read I can upload, using the same python code. 

code example: 

```

from minio import Minio

client = Minio(
    "localhost:9000",
    access_key="UploadUser",
    secret_key="SECRETKEY",
    secure=False,
)

client.fput_object(  "images", "Testimage.png", "C:\minio\Testimage.png")


```

  Is this a bug? Or do I have to change the config? 

Thanks!

**Comment by vadmeste** [comment]
s3:GetBucketLocation is probably missing here.

You can also enable tracing to see what fails, `client.trace_on(sys.stderr)`

**Comment by balamurugana** [comment]
The error clearly says the user has no permission. You would need to investigate further by adjusting your bucket policy. You could enable `Minio.trace_on()` to look about HTTP traces for respective S3 API failure.

**Comment by lbgr0** [comment]
Hi, 

i further investigated the issue and found the follwing by analyzing the HTTP trace (below is the output for a user with "readwrite" policy), for a user with just "onlywrite" policy, the first "GET ? location" request provokes an "Access denied":
The GET is only requested for the very first call of  put_object() following put_object() calls do not send a GET. 

Is this the expected behaviour? How can I prevent the GET?location call ,or can I adjust the policy of the user to allow this action as well? 
Thanks for your help! 
 

`minIOclient.fput_object("Bucket", "testImage.png", "image.png")`

>  ---------START-HTTP---------
> GET /Bucket?location= HTTP/1.1
> Host: XXX:9000
> User-Agent: MinIO (Windows; AMD64) minio-py/7.1.0
> X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
> X-Amz-Date: 20210810T103356Z
> Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210810/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*
> 
> HTTP/1.1 200
> Accept-Ranges: bytes
> Content-Length: 128
> Content-Security-Policy: block-all-mixed-content
> Content-Type: application/xml
> Server: MinIO
> Strict-Transport-Security: max-age=31536000; includeSubDomains
> Vary: Origin
> Vary: Accept-Encoding
> X-Amz-Request-Id: 1699EB76E975A2FC
> X-Content-Type-Options: nosniff
> X-Xss-Protection: 1; mode=block
> Date: Tue, 10 Aug 2021 10:33:56 GMT
> 

```
> ?xml version="1.0" encoding="UTF-8"?
> LocationConstraint xmlns="http://s3.amazonaws.com/doc/2006-03-01/"></LocationConstraint>
```
> 

> ----------END-HTTP----------
> ---------START-HTTP---------
> PUT /Bucket/testImage.png HTTP/1.1
> Content-Type: application/octet-stream
> Host: XXX
> User-Agent: MinIO (Windows; AMD64) minio-py/7.1.0
> Content-Length: 102227
> Content-Md5: i122nRFFCUdsTj5+iNzenQ==
> X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
> X-Amz-Date: 20210810T103356Z
> Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210810/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*
> 
> HTTP/1.1 200
> Accept-Ranges: bytes
> Content-Length: 0
> Content-Security-Policy: block-all-mixed-content
> ETag: "8b5db69d114509476c4e3e7e88dcde9d"
> Server: MinIO
> Strict-Transport-Security: max-age=31536000; includeSubDomains
> Vary: Origin
> Vary: Accept-Encoding
> X-Amz-Request-Id: 1699EB76EA1805BD
> X-Content-Type-Options: nosniff
> X-Xss-Protection: 1; mode=block
> Date: Tue, 10 Aug 2021 10:33:56 GMT

> ----------END-HTTP----------

**Comment by balamurugana** [comment]
You have two options
1. Add permission to `GetBucketLocation` in your bucket policy (or)
2. Pass region of your bucket as value to `region` arg to `Minio` constructor. This way all S3 APIs use specified region.
