### ISSUE TITLE
Allow path in endpoint for access to custom URL deployments

### ISSUE THREAD

**Issue by pedro-bralv** [minio/minio-py#1140]
So I have my MinIO deployed under "https://my.internal.url/minio/" and when trying to access my endpoint through:

```python
minio = Minio(endpoint="my.internal.url/minio",
                  access_key=access_key,
                  secret_key=secret_key,
                  region=region_name)
```

I get the following:
```ValueError: path in endpoint is not allowed```

If I take out the "/minio" bit, I don't get to access my endpoint because there's no MinIO deployed under "/".

Is there something that I am missing or it just wasn't made for this case?
I don't know if this is intended, but for our current use case where we have other services running under the same base url, it would be nice to have the possibility to access custom url endpoints.

**Comment by balamurugana** [comment]
As per S3 specification and request signing process, path in endpoint is not allowed. You could configure reverse proxy or something similar to expose endpoint without path.
