### ISSUE TITLE
Connection reset by peer using MinIO in python

### ISSUE THREAD

**Issue by AviNash15** [minio/minio-py#1147]
I'm trying to download a file from the MinIO server (localhost:port) using the fget_object method. Whenever I'm sending concurrent requests randomly few requests are failing by error connection reset by peer.
I'm using gunicorn with 4 workers 4 threads for my application. 

```
client.fget_object("test","my_file.zip","output_dir")
  File "/home/app/.local/lib/python3.8/site-packages/minio/api.py", line 1101, in fget_object
    for data in response.stream(amt=1024*1024):
  File "/home/app/.local/lib/python3.8/site-packages/urllib3/response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/app/.local/lib/python3.8/site-packages/urllib3/response.py", line 541, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/app/.local/lib/python3.8/site-packages/urllib3/response.py", line 455, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

```

How can I solve this?

**Comment by balamurugana** [comment]
`urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))` means the server closes the connection. You would need to check why server is closing the connection abnormally.

**Comment by AviNash15** [comment]
yes, I know that, but is it due to concurrent requests with multiple workers & threads trying to download the file. The urllib3 pool manager is not available. that's why it is failing? what is the default timeout for minio and connections?
I know what the error means.
Can you be more specific in your reply.

**Comment by balamurugana** [comment]
If the server is closing connections on parallel requests, there is nothing can be done at client side. You would need to investigate why server is resetting connections. The default `http_client` is created at https://github.com/minio/minio-py/blob/master/minio/api.py#L143. You could pass your own `urllib3.PoolManager` by `http_client` argument to `Minio` class, if you feel to debug at client side.
