### ISSUE TITLE
minio.error.NoSuchKey: NoSuchKey: message: The specified key does not exist.

### ISSUE THREAD

**Issue by patelnikit16** [minio/minio-py#1150]
I am facing the issue of minio.error.NoSuchKey: NoSuchKey: message: The specified key does not exist.

I have setup the minio in local with following step.
./minio server --address ":5050" /home/nikit/data
RootUser: minioadmin 
RootPass: minioadmin 

`def download_object(path, local_path):
    minio_client = Minio(os.environ.get("MINIO_SERVER"), access_key=os.environ.get("ACCESS_KEY"),
                        secret_key=os.environ.get("SECRET_KEY"), secure=False)
    minio_client.fget_object(os.environ.get("BUCKET_NAME"), path, local_path)`

Error:

`File "/home/nikit/Testing_CODE/recobo-form-extraction-custom2-model/recobo_form_custom2/lib/python3.8/site-packages/minio/api.py", line 787, in fget_object
    stat = self.stat_object(
  File "/home/nikit/Testing_CODE/recobo-form-extraction-custom2-model/recobo_form_custom2/lib/python3.8/site-packages/minio/api.py", line 1195, in stat_object
    response = self._url_open(
  File "/home/nikit/Testing_CODE/recobo-form-extraction-custom2-model/recobo_form_custom2/lib/python3.8/site-packages/minio/api.py", line 2222, in _url_open
    raise ResponseError(response,
minio.error.NoSuchKey: NoSuchKey: message: The specified key does not exist.`

**Comment by balamurugana** [comment]
You don't have `path` referring object in your S3 server.
