### ISSUE TITLE
How to use Minio in tests

### ISSUE THREAD

**Issue by MaxG87** [minio/minio-py#1151]
I am trying to write some tests for a high-level abstraction of Minio. For this I would like to have a valid but fresh instance of Minio. I could not find how to make that happen.

I could (and do) mock aspects of Minio. However, this makes the entire test suite quite fragile. Also, I did get several tricky aspects wrong, e.g. the concrete return type of `get_object`. I could fix these, but I think it would be better not to mock Minio at all.

I could use [play.min.io](play.min.io). This would allow me to use a real Minio client. However, then I have tests that depend on (a) the crededentials of the server, (b) network being available and (c) the state [play.min.io](play.min.io) is in. To elaborate a bit on (c), imagine I call `client.make_bucket("test-bucket")`. In my test, that would be very reasonable, but the chances are high that the test fails because "test-bucket" already exists. So I could run `client.make_bucket("my-test-bucket-7dd7468fa5678933f9e92a8c2a23b565d0081276d4b204169be811c9fc83a7eb")` and probably no one else does use this bucket name, but then the success of test run $n+1$ depends on whether or not test run $n$ was able to delete the bucket again.

All in all, I wonder whether there is some kind of test client using the local file system or the RAM as storage, so I can use it in my test suite. It would be very great.

Last but not least: Thank you for your awesome project you have. Besides the test issue above it is really a charm to work with.

**Comment by balamurugana** [comment]
`minio-py` has [functional tests](https://github.com/minio/minio-py/tree/master/tests/functional) which uses `minio` server or `play.min.io`. These tests are also used in [Mint](https://github.com/minio/mint) which test `minio` server. These references will help for testing requirement.
