### ISSUE TITLE
Download all Objects that are newer than a certain time

### ISSUE THREAD

**Issue by vkoukoutsas** [minio/minio-py#1153]
How can someone download (copy to the local filesystem) all the objects that are newer than a certain date and save them as files?
Which method/flags are the suggested? 

I could not find an exact example of this.

Similar to the mc cp command with the --newer-than value:
 mc cp minio/my-bucket ./minio-copy/ --newer-than 30m

This command would download all objects/files that are newer than 30m in the specified bucket.

**Comment by poornas** [comment]
See the example for `mc find` with --exec flag

**Comment by vkoukoutsas** [comment]
Hi Poorna,

I meant to ask how to do what this command does:

> mc cp minio/my-bucket ./minio-copy/ --newer-than 30m

But do the same with the minio-py SDK, which method should I use and with which arguments?
e.g. get_object or another method?

Such a use case is not part of the [get_object.py](https://github.com/minio/minio-py/blob/master/examples/get_object.py) example provided

**Comment by balamurugana** [comment]
`minio-py` is a SDK focused for application/tool development. For `mc` like tool behavior, you would need to write your own code using [list_objects()](https://docs.min.io/docs/python-client-api-reference#list_objects) and [get_object()](https://docs.min.io/docs/python-client-api-reference#get_object) for your requirement.
