### ISSUE TITLE
select_object_content.py  - Example error

### ISSUE THREAD

**Issue by gevabenori** [minio/minio-py#1154]
Hi, 
I tried to run the select_object_content example:
`from minio import Minio
from minio.select import (CSVInputSerialization, CSVOutputSerialization,
                          SelectRequest)

client = Minio(
    "play.min.io",
    access_key="Q3AM3UQ867SPQQA43P2F",
    secret_key="zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG",
)

with client.select_object_content(
        "my-bucket",
        "my-object.csv",
        SelectRequest(
            "select * from S3Object",
            CSVInputSerialization(),
            CSVOutputSerialization(),
            request_progress=True,
        ),
) as result:
    for data in result.stream():
        print(data.decode())
    print(result.stats())`

and I received the following error:
`AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_17881/3721787898.py in <module>
     14         ),
     15 ) as result:
---> 16     for data in result.stream():
     17         print(data.decode())
     18     print(result.stats())

~/.local/lib/python3.8/site-packages/minio/select.py in stream(self, num_bytes)
    442                 yield result
    443 
--> 444             if self._read() <= 0:
    445                 break

~/.local/lib/python3.8/site-packages/minio/select.py in _read(self)
    375     def _read(self):
    376         """Read and decode response."""
--> 377         if self._response.isclosed():
    378             return 0
    379 

AttributeError: 'HTTPResponse' object has no attribute 'isclosed'`

Versions:
minio: 7.1.0
urllib3: 1.22

Thanks

**Comment by balamurugana** [comment]
I just updated a test csv file, it works. Try the example as is.

Please note `play.min.io` can be cleared anytime i.e. `my-bucket` and `my-object.csv` might be removed.
