### ISSUE TITLE
Replication Config Get issue

### ISSUE THREAD

**Issue by Suween** [minio/minio-py#1164]
I'm having an issue with the bucket [get_replication_config](https://docs.min.io/docs/python-client-api-reference.html#get_bucket_replication) function. 

Environment:

I have a local [docker-compose](https://docs.min.io/docs/deploy-minio-on-docker-compose.html) which I want to replicate on a similarly deployed remote cluster. 

Issue: 

From the UI, I can without issue set the replication from one cluster to another. It works great. 

Now I wanted to code it, so first step I did was to try fetching the current replication to see what's inside a Replication Config (And frankly from an editorial side, doc is VERY lacking. I only seem to find info about the bucket class, everything else has to be learn by ourselves). 

Here's the error I get: 

![image](https://user-images.githubusercontent.com/20570625/143256624-eb3c189a-a9d8-4705-9dff-20720beaba91.png)

Seems like the code need a role? But there's no where mention of a 'role' anywhere? Even in the [example](https://docs.min.io/docs/minio-bucket-replication-guide.html), the 'role' key is empty. 

I would understand for a 'set', but for a get? 

Anyway, after investigation, it seem that the issue here is in the function 'toxml' of the 'ReplicationConfig' class. 

![image](https://user-images.githubusercontent.com/20570625/143257570-67806f1c-444a-4775-9ccd-a7eb8674851e.png)

Fetching the 'role' from the http reply, it doesn't seem to find any, so it tries to init it's class with an empty string. But then, raise an error at the 'if not role' line. 

---------------------------------------------------------------------------------------------------------------------------------------------------

Question: I'm I missing where the 'role' must be set? 

Else, I think there's an error in the code logic.

**Comment by balamurugana** [comment]
The S3 server of `GetBucketReplication` API should return valid XML. If no configuration available, the server should return `ReplicationConfigurationNotFoundError`. It seems the server is not returning valid XML. You could enable `Minio.trace_on()` and share the output.

**Comment by Suween** [comment]
Here's the log: 

---------START-HTTP---------
GET /some-bucket?location= HTTP/1.1
Host: 127.0.0.1:9000
User-Agent: MinIO (Windows; AMD64) minio-py/7.1.1
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20211124T163814Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20211124/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*

HTTP/1.1 200
Server: nginx/1.19.2
Date: Wed, 24 Nov 2021 16:38:11 GMT
Content-Type: application/xml
Content-Length: 128
Connection: keep-alive
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Request-Id: 16BA88DBB80B9B70
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

<?xml version="1.0" encoding="UTF-8"?>
<LocationConstraint xmlns="http://s3.amazonaws.com/doc/2006-03-01/"></LocationConstraint>
----------END-HTTP----------
---------START-HTTP---------
GET /some-bucket?replication= HTTP/1.1
Host: 127.0.0.1:9000
User-Agent: MinIO (Windows; AMD64) minio-py/7.1.1
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20211124T163814Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20211124/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*

HTTP/1.1 200
Server: nginx/1.19.2
Date: Wed, 24 Nov 2021 16:38:11 GMT
Content-Type: application/xml
Content-Length: 642
Connection: keep-alive
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Request-Id: 16BA88DBB8C95F20
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

<ReplicationConfiguration><Rule><ID>c6em39bbms9fjtfqslv0</ID><Status>Enabled</Status><Priority>1</Priority><DeleteMarkerReplication><Status>Disabled</Status></DeleteMarkerReplication><DeleteReplication><Status>Disabled</Status></DeleteReplication><Destination><Bucket>arn:minio:replication::a0cd6d61-ecc0-4273-876c-e5f786b58fba:some-bucket</Bucket></Destination><SourceSelectionCriteria><ReplicaModifications><Status>Enabled</Status></ReplicaModifications></SourceSelectionCriteria><Filter><Prefix></Prefix></Filter><ExistingObjectReplication><Status>Enabled</Status></ExistingObjectReplication></Rule><Role></Role></ReplicationConfiguration>
----------END-HTTP----------


As you can see, the 'role' field is empty

Here's a picture of the bucket with the replication I'm trying to get:
![image](https://user-images.githubusercontent.com/20570625/143279469-a55f10dd-3aa4-4c74-afdc-4fcb933fc145.png)

**Comment by balamurugana** [comment]
Please open an issue at server and check why `role` is empty.

**Comment by harshavardhana** [comment]
@balamurugana Role can be empty.

**Comment by kannappanr** [comment]
```
aws s3api --profile play --endpoint-url http://play.min.io get-bucket-replication --bucket test1
{
    "ReplicationConfiguration": {
        "Role": "",
        "Rules": [
            {
                "ID": "c6f9dmm86tqkcl7nd9k0",
                "Priority": 0,
                "Filter": {
                    "Prefix": ""
                },
                "Status": "Enabled",
                "SourceSelectionCriteria": {
                    "ReplicaModifications": {
                        "Status": "Enabled"
                    }
                },
                "ExistingObjectReplication": {
                    "Status": "Disabled"
                },
                "Destination": {
                    "Bucket": "arn:minio:replication::01b83007-9be4-4577-9179-cf5b8a1243aa:test2"
                },
                "DeleteMarkerReplication": {
                    "Status": "Disabled"
                }
            }
        ]
    }
}
```

**Comment by harshavardhana** [comment]
```
~ mc replicate ls myminio-local1/olockbucket
ID                   | Priority | Status   | Prefix                    | Tags                      | DestBucket           | StorageClass   
c6f9eu3rm80f5jf3vr30 | 0        | Enabled  |                           |                           | arn:minio:replica... |                
c6f9evbrm80f5op9nb30 | 2        | Enabled  |                           |                           | arn:minio:replica... |                
```

```
~ python3 get_bucket_replication.py
Traceback (most recent call last):
  File "get_bucket_replication.py", line 26, in <module>
    config = client.get_bucket_replication("olockbucket")
  File "/home/harsha/repos/minio-py/minio/api.py", line 2201, in get_bucket_replication
    return unmarshal(ReplicationConfig, response.data.decode())
  File "/home/harsha/repos/minio-py/minio/xml.py", line 85, in unmarshal
    return cls.fromxml(ET.fromstring(xmlstring))
  File "/home/harsha/repos/minio-py/minio/replicationconfig.py", line 489, in fromxml
    return cls(role, rules)
  File "/home/harsha/repos/minio-py/minio/replicationconfig.py", line 463, in __init__
    raise ValueError("role must be provided")
ValueError: role must be provided
```

**Comment by Suween** [comment]
Tried the Fix, it works! Thank you Very much!
