### ISSUE TITLE
bucket_exists now returns InvalidAccessKeyId leading to uncaught exception

### ISSUE THREAD

**Issue by dpdoughe** [minio/minio-py#1167]
bucket_exists currently checks for 
`if exc.code != "NoSuchBucket"`
but the server seems to be returning a new/different code when the bucket doesn't exists called "InvalidAccessKeyId"
![image](https://user-images.githubusercontent.com/23531138/144117959-fe4a2c79-da2f-4f45-b8a9-9d0e8edb0f45.png)

**Comment by dpdoughe** [comment]
Our Minio server version is:    

Version
    2020-04-02T21:34:49Z
    Platform
    Host: OS: linux | Arch: amd64
    Runtime
    Version: go1.13.8 | CPUs: 4

**Comment by harshavardhana** [comment]
@dpdoughe that doesn't make any sense - looks like your access_key is wrong

> Version
> 2020-04-02T21:34:49Z
> Platform
> Host: OS: linux | Arch: amd64
> Runtime
> Version: go1.13.8 | CPUs: 4

Please upgrade this is too old a setup.

**Comment by dpdoughe** [comment]
My bad. There was a bug on my end that was feeding the wrong config in. All is well. Thanks.
