### ISSUE TITLE
copy object between minio and s3 

### ISSUE THREAD

**Issue by mazen423** [minio/minio-py#1168]
Just a quick simple question, as the mc client is able to define alias and copy from minio bucket and aws s3 bucket. Can that be done also through the SDK ? i'm trying to avoid the download/upload object. Any support is appreciated

**Comment by balamurugana** [comment]
You could do this by 
```py
minioClient = Minio("myminio:9000", ...)
s3Client = Minio("s3.amazonaws.com", ...)
response = minioClient.get_object(...)
result = s3Client.put_object("bucket_name", response, length, ...)
```
