### ISSUE TITLE
How to limit the upload bandwith?

### ISSUE THREAD

**Issue by bucibucii** [minio/minio-py#1172]
I am using this library to upload files periodically into minio server, but i need to limit the upload rate, in order not to create traffic on my network. 
Is it possible to do it?

**Comment by cobolbaby** [comment]
@balamurugana Could you provide a simple demo?

**Comment by fbeqirllari** [comment]
> [@balamurugana](https://github.com/balamurugana) Could you provide a simple demo?

[https://github.com/fbeqirllari/minio-py/tree/throttle-bandwidth](url)
