### ISSUE TITLE
remove_objects generates invalid XML

### ISSUE THREAD

**Issue by cuu508** [minio/minio-py#1185]
The `remove_objects` method generates a XML request which includes the following: `<Quiet>True</Quiet>`. I suspect the boolean value should not be capitalized, it should be `true`.

The [AWS documentation for the DeleteObjects call](https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObjects.html) describes the "Quiet" field as boolean.

The [XML schema spec](https://www.w3.org/TR/xmlschema-2/#boolean) says the boolean datatype should have lowercase values – true|false.

I've been testing minio-py with Scaleway and OVH object storage, and both rejected the uppercase `True`. When I patched my local minio-py copy to not put the `Quiet` field in the request XML, the remove_objects calls worked as expected with both Scaleway and OVH. 

PS. After I reported the issue, Scaleway have already fixed their S3 interface to accept `<Quiet>True</Quiet>`, and OVH is working on it. Still, it would be good to fix minio-py to send lowercase true|false, so it works with with other S3 implementations too.

**Comment by harshavardhana** [comment]
> I've been testing minio-py with Scaleway and OVH object storage, and both rejected the uppercase `True`. When I patched my local minio-py copy to not put the `Quiet` field in the request XML, the remove_objects calls worked as expected with both Scaleway and OVH.

This works perfectly fine with AWS S3 @cuu508 and MinIO what is the problem with Scaleway and OVH?

**Comment by cuu508** [comment]
They expect the boolean datatype to be `true`|`false`, not `True`|`False`.
