### ISSUE TITLE
Create IAM Policies with Python

### ISSUE THREAD

**Issue by Pythonov** [minio/minio-py#1191]
Is it possible to create policies with Python?
Like this
![image](https://user-images.githubusercontent.com/61191665/161094286-146261fd-c958-4b4f-8f61-ad6d85d9b8b2.png)

Didn't find anything in docs, only bucket policies

Thanks!

**Comment by balamurugana** [comment]
Creating policy JSON is out of scope of `minio-py`. `minio-py` has APIs to set/get/delete bucket policy.
