### ISSUE TITLE
No way to update metadata in copyObject

### ISSUE THREAD

**Issue by nununoisy** [minio/minio-py#1192]
Hello,

I am trying to use `copyObject` to copy a file over itself while updating `lastModified` on it. However, this fails with this error:
```
S3Error: This copy request is illegal because it is trying to copy an object to itself without changing the object's metadata, storage class, website redirect location or encryption attributes.
```
I've noticed that some of the other client libraries do include metadata fields in their `copyObject` - however I can also see how adding a parameter would introduce a potentially breaking change.

I can work with either of these two solutions:
- Update lastModified when copying an object onto itself
- Adding a parameter for new metadata
- Adding an overflow method that replaces the `conditions` parameter with an object (an example):
```js
const conds = new Minio.CopyConditions();
const options = {
    conditions: conds,
    metadata: {
        lastModified: new Date()
    }
}
client.copyObject('bucket', 'prefix/file', '/bucket/prefix/file', options, callback);
```

For now I will have to stick with the download/reupload workaround - but using `copyObject` will be far more efficient.

Thank you!

**Comment by balamurugana** [comment]
Why is this issue relevant to current `minio-py`?

**Comment by philkunz** [comment]
@kannappanr Whats the status on this one?

**Comment by philkunz** [comment]
Also, why is this in the py section? This is about js?
