### ISSUE TITLE
BytesIO.write(...): OSError: stream having not enough data;expected: n, got: 0 bytes (put_object)

### ISSUE THREAD

**Issue by skei0** [minio/minio-py#1193]
Python: 3.9 
Minio sdk: 7.1.5

When i do this: 

```python
from minio import Minio 
from io import BytesIO

client =  Minio(...)

data = BytesIO()
data.write(b"hello minio")
length = data.getbuffer().nbytes

client.put_object("test", "data.test.txt", data, length)

```
I get this ERROR: ``` OSError: stream having not enough data;expected: 11, got: 0 bytes ``` Not sure if this is the desired behavior! Maybe i miss something.

I can hot-fix it by doing this:
```python
...
new_data = BytesIO(data.getbuffer())
client.put_object("test", "data.test.txt", new_data, length)

```
Also this ``` data = BytesIO(b'hello minio') ``` is working as well. 

Thanks for your work, i like minio =)

**Comment by balamurugana** [comment]
What is your question? Are you testing how `BytesIO` behaves?

**Comment by skei0** [comment]
This is simple. If I have a ```BytesIO``` object and I write something into the object I also expect the whole object to be uploaded with ```pub_object```... I don't understand why this doesn't happen here. And yes I don't know if it's ```BytesIO``` or Minio... if you think this behavior is normal ok. Just thought I'd show you.

**Comment by skei0** [comment]
it was ```BytesIO``` i needed to use ```seek(0)```. did not know that.
https://stackoverflow.com/questions/26879981/writing-then-reading-in-memory-bytes-bytesio-gives-a-blank-result
