### ISSUE TITLE
how to http?

### ISSUE THREAD

**Issue by j2l** [minio/minio-py#1199]
With distant client uploading to a local S3 with endpoint "172.23.0.2:9123" (S3 container, something else uses port 9000), I get error:
`HTTPSConnectionPool(host='172.23.0.2', port=9123): Max retries exceeded with url: /bucket1?location= (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb79aa0d610>: Failed to establish a new connection: [Errno 111] Connection refused'))`

changing minio-py endpoint to `http://172.23.0.2:9123` results in `AttributeError: 'Minio' object has no attribute '_http'`

Any idea?

**Comment by balamurugana** [comment]
Please refer examples in https://github.com/minio/minio-py/tree/master/examples.

**Comment by j2l** [comment]
I did @balamurugana 
None has http protocol. Only localhost is switched to http by default, rest is https AFAIK

**Comment by balamurugana** [comment]
Use` `secure=False` to `Minio` class and refer our documentation.
