### ISSUE TITLE
HTTP status 304 treated as an error

### ISSUE THREAD

**Issue by bbonenfant** [minio/minio-py#1201]
When a `304 Not Modified` response is returned from the server, this library raises an `minio.InvalidResponseError`. This status code is a valid response when checking whether the entity tag of an object has changed, i.e. for caching purposes. For example:
```python
client: minio.Minio
client.make_bucket("example-304-error")
object = client.put_object("example-304-error", "blob", io.BytesIO(b"hello"), 5)
response = client.get_object("example-304-error", "blob", request_headers={"If-None-Match": f'"{object.etag}"'})
```
raises the following error:
```
minio.error.InvalidResponseError: non-XML response from server; Response code: 304, Content-Type: None, Body: None
```

Depending on how (or if) this library wants to handle 304 statuses, adding it as one of the options to the following line fixes the issue in my experimentation: https://github.com/minio/minio-py/blob/1f60dc95e0373ee07ebd9532bd486ae6248f02df/minio/api.py#L281

**Comment by balamurugana** [comment]
`minio-py` shouldn't treat 304 as success. It is user's responsibility to handle it to success or failure. However `InvalidResponseError` statng `non-XML response from server` is not correct. I will send a fix for that.
