### ISSUE TITLE
'Minio' object has no attribute '_http'

### ISSUE THREAD

**Issue by doyus** [minio/minio-py#1204]
The compiler version and package version are the same as the local machine, but the Linux environment keeps reporting an error: no attribute _http, why is this?
![image](https://user-images.githubusercontent.com/37011721/170975389-1ef81336-c91c-4935-9293-c9e2264a96db.png)

**Comment by Lucidiot** [comment]
This might be occurring because something in the `Minio` constructor caused an error, any of those lines: https://github.com/minio/minio-py/blob/2067045ccad998831414647b9cb23e506d1c3e1a/minio/api.py#L120-L141

Here's an example in a Python shell with minio 7.1.8:

```python
>>> from minio import Minio
>>> client = Minio(None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lucidiot/.virtualenvs/backend/lib/python3.8/site-packages/minio/api.py", line 131, in __init__
    ("https://" if secure else "http://") + endpoint,
TypeError: can only concatenate str (not "NoneType") to str
>>> exit()
Exception ignored in: <function Minio.__del__ at 0x7f3c7818da60>
Traceback (most recent call last):
  File "/home/lucidiot/.virtualenvs/backend/lib/python3.8/site-packages/minio/api.py", line 155, in __del__
    self._http.clear()
AttributeError: 'Minio' object has no attribute '_http'
```

**Comment by balamurugana** [comment]
Why are you passing `None` to endpoint?

**Comment by Lucidiot** [comment]
This was purely an example to show how you could get the AttributeError later, I can just make the constructor crash in other ways and this always ends up in `self._http` not being defined, causing the AttributeError:

```python
Minio('example.com', http_client="not an http client!")
Minio('example.com', access_key='something')
```

Both of those will cause some errors, so the `self._http = …` code is never reached, and the attribute is never defined. So when `__del__` is called, the attribute does not exist and the destructor causes an error.

**Comment by arLevi** [comment]
@Lucidiot I also experienced this issue
There's a strange change of behavior between versions(my assumption)

```
# Before - such code would have worked
Minio('example.com', http_client="not an http client!")
Minio('example.com', access_key='something')

# After - only by adding endpoint= (positional argument) - it works (?!)
Minio(endpoint='example.com', http_client="not an http client!")
Minio(endpoint='example.com', access_key='something')
```

The same issue appears in other functions as well, such as `add_service_account`
