### ISSUE TITLE
Need REST API or python API for minio admin (similar to madmin-go)

### ISSUE THREAD

**Issue by mukhtar-inamdar** [minio/minio-py#1206]
Hi,
I need Admin functionality:
- API in python like 'madmin-go' or
- REST API interface.

that I need to call from our client.

**Comment by balamurugana** [comment]
Refer https://github.com/minio/minio-py/blob/master/minio/minioadmin.py

**Comment by mukhtar-inamdar** [comment]
Is there any example to create an instance of MinioAdmin as the parameters don't match with the minio client?
and is this the same as APIs from 'madmin-go'?

**Comment by balamurugana** [comment]
It is nothing complicated in `MinioAdmin`. It is just a wrapper to `mc admn` command. Feel free to look into `mc admin` and `MinioAdmin` source.
