### ISSUE TITLE
Expose max_keys in list_objects

### ISSUE THREAD

**Issue by Lucidiot** [minio/minio-py#1207]
I am calling `list_objects` to only retrieve up to 20 objects at a time. Minio [uses a default of 1000](https://github.com/minio/minio-py/blob/2067045ccad998831414647b9cb23e506d1c3e1a/minio/api.py#L2722) for `max_keys`, so it ends up requesting 1000 objects to S3 when I only need the 20 first objects.

`Minio._list_objects` has a `max_keys` argument, so I can use `client._list_objects(..., max_keys=20)`, but it would be a lot cleaner to have that be available in `Minio.list_objects` as well.

**Comment by balamurugana** [comment]
`Minio.list_objects()` is higher level APIs over `Minio._list_objects()` which deals with low level S3 APIs. If you want to deal with low level S3 APIs, you just inherit `Minio` in your custom class or use such low level APIs directly.
