### ISSUE TITLE
save excel file into minio

### ISSUE THREAD

**Issue by russele7** [minio/minio-py#1210]
Hi all.  I am working with Minio in python.  And I need to save excel file into Minio, but I found examples in open sources for csv-file only . Does anyone have example python-code for excel-file (or for zip-file as alternative)?  (P.S. In my case I need to save exactly excel file, not a csv. Because resulting file have several sheets and drawings inside). Thank you in advance.

**Comment by balamurugana** [comment]
Use `put_object()` and refer example https://github.com/minio/minio-py/blob/master/examples/put_object.py
