### ISSUE TITLE
Multiple Files Upload -Async/Multiprocessing

### ISSUE THREAD

**Issue by akirs82** [minio/minio-py#1211]
Hello Everyone,

I am new to "uploading files to cloud" kind of tasks. I have a requirement where i want to upload multiplt files at once in an asynchronous way and in batches if possible. Going thrugh the documentation it was not clear how async batch uploads are handled or even batch uploads for these kind of tasks  

1. Should we use asyncio to write a custom code on top of the existing minio put_object api calls OR
2. Should we use multiprocessing libraries OR 
3. What is the best practice here ? ANy libraries etc?

**Comment by harshavardhana** [comment]
multiprocessing is easier to use @akirs82 not sure about asyncio

**Comment by balamurugana** [comment]
`put_object()` uses threads to upload parts in parallel. You could use the same for multiple files upload.  However there is no specific recommendation to use `minio-py` WRT multiple files upload.
