### ISSUE TITLE
presigned_get_object failed with AccessDenied

### ISSUE THREAD

**Issue by rmGFW** [minio/minio-py#1224]
minio-py version : 7.1.10

this is the IAM configuration 
<img width="754" alt="image" src="https://user-images.githubusercontent.com/66858140/180108063-ffccab88-2ba1-4427-88d3-1c24ffaaf2f0.png">

i  presigned for file in path workspace/infra/xxxx/some/file 
<img width="811" alt="image" src="https://user-images.githubusercontent.com/66858140/180108225-c24c1beb-5738-434d-a61a-7e367267f952.png">

i found that if i change the resouce to arn:aws:s3:::workspace*, the AccessDenied no longer

**Comment by balamurugana** [comment]
Not all actions support path. You should check S3 policy documentation. If you still see the problem, check with your server. There is nothing can be done at client side.
