### ISSUE TITLE
put_object stalls when connection to server is lost

### ISSUE THREAD

**Issue by tea-more** [minio/minio-py#1226]
I am running a Minio server and client on two machines. When uploading a (large) file to the bucket and the client loses connection with the server, the thread stalls without throwing an error.

My Minio is configured as follows:
```
Minio(
    endpoint=..some adress..,
    access_key=..minio access key..,
    secret_key=..minio secret key..,
    secure=False,
    http_client=PoolManager(
        timeout=20,
        maxsize=10,
        cert_reqs='CERT_REQUIRED',
        ca_certs=..certificates..,
        retries=urllib3.Retry(
            total=2,
            respect_retry_after_header=False,
        )
    )
)
```
After the upload, I disconnect the Minio server and get `urllib3.connectionpool` Retry warnings (expected), but they conclude in the program stalling. 
```
urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at ...>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')'
```

The issue is that the `_tasks_queue` in the `ThreadPool` class is not configured to timeout. The program stalls on `task = self._tasks_queue.get()` when the Queue keeps waiting without returning or throwing an error. 

I couldn't find a way to configure a timeout for `get` or verify that the connection is active, so an error is thrown when it is not.

**Comment by balamurugana** [comment]
Please try the latest release
