### ISSUE TITLE
corrupted output when num_bytes is smaller than payload length

### ISSUE THREAD

**Issue by zhanggefan** [minio/minio-py#1228]
Hi dev team of minio-py,

First of all, thanks for your excellent work!

I happened to notice that the following code might give corrupted output when `num_bytes` is smaller than `self._payload` size. Note that the `yield` does not `continue` the while loop, so the following `self._read()` won't be bypassed and will be called at the start of the next iteration, which overwrites the `self._payload` not yet finished reading. In such a situation, the last message's payload will also be truncated. Did you make it like this on purpose? Or is it simply a bug?

https://github.com/minio/minio-py/blob/8de41f078b83addd43724412537e0a5f9669ae14/minio/select.py#L418-L432

**Comment by balamurugana** [comment]
Refer https://github.com/minio/minio-py/pull/1225
