### ISSUE TITLE
MinIO `secure` parameter still tries to verify the certificate

### ISSUE THREAD

**Issue by lopezco** [minio/minio-py#1230]
`minio.Minio` with `secure=False` still checks the certificate.

Would you consider changing this code bloc: https://github.com/RiverBank-Eu/minio-py/blob/master/minio/api.py#L142-L152

```python
        self._http = http_client or urllib3.PoolManager(
            timeout=urllib3.util.Timeout(connect=timeout, read=timeout),
            maxsize=10,
            cert_reqs='CERT_REQUIRED',
            ca_certs=os.environ.get('SSL_CERT_FILE') or certifi.where(),
            retries=urllib3.Retry(
                total=5,
                backoff_factor=0.2,
                status_forcelist=[500, 502, 503, 504]
            )
        )
```

to 

```python
if secure:
    cert_params = dict(
        cert_reqs='CERT_REQUIRED', 
        ca_certs=os.environ.get('SSL_CERT_FILE') or certifi.where()
    )
else:
    cert_params = dict(
        cert_reqs='CERT_NONE',
    )

self._http = http_client or urllib3.PoolManager(
    timeout=urllib3.util.Timeout(connect=timeout, read=timeout),
    maxsize=10,
    retries=urllib3.Retry(
        total=5,
        backoff_factor=0.2,
        status_forcelist=[500, 502, 503, 504]
    )
    **cert_params 
)
```

or something similar. 

I can write a Pull Request

**Comment by harshavardhana** [comment]
Secure=False means - you are using plain-text not TLS Insecure - if you want insecure then you need to bring your own http_client @lopezco

**Comment by lopezco** [comment]
I got confused by the docstrings:
```   
 :param secure: Flag to indicate to use secure (TLS) connection to S3
        service or not.
```
I would expect that `secure=False` would use http ([which is the case of the flag](https://github.com/RiverBank-Eu/minio-py/blob/master/minio/api.py#L131)) therefore, no certificate check.

**Comment by harshavardhana** [comment]
> 
> I would expect that `secure=False` would use http ([which is the case of the flag](https://github.com/RiverBank-Eu/minio-py/blob/master/minio/api.py#L131)) therefore, no certificate check.

No that is not entirely correct Secure=False is plain-text not SkipCertCheck - for SkipCertCheck the connection is still Secure just that it is not "trusted". 

That is why you need  to provide your own http_client that basically does CERT_NONE we cannot anticipate this based on `Secure=True|False` alone
