### ISSUE TITLE
[feature request] Support for Client Side Encryption

### ISSUE THREAD

**Issue by frittentheke** [minio/minio-py#1232]
While there is support for multiple ways of doing service-side encryption (SSE) with
* https://github.com/minio/minio-py/issues/682
* https://github.com/minio/minio-py/issues/683
* https://github.com/minio/minio-py/issues/684

the client unfortunately cannot do client-side encryption yet, removing the need to trust an S3 service in any way but with the durability and availability of the bits stored there.

AWS does clearly document their client side encryption implementations at https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingClientSideEncryption.html and lists which of their SDKs have this implemented:

* [AWS SDK for .NET](https://aws.amazon.com/sdk-for-net/)
* [AWS SDK for Go](https://aws.amazon.com/sdk-for-go/)
* [AWS SDK for Java](https://aws.amazon.com/sdk-for-java/)
* [AWS SDK for PHP](https://aws.amazon.com/sdk-for-php/)
* [AWS SDK for Ruby](https://aws.amazon.com/sdk-for-ruby/)
* [AWS SDK for C++](https://aws.amazon.com/sdk-for-cpp/)

strangely this feature is not (yet) implemented in the boto3 Python SDK (see my issue at https://github.com/boto/boto3/issues/3395) 
which had me look for other commonly used Python libraries, like minio-py, potentially supporting this.

So here I am proposing to add this feature to your Python library and to make it compatible with data written by the other (AWS) SDKs.

**Comment by balamurugana** [comment]
It is deliberate design not to support client side encryption in the SDK. This can be easily achievable at API consumer side by wrapping input/output stream by required encryption/decryption with custom metadata headers.
