### ISSUE TITLE
Cannot preview objects pushed with Python client

### ISSUE THREAD

**Issue by mmelcot** [minio/minio-py#1238]
When adding an object with the `put_object` of the Python client, the resulting object in MinIO has a broken content-type and cannot be previewed.

Using this simple example from the [official page](https://docs.min.io/docs/python-client-api-reference.html#put_object):
```
result = client.put_object(
    "my-bucket", "my-object", io.BytesIO(b"hello"), 5,
    content_type="application/csv",
)
```
It results in the 'broken' content-type icon, and the impossibility to preview the file.
![image](https://user-images.githubusercontent.com/22167439/189651109-7e6fb20d-2e79-4e38-b1ff-4e134d97a68a.png)

Although the `content-type` is correctly set:  
![image](https://user-images.githubusercontent.com/22167439/189651594-18ae823b-a303-4af8-b674-7cfab111e6b3.png)

**Comment by balamurugana** [comment]
If UI is not interpreting `content-type` properly, it is UI bug and open an issue appropriately.
