### ISSUE TITLE
client.put_object( ) --> AttributeError: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by davesuketu215** [minio/minio-py#1241]
Python 3.10.2
minio-py: 7.1.11

Receiving the below error in client.put_object( ) API Call
Traceback attached here:
<img width="828" alt="image" src="https://user-images.githubusercontent.com/68798855/192783140-6042b8c5-11cf-477f-874b-6bdb24c2d80b.png">

Just a background: I am calling the MinIO API from a Flask Service. The API call is done periodically with the same set of parameters. Basically dumping a JSON file in a MinIO Path. Everything works well, but at one specific point all of a sudden this error comes. However, this error came just today and not until yet. The API Call parameters are the same

Could you check and let me know why this comes up?

**Comment by balamurugana** [comment]
Your server must return `etag` header on successful `put_object()`. Please check your server why it didn't return `etag` header.

**Comment by whbing** [comment]
I have the same problem. Using the s3 boto3 client is no problem. I printed the response of boto3 and minio as follows:
boto3:
```xml
{
	'ResponseMetadata': {
		'RequestId': 'f85f6dc0-b31c-4890-97cc-5cd4ff683ecb',
		'HostId': '4O4jLERCm',
		'HTTPStatusCode': 200,
		'HTTPHeaders': {
			'date': 'Wed, 26 Oct 2022 14:09:54 GMT',
			'cache-control': 'no-cache',
			'expires': 'Wed, 26 Oct 2022 14:09:54 GMT',
			'pragma': 'no-cache',
			'content-type': 'text/plain;charset=utf-8',
			'x-content-type-options': 'nosniff',
			'x-xss-protection': '1; mode=block',
			'x-frame-options': 'SAMEORIGIN',
			'server': 'Ozone',
			'x-amz-id-2': '4O4jLERCm',
			'x-amz-request-id': 'f85f6dc0-b31c-4890-97cc-5cd4ff683ecb',
			'content-length': '0'
		},
		'RetryAttempts': 0
	}
}
```
minio:
```xml
HTTPHeaderDict({
	'Date': 'Wed, 26 Oct 2022 14:00:54 GMT',
	'Cache-Control': 'no-cache',
	'Expires': 'Wed, 26 Oct 2022 14:00:54 GMT',
	'Pragma': 'no-cache',
	'Content-Type': 'text/plain;charset=utf-8',
	'X-Content-Type-Options': 'nosniff',
	'X-XSS-Protection': '1; mode=block',
	'X-FRAME-OPTIONS': 'SAMEORIGIN',
	'Server': 'Ozone',
	'x-amz-id-2': 'JH5YwMORQqMbffK',
	'x-amz-request-id': 'f6883807-7031-48e5-9b43-d1aeb1d44c51',
	'Content-Length': '0'
})
```
Is this code redundant in api.py? Or check to see if there is an `etag` and then replace?
```python
            response.getheader("etag").replace('"', ""),
```

**Comment by whbing** [comment]
@balamurugana  PTAL

**Comment by balamurugana** [comment]
@whbing You would need to fix your server.
