### ISSUE TITLE
MinioAdmin needs mc installed on local machine

### ISSUE THREAD

**Issue by Rocking80** [minio/minio-py#1243]
I checked `MinioAdmin` class in `minioadmin` file. It seems for admin we can only execute admin commands instead of the rest api way as `Minio`? So this needs `mc` executable to be installed and configured on local machine, right? This is not convenient and has much limitation in automation.

**Comment by balamurugana** [comment]
Yep. It requires `mc` on local machine. Please feel free to send a PR to use `urllib3`.
