### ISSUE TITLE
This  minio python api:<remove_objects> has a bug

### ISSUE THREAD

**Issue by Liangzijiangit** [minio/minio-py#1244]
Bug from mino/deleteobjects.py
The code below：

class DeleteObject:
    """Delete object request information."""

    def __init__(self, name, version_id=None):
        self._name = name
        self._version_id = version_id

    def toxml(self, element):
        """Convert to XML."""
        element = SubElement(element, "Object")
        SubElement(element, "Key", self._name)
        if self._version_id is not None:
            SubElement(element, "VersionId", self._version_id)
        return element

class DeleteRequest:
    """Delete object request."""

    def __init__(self, object_list, quiet=False):
        self._object_list = object_list
        self._quiet = quiet

    def toxml(self, element):
        """Convert to XML."""
        element = Element("Delete")
        if self._quiet:
            SubElement(element, "Quiet", "true")
        for obj in self._object_list:
           
            **obj.toxml(element)**  #_'str' object has no attribute 'toxml'， I think you should have forgotten to call this DeleteObject_
            # new_obj = DeleteObject(obj)
            # new_obj.toxml(element)
        return element

**Comment by balamurugana** [comment]
@Liangzijiangit feel free to send a PR

**Comment by balamurugana** [comment]
@Liangzijiangit `object_list` argument to `DeleteRequest`  must be list of `DeleteObject`
