### ISSUE TITLE
Django minio doesnt save image file with exception argument error

### ISSUE THREAD

**Issue by burakertr** [minio/minio-py#1245]
Hi, 
I read the image file from database and get the corresponding image file from media folder. Then I rotate it and delete the old file and save the new file with the following code;

```
img = Image.objects.filter(listing=lst, id=int(id)).first()
imagepointer = pImage.open(img.image_file)
imagepointer = imagepointer.rotate(-1 * rot, expand=True)
output = BytesIO()
imagepointer.save(output, format=format)
imageout = InMemoryUploadedFile(output, 'ImageField',
                                                    img.image_file.name,
                                                    'image/jpeg',
                                                    sys.getsizeof(output), None)
img.image_file.delete(save=False)
img.image_file = imageout
img.save()
```
The code works flawlessly with aws s3 storage but not working with my self hosted minio instance. It gives error as:

`minio.error.InvalidArgumentError: InvalidArgumentError: message: Could not read 158078 bytes from data to upload
`
I am using minio_storage.storage.MinioMediaStorage. What do I do wrong?

**Comment by balamurugana** [comment]
You would need to open an issue in corresponding project.
