### ISSUE TITLE
Cannot connect to api with ip address!

### ISSUE THREAD

**Issue by burakertr** [minio/minio-py#1246]
Hi,

I am using Minio with creating the instance below, from my local machine;

```
    client = Minio(
        "10.0.0.2:9000",
        access_key="***",
        secret_key="***",

    )
```
where 10.0.0.2 is the local ip of the minio server. But  when I try to do a client.bucket_exists, I get the following error defining ("hostname '10.0.0.2' doesn't match either of 'cdn.xx.com' ))) where cdn.xx.com is the domain I set for the minio server for lets encrypt ssl. 

How can I connect with the ip address instead of the hostname or domain name?

**Comment by balamurugana** [comment]
You would need to create a custom http client and validate your certificate or try https://stackoverflow.com/questions/61380617/ssl-certificateerror-hostname-example-com-doesnt-match-either-of-exampleser
