### ISSUE TITLE
No way to set fetch_owner from list_objects

### ISSUE THREAD

**Issue by dmosesson** [minio/minio-py#1254]
There is no way to specify `fetch_owner=True` from `list_objects` 

`_list_objects` supports it, but it is never called with that as a parameter (only usage of that function I can find is here: https://github.com/minio/minio-py/blob/master/minio/api.py#L1820)

**Comment by dmosesson** [comment]
Is there a reason it shouldn't be be exposed? if not, I'll send the PR.
Is there equivalent functionality that should be made available in stat_object for fetching owner? If its small I can get everything at once

**Comment by balamurugana** [comment]
We add functionalities on demand. There was no requirement for `fetch_owner`. `stat_object()` is entirely different thing. Refer https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadObject.html

**Comment by dmosesson** [comment]
PR posted: https://github.com/minio/minio-py/pull/1255

**Comment by balamurugana** [comment]
Fixed by https://github.com/minio/minio-py/pull/1255
