### ISSUE TITLE
Connect / use dropbox business? 

### ISSUE THREAD

**Issue by horsto** [minio/minio-py#1257]
I wondered whether I can use my dropbox business account for s3/minio compatible storage, but I am stuck trying to figure out how to do it / whether it is possible at all. Does anybody have experience with that? 
It seems like endpoints and authorisation exist (https://www.dropbox.com/developers/documentation/http/documentation), but I am not sure how to initialise things.

**Comment by harshavardhana** [comment]
Dropbox is not an S3 API - this SDK is only meant to be used with S3 API endpoints.
