### ISSUE TITLE
Handling "Bucket name does not follow S3 standards" for trailing dash

### ISSUE THREAD

**Issue by cal-pratt** [minio/minio-py#1261]
I've been using the boto libraries for a while and wanted to switch over to using the Minio library for the simpler interface.
We're using a self hosted solution implementing S3 (using Ceph, not Minio server or AWS S3).

One thing we've caught is that some of our bucket names are being rejected because they end with a dash `-`, by `check_bucket_name` https://github.com/minio/minio-py/blob/039ff29d76a45427498d04153ddc74776f5d777f/minio/helpers.py#L203-L213

I understand that ending with a dash is allowed in the proper S3 spec, but this is how our buckets are currently configured and it would be a significant amount of engineering work to change it. I was wondering if we could allow ending with a dash for the non-strict regex? That would help a lot!

-------

PS. I've tested with the following hack and everything seems to work how I would expect:

```py
from minio import Minio
import minio.helpers
minio.helpers._VALID_BUCKETNAME_REGEX = re.compile(
    '^[A-Za-z0-9][A-Za-z0-9\\.\\-\\_\\:]{1,61}[A-Za-z0-9-]$'  # allowed to end with -
)

client = Minio(
    endpoint=my_endpoint,
    access_key=my_access_key,
    secret_key=my_secret_key,
)
client.fget_object("some-bucket-", "some.file", "some.file")
```

**Comment by cal-pratt** [comment]
Another option that might be less invasive to other users is to allow users to provide their own validation regex's as part of the `Minio.__init__` method.

**Comment by balamurugana** [comment]
[Bucket naming rules](https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html) does not allow `-` at the end and we don't want to support non-standard names.

You could inherit `Minio` class for all custom requirements.

**Comment by cal-pratt** [comment]
@balamurugana this seems to be hardcoded in the module constant. Could you explain how I could avoid it with inheritance?
