### ISSUE TITLE
list_objects does not return metadata in version > 7.1.0

### ISSUE THREAD

**Issue by flyattimes** [minio/minio-py#1263]
I am using minio server with version: RELEASE.2022-08-08T18-34-09Z
Using minio-py 7.1.0, this enables me to access metadata as expected:

`res = self.client.list_objects(bucket_name, prefix=folder, include_user_meta=True, recursive=True)`
`for r in res:`  
`    print(r.metadata['X-Amz-Meta-Mymetadata'])`

Using 7.1.3 however, the above code will raise a KeyError, because list_objects returns an empty dict for metadata.
The list_objects() docs do still include the "include_user_meta" flag.

On the other hand, a recent minio server release together with 7.1.3 is working as expected.

The best fix for me is to set minio-py version to 7.1.0.

This inconsistent behaviour may be cause for concern when an upgrade of the minio server should occur.

**Comment by harshavardhana** [comment]
You need to upgrade your MinIO server @flyattimes to match the new changes in list objects with metadata.

Or you need to stick to older client version that works with your version of MinIO.

**Comment by flyattimes** [comment]
@harshavardhana thank you for the swift response
