### ISSUE TITLE
return 'version_id' = None while fput_object

### ISSUE THREAD

**Issue by sam-leonid** [minio/minio-py#1264]
When I updated version of Minio to '2023-01-20T02:05:44Z', I saw that fput_object return 'version_id' = None sometimes.

When it happens:

1. Many fput_object in one bucket.
2. Transfer large files with fput_object

```python
    minio_obj = minio_client.fput_object(
        bucket_name=bucket_name,
        object_name= object_name)
```

When I exec `minio_obj .__dict__` -> I see `'_version_id': None`.

I try about 10 versions of minio package, but this problem is stayed.

All parameters in minio_client.fput_object are default.

**Comment by balamurugana** [comment]
Have you enabled bucket versioning? Refer https://github.com/minio/minio-py/blob/master/docs/API.md#set_bucket_versioning

**Comment by sam-leonid** [comment]
> Have you enabled bucket versioning? Refer https://github.com/minio/minio-py/blob/master/docs/API.md#set_bucket_versioning

Yes, it's enable

**Comment by sam-leonid** [comment]
I found the solution:

By default, fput_object calc part_size (parameter for deviding data by chunks for transfering) by [formula](https://github.com/minio/minio-py/blob/039ff29d76a45427498d04153ddc74776f5d777f/minio/helpers.py#L131-L134). 

And for all files with size < 49 Gb part_size=5Mb.

When I set this size to 50Mb (calculated by my own tests) the problem is gone.

```python
client.fput_object(
    bucket_name=bucket_name,
    object_name= name,
    part_size=50*1024*1024)
```
