### ISSUE TITLE
Minio.list_objects does not support request headers

### ISSUE THREAD

**Issue by aaron-mar** [minio/minio-py#1278]
I was trying to use the x-minio-extract feature to list objects in a zip file as outlined in this blog posting: 

https://blog.min.io/small-file-archives/

There is a way to use this feature to get objects using the request_header parameter in Minio.get_object(), but it seems to be missing for the Minio.list_objects() method. Is there another way to use this feature for Minio.list_objects()? If not, can it be added?

**Comment by balamurugana** [comment]
Feel free to send a PR like https://github.com/minio/minio-py/blob/master/minio/api.py#L2828 supporting `extra_headers` and `extra_query_params`
