### ISSUE TITLE
mc cp --recursive --rewind equivalent

### ISSUE THREAD

**Issue by robin-deltares** [minio/minio-py#1279]
At Deltares we want to transition our testbench data sets to Minio and retrieve the versions of the sets on the basis of timestamps.

This works very well from commandline (mc cp --recursive --rewind <timestamp> <source> <destination>) but we want to utilize minio-py in our current testbench-workflow Python-scripts.

There seem to be some copy_conditions, but none that cover our use-case?

**Comment by balamurugana** [comment]
Tool like behavior needs to be built on top on `minio-py` SDK, not inside `minio-py`

**Comment by robin-deltares** [comment]
For anybody that stumbles upon this while searching for a similar solution:
https://github.com/robin-deltares/minio-py-rewind/
