### ISSUE TITLE
MinioAdmin.policy_add() triggers an mc deprecation error

### ISSUE THREAD

**Issue by ctengel** [minio/minio-py#1293]
Upon calling

`minio.MinioAdmin().policy_add()`

The following error is returned:
`subprocess.CalledProcessError: Command '['/home/minio/mc', '--json', 'admin', 'policy', 'add', 'alias', 'policy', 'policy.json']' returned non-zero exit status 1.`

Upon closer investigation, it appears that `mc admin policy add` is being run, and on recent versions of mc, the following error is returned from that
`mc: <ERROR> Deprecated command. Please use 'mc admin policy create' instead.`

minio-py version 7.1.5 ; mc version RELEASE.2023-08-08T17-23-59Z

Assuming this was a recent change to mc, I am guessing minio-py`s minioadmin.py needs to be slightly changed to accommodate this.

**Comment by ctengel** [comment]
See minio/mc#4428 and minio/mc#4498

**Comment by balamurugana** [comment]
Feel free to send a PR

**Comment by balamurugana** [comment]
Stay tuned!
