### ISSUE TITLE
Request to add user svcacct feature to minio-py

### ISSUE THREAD

**Issue by cyberayu** [minio/minio-py#1307]
The access keys section displays all Access Keys associated to the authenticated user.

I found that minio-py lacks support for mc admin user svcacct. I searched through all the code and didn't find any mention of svcacct. This is surprising. Perhaps other users also need this. I need to complete the code for this module in the next few days. If needed, I can submit these codes to this repository

[User Management](https://min.io/docs/minio/linux/administration/identity-access-management/minio-user-management.html)

**Comment by balamurugana** [comment]
PRs are welcome. Please feel free to send a PR

**Comment by Alveel** [comment]
I am working on this in my fork: https://github.com/Alveel/minio-py/tree/service-accounts

**Comment by cyberayu** [comment]
> I am working on this in my fork: https://github.com/Alveel/minio-py/tree/service-accounts

What a coincidence! After Piotr Borowski refactored the minioadmin module, the content I had previously written happened to become unusable. As I was going through his refactoring, I was also planning to complete this part of the content, and then I came across your submission. Well done! I can refactor the content in our project now.

**Comment by Alveel** [comment]
Well my fork and PR is done, now for the maintainers :)
