### ISSUE TITLE
Calling stat_object results in exception not well-formed (invalid token): line 1, column 49

### ISSUE THREAD

**Issue by mohanasundaramchandran** [minio/minio-py#1310]
I have a minio server running on my local computer.
I am using Minio Python API to see if an object exists.
I am using the following code to see if an object exists in the server.

`minio_client.stat_object(bucket_name, digest)`

`bucket_name` and `digest` are valid values. However, the digest does not exist in the minio server.
Hence I expected that I would get NoSuchKey.  However, I got `minio.error.InvalidXMLError`

The exception is raised from error.py in the below line
`root = ElementTree.fromstring(self._response.data)`
The self._response.data looks like this

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Not Found</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Not Found</h2>
<hr><p>HTTP Error 404. The requested resource is not found.</p>
</BODY></HTML>

```
Looks like double quotes is the culprit.
What am I doing wrong?
Please help.

**Comment by balamurugana** [comment]
Use correct minio server port, not console port for your S3 requests.

**Comment by mohanasundaramchandran** [comment]
@balamurugana 
Thanks for your response.
I am using the right port.
It is also throwing the right error 404 as the object is not in the server.
However, while parsing the 404 error it throws `minio.error.InvalidXMLError`
The error points to line 1 column 49 which is double quote in the response.
The double quotes are malformed.
