### ISSUE TITLE
AccessDenied，get_presigned_url 

### ISSUE THREAD

**Issue by dayhappy2012** [minio/minio-py#1315]
env:    

minio 7.1.17     
minio/minio:RELEASE.2023-10-07T15-07-38Z

![image](https://github.com/minio/minio-py/assets/47685606/e21b21e3-b147-41c9-b08e-91bcacaa7490)

minio 7.1.17     
minio/minio:  2 years ago version  is  ok 

get_presigned_url ( )     extra_query_params = {"X-Amz-Meta-Xxxx": "xxxx"}

**Comment by dayhappy2012** [comment]
Help with that. Thank you

**Comment by balamurugana** [comment]
Refer https://requests.readthedocs.io/en/latest/api/#requests.Request how to use query parameters.

**Comment by dayhappy2012** [comment]
sorry， example2 is error ,  

    # example1
    result = client.get_presigned_url("PUT", "test", "111213")
    res = requests.put(result, files=files)
    print('example1', res.status_code, res.content)

    # example2
    result = client.get_presigned_url("PUT", "test", "111111", extra_query_params={"X-Amz-Meta-Xxxx": "xxx"})
    res = requests.put(result, files=files)
    print('example2', res.status_code, res.content)

now example1 is ok !    example2  is  error !


error info:

example1 200 b''

example2 400 b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>AccessDenied</Code><Message>There were headers present in the request which were not signed</Message><Key>111111</Key><BucketName>test</BucketName><Resource>/test/111111</Resource><RequestId>178D86F3E036A104</RequestId><HostId>dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8</HostId></Error>'
