### ISSUE TITLE
Whether to use the python sdk to create access keys？

### ISSUE THREAD

**Issue by xujuchao** [minio/minio-py#1329]
![Minio access keys](https://github.com/minio/minio-py/assets/58095560/c8b689f1-0cc2-43ab-9cd7-f1201f5fb7f3)

The arrows above indicate that the console can create access keys. Does the Python sdk work?

**Comment by balamurugana** [comment]
Access and secret keys are like username and password of your choice. You could use any values for that.

**Comment by xujuchao** [comment]
My scenario is that I want to use Python to retrieve the minio-py sdk and then automatically create buckets and set the authorization of buckets, but I can't find any information about how to automatically create an access keys from the MinioAdmin method, because I understand that after automatically creating buckets, policy authorization is based on access keys, so I don't know if there is a way to do this?

**Comment by balamurugana** [comment]
Please refer https://github.com/minio/minio-py/blob/master/minio/minioadmin.py#L282

**Comment by xujuchao** [comment]
I may not have been clear, I'm sorry, I want to know this URLhttps://github.com/minio/minio-py/blob/master/minio/minioadmin.py#L282 about I give you a screenshot of the picture - refers to the access keys to create this functionality, Can I create access keys using the SDK?

**Comment by xujuchao** [comment]
If possible, could you please mark and cut a picture?
