### ISSUE TITLE
feature(idp): Add idp (previously admin idp) endpoints 

### ISSUE THREAD

**Issue by Dzordzu** [minio/minio-py#1337]
Identity Providers endpoints are not covered. The following `mc` command alternatives are not present:

- `mc idp ldap` and similar
- `mc idp openid`

**Comment by harshavardhana** [comment]
@Dzordzu sounds like a great idea. Feel free to send a PR. 

We are closing this issue since we need cycles to work on this.

**Comment by Dzordzu** [comment]
Opened a PR: #1344

**Comment by Dzordzu** [comment]
@harshavardhana can you open this issue for the time of the feature development?
