### ISSUE TITLE
BUG: Encrypted messages above 16k are not decrypted

### ISSUE THREAD

**Issue by Dzordzu** [minio/minio-py#1343]
## Steps to reproduce

1. Prepare minio installation with over 3k buckets with many user/group bindings. Ideally these bindings should contain entities with long names.
2. Call an endpoint responsible for listing entities with respective affiliations
3. An error occurs: `MAC check failed`

**Comment by pbrw** [comment]
I just checked and this bug is also present in [MinIO Java SDK](https://github.com/minio/minio-java)

**Comment by Dzordzu** [comment]
I assume that it will be present everywhere, outside of the go implementation
