### ISSUE TITLE
How to Set the Bucket Policy to Private?

### ISSUE THREAD

**Issue by xujuchao** [minio/minio-py#1349]
我想通过Python sdk实现设置桶的策略为私有，请问如何实现？

![image](https://github.com/minio/minio-py/assets/58095560/20ac36e5-4a85-468c-ac58-3f27e368524f)

**Comment by xujuchao** [comment]
I want to use Python sdk to set the bucket policy to private, how to achieve?

**Comment by balamurugana** [comment]
What is the equivalent `mc admin` command you are using?

**Comment by xujuchao** [comment]
I didn't find it, but the bucket I created through the Python sdk has an Access policy of n/a. If this is not specified, does it default to private without having to select "private"?

![image](https://github.com/minio/minio-py/assets/58095560/8826b20f-5324-4cbb-a159-6a8630cb43f5)

**Comment by balamurugana** [comment]
You would need to know respective `mc` command to map respective minio admin API in minio-py
