### ISSUE TITLE
Does Python SDK support custom IAM policies?

### ISSUE THREAD

**Issue by xujuchao** [minio/minio-py#1360]

**Comment by balamurugana** [comment]
How do you do this with `mc` tool?

**Comment by xujuchao** [comment]
我并没有找到关于mc工具相关的参数，但是Minio Console支持基于IAM Policy，正常Minio sdk 也会支持吧？
   
![image](https://github.com/minio/minio-py/assets/58095560/f2bd6382-f443-4040-b4ba-8c09a9557cbb)

**Comment by xujuchao** [comment]
I didn't find any parameters related to the mc tool, but the Minio Console supports IAM Policy based, will the normal Minio sdk also support it?

![image](https://github.com/minio/minio-py/assets/58095560/8d2cd6ad-e5f8-4933-bf3f-654a2f12136e)

**Comment by balamurugana** [comment]
Refer IAM policy related APIs in `minioadmin.py`

**Comment by xujuchao** [comment]
I just read this is based on group or user dimension, I prefer IAM Access key Policy, does Python SDK support it?
