### ISSUE TITLE
Remove hard dependency on urllib3>2

### ISSUE THREAD

**Issue by alanvgreen** [minio/minio-py#1382]
It would be very helpful if one of anehx's suggestions in #1378 could be implemented, allowing either a later version of urllib3 1.x.x or urllib3 2 to be used.

botocore3 - a package that many minio users would have installed simultaneously with minio - has the requirement [`'urllib3>=1.25.4,<2.1 ; python_version >= "3.10"'`](https://github.com/boto/botocore/blob/0b1f9dc807af961c7345457b3a8ec68eb616083d/setup.py#L29C1-L29C55). minio is obviously not the first project to encounter versioning drama due to urllib3's v1 vs v2 changes.

For our organisation, mandating urllib3>2 at this point is difficult. There are many unfortunate first and third party dependencies and a surprising number of conda environments that need to be updated to use urllib3, and we are only part way through the process. Happy to discuss the situation further, but I don't believe we are unique in finding version pinning issues time consuming to deal with. It wouldn't surprise me to learn that, across all of minio's users, adding the requirement of urllib3>2 caused a thousand hours' unscheduled work.

Implementing a softer transition from urllib3 v1 to v2 will make it easier to upgrade our other package dependencies on urllib3.

**Comment by harshavardhana** [comment]
We will see how this can be done @alanvgreen

**Comment by dhilazo** [comment]
Agree with @alanvgreen this can lead to `ImportError` in any package using minio too. It happened to me in `pymilvus` where I got `ImportError: cannot import name 'BaseHTTPResponse' from 'urllib3.response'` due to the v2 breaking change

**Comment by suyuchenxm** [comment]
@dhilazo  any solutions to fix this issue? Thanks!

**Comment by dhilazo** [comment]
@suyuchenxm if you are referring to the `pymilvus` case, you might have to manually specify version lower than `7.2.1` for `minio` in your requirements. [Since pymilvus doesn't specify any version for minio](https://github.com/milvus-io/pymilvus/blob/d58447a8433752d3a97d8a6cb497dada63959f1e/requirements.txt#L39) you will have to do it yourself unfortunately.

The bugfix `7.2.2` doesn't have this problem as it specifies the hard requirement of having urllib3>2 but since pypi by default tries to install the latest version, it will install version 7.2.1 which contains this bug. Imho, [release 7.2.1](https://pypi.org/project/minio/7.2.1/) should be removed from the pypi registry

**Comment by harshavardhana** [comment]
> @suyuchenxm if you are referring to the `pymilvus` case, you might have to manually specify version lower than `7.2.1` for `minio` in your requirements. [Since pymilvus doesn't specify any version for minio](https://github.com/milvus-io/pymilvus/blob/d58447a8433752d3a97d8a6cb497dada63959f1e/requirements.txt#L39) you will have to do it yourself unfortunately.
> 
> The bugfix `7.2.2` doesn't have this problem as it specifies the hard requirement of having urllib3>2 but since pypi by default tries to install the latest version, it will install version 7.2.1 which contains this bug. Imho, [release 7.2.1](https://pypi.org/project/minio/7.2.1/) should be removed from the pypi registry

7.2.1 will stay as is, move to v7.2.2 if you can if not stay at v7.2.0 - until a different workaround is found.

You simply have conflicting dependency using two different SDKs for the same work.

You could use a custom namespaced deployment where you are using virtualenv.

There are various workarounds.

**Comment by harshavardhana** [comment]
I upgraded successfully all the dependencies and everything checkout file and works without anything breaking.

```
 pip install minio --upgrade
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: minio in /home/harsha/.local/lib/python3.10/site-packages (7.2.2)
Requirement already satisfied: pycryptodome in /home/harsha/.local/lib/python3.10/site-packages (from minio) (3.19.1)
Requirement already satisfied: urllib3>=2.0 in /home/harsha/.local/lib/python3.10/site-packages (from minio) (2.0.7)
Requirement already satisfied: argon2-cffi in /home/harsha/.local/lib/python3.10/site-packages (from minio) (23.1.0)
Requirement already satisfied: certifi in /home/harsha/.local/lib/python3.10/site-packages (from minio) (2022.12.7)
Requirement already satisfied: typing-extensions in /usr/lib/python3/dist-packages (from minio) (3.10.0.2)
Requirement already satisfied: argon2-cffi-bindings in /home/harsha/.local/lib/python3.10/site-packages (from argon2-cffi->minio) (21.2.0)
Requirement already satisfied: cffi>=1.0.1 in /home/harsha/.local/lib/python3.10/site-packages (from argon2-cffi-bindings->argon2-cffi->minio) (1.15.1)
Requirement already satisfied: pycparser in /home/harsha/.local/lib/python3.10/site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->minio) (2.21)

[notice] A new release of pip available: 22.2.2 -> 23.3.2
[notice] To update, run: python3 -m pip install --upgrade pip

```

```
pip install minio 
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: minio in /home/harsha/.local/lib/python3.10/site-packages (7.2.2)
Requirement already satisfied: pycryptodome in /home/harsha/.local/lib/python3.10/site-packages (from minio) (3.19.1)
Requirement already satisfied: urllib3>=2.0 in /home/harsha/.local/lib/python3.10/site-packages (from minio) (2.0.7)
Requirement already satisfied: typing-extensions in /usr/lib/python3/dist-packages (from minio) (3.10.0.2)
Requirement already satisfied: argon2-cffi in /home/harsha/.local/lib/python3.10/site-packages (from minio) (23.1.0)
Requirement already satisfied: certifi in /home/harsha/.local/lib/python3.10/site-packages (from minio) (2022.12.7)
Requirement already satisfied: argon2-cffi-bindings in /home/harsha/.local/lib/python3.10/site-packages (from argon2-cffi->minio) (21.2.0)
Requirement already satisfied: cffi>=1.0.1 in /home/harsha/.local/lib/python3.10/site-packages (from argon2-cffi-bindings->argon2-cffi->minio) (1.15.1)
Requirement already satisfied: pycparser in /home/harsha/.local/lib/python3.10/site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->minio) (2.21)

[notice] A new release of pip available: 22.2.2 -> 23.3.2
[notice] To update, run: python3 -m pip install --upgrade pip
```

```
>>> from minio import Minio
>>> 
>>> client = Minio("play.min.io",
...     access_key="Q3AM3UQ867SPQQA43P2F",
...     secret_key="zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG",
... )
>>> for i in client.list_objects("testbucket"):
...     print(i.object_name)
... 
testdata
>>> 
>>> import minio
>>> minio.__version__
'7.2.2'
```

```
aws s3api list-buckets --profile s3
{
    "Buckets": [
        {
            "Name": "219432304946-us-east-1-bhdl-talend-dev-va",
            "CreationDate": "2022-02-25T12:54:02.000Z"
        },
```

Both of them work fine along with urllib2.0 upgraded dependency.

**Comment by balamurugana** [comment]
Please check PR https://github.com/minio/minio-py/pull/1384 solves your problem.

**Comment by alonme-loops** [comment]
@balamurugana when can we expect a release with this fix?

**Comment by minio-trusted** [comment]
Removed hard dependency with v7.2.3
