### ISSUE TITLE
Append file content：part size 1706920 is not supported; minimum allowed 5MiB

### ISSUE THREAD

**Issue by kkzzhhqq** [minio/minio-py#1387]
I want to use the fput_object interface and pass in the part_size parameter to append the content of a file in the bucket. When I pass in part_size < 5MiB, an error is reported: ValueError: part size 1706920 is not supported; minimum allowed 5MiB
example：
`client.fput_object(
    bucket_name="my bucket",
    object_name="my object name",
    file_path="my file path",
    part_size=position
)`

**Comment by balamurugana** [comment]
According to S3 specification object append is not possible.
