### ISSUE TITLE
minio.error.S3Error: S3 operation failed; code: AccessDenied

### ISSUE THREAD

**Issue by kerwincwc** [minio/minio-py#1398]
![image](https://github.com/minio/minio-py/assets/81196748/a99ebcbe-bc52-479c-b252-2123709a5d7b)

I am new with minio. I am using the python SDK, but I am getting an error when trying to start up my flask app. This is the error I am getting. I am trying to use a domain to access bucket. When I am using my local IP address (127.0.0.1:9000), I am able to get my app running, but when I switch to the domain name I then get this error. Can anyone help me with this?

minio.error.S3Error: S3 operation failed; code: AccessDenied, message: Access Denied., resource: /templatebucket, request_id: 17B167A27DD1D7D8, host_id: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8, bucket_name: templatebucket

**Comment by balamurugana** [comment]
Looks like you have MinIO server setup issue. Please refer server documentation.
