### ISSUE TITLE
[feature] Addition of exclude prefixes when adding versioning to buckets

### ISSUE THREAD

**Issue by VerdantForge** [minio/minio-py#1401]
I'm currently adding versioning to some buckets used for job asset storage. These have some temporary files which I don't want to be versionned.
The `mc` cli tool allows us to specify `--exclude-prefixes` when setting up versionning as per [the docs](https://min.io/docs/minio/linux/administration/object-management/object-versioning.html#id9)

This results in the following config
```json
{
 "Op": "info",
 "status": "success",
 "url": "local/my-bucket",
 "versioning": {
  "status": "Enabled",
  "MFADelete": "",
  "ExcludedPrefixes": [
   "prefix1, prefix2"
  ]
 }
}
```

The python clients `VersioningConfig` class however only seems to support `status` and `mfa_delete`.

Due to this I'm forced to launch `mc` in a shell from python to complete this configuration step.

Would it be possible to add this option to VersionningConfig?

**Comment by balamurugana** [comment]
@VerdantForge This is minio server specific extension 
```go
// BucketVersioningConfiguration is the versioning configuration structure
type BucketVersioningConfiguration struct {
	XMLName   xml.Name `xml:"VersioningConfiguration"`
	Status    string   `xml:"Status"`
	MFADelete string   `xml:"MfaDelete,omitempty"`
	// MinIO extension - allows selective, prefix-level versioning exclusion.
	// Requires versioning to be enabled
	ExcludedPrefixes []ExcludedPrefix `xml:",omitempty"`
	ExcludeFolders   bool             `xml:",omitempty"`
}
```

Feel free to send a PR

**Comment by VerdantForge** [comment]
Aight working on the PR now

**Comment by VerdantForge** [comment]
> @VerdantForge This is minio server specific extension
> 
> ```go
> // BucketVersioningConfiguration is the versioning configuration structure
> type BucketVersioningConfiguration struct {
> 	XMLName   xml.Name `xml:"VersioningConfiguration"`
> 	Status    string   `xml:"Status"`
> 	MFADelete string   `xml:"MfaDelete,omitempty"`
> 	// MinIO extension - allows selective, prefix-level versioning exclusion.
> 	// Requires versioning to be enabled
> 	ExcludedPrefixes []ExcludedPrefix `xml:",omitempty"`
> 	ExcludeFolders   bool             `xml:",omitempty"`
> }
> ```
> 
> Feel free to send a PR

PR added https://github.com/minio/minio-py/pull/1402

**Comment by balamurugana** [comment]
Fixed by https://github.com/minio/minio-py/pull/1402
