### ISSUE TITLE
Install requirement not observed (python 3.6)

### ISSUE THREAD

**Issue by smalenfant** [minio/minio-py#1405]
I have a bunch of servers using the minio client 7.1.12-14 which works fine under Python 3.6 (Cento 7). Although installing a new hosts fails because it wants to installed 7.2.5 (need to compile packages).

Looks like there was an intention to block 7.1.9 to use python 3.7 but the install requirement is not observed.

Installing 7.1.16 on python 3.6 works. 7.1.17.
Minimum python requirement changed as minor release.

I'm writting this issue as an observer/user but looks like from some documentation, there should be something like this added to setup to prevent a library to be installed (and fail):

```
setup(
   ...
   python_requires='>=3.7'
   ...
)
```

**Comment by balamurugana** [comment]
Yep. We do not support EOL'ed versions. We remove python 3.7 support soon.

**Comment by smalenfant** [comment]
@balamurugana The intent of this bug was to restrict users from installing an unsupported version of the python client. Currently, if you issue a `pip install minio`, you get the latest version no matter which python version you have which can be avoided.

**Comment by balamurugana** [comment]
@smalenfant feel free to send a PR
