### ISSUE TITLE
IMDS V2 support for AWS

### ISSUE THREAD

**Issue by ShuaiShao93** [minio/minio-py#1411]
It seems we don't support [IMDS V2](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html) endpoint in [IamAwsProvider](https://github.com/minio/minio-py/blob/master/minio/credentials/providers.py#L455-L465). Is it possible to support it?

**Comment by balamurugana** [comment]
@ShuaiShao93 feel free to send a PR

**Comment by setu4993** [comment]
I'll have a PR for this in the next couple of days.
