### ISSUE TITLE
MinIO Client not able to connect with a hosted domain.

### ISSUE THREAD

**Issue by Shudh25** [minio/minio-py#1420]
MinIO Client not able to connect with a hosted domain.

I am using MinIO python client to connect with MinIO, when i am running it in a docker conatainer on my local it is working as expected and i can create buckents in my minio.

`from minio import Minio
client = Minio(
    "localhost:9000",
    access_key="Q3AM3UQ867SPQQA43P2F",
    secret_key="zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
)`
[](https://min.io/docs/minio/linux/developers/python/API.html)

but, when i host the minio in my on prem cluster and use an ingress example: "**https://minio.temp.com**"
i'm using the same code and when i create bucket.

`client = Minio(
    "minio.temp.com",
    access_key="Q3AM3UQ867SPQQA43P2F",
    secret_key="zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
)`

`client.make_bucket("myBucket")`

**It is giving an error "INVALID ARGUMENT ERROR"**

When i am opening this in my browser  "**https://minio.temp.com**" is available and i can login and create buckets using the MinIO UI.

**Comment by balamurugana** [comment]
Check what port your MinIO S3 service is running and use it in the endpoint accordingly.
