### ISSUE TITLE
java.net.SocketException: Connection reset error

### ISSUE THREAD

**Issue by chatnord** [minio/minio-py#1425]
Hi,

thanks for your work! I am using your library to download a series of files from AWS S3 (multiprocessing) and, from time to time, I get a `java.net.SocketException: Connection reset` error. I understand that, from time to time, AWS could get stuck. Is there a parameter I can set somewhere to retry a few times, instead of crashing? I reckon `boto3` has some option like this.

Thank you!

**Comment by balamurugana** [comment]
Pass your custom http client to `Minio` class.
