### ISSUE TITLE
Memory leak when use fget_object function

### ISSUE THREAD

**Issue by Hieu-github** [minio/minio-py#1426]
I am using fget_object function to download a list file in Minio Server. But the monitor show me something strange
![image](https://github.com/minio/minio-py/assets/81610119/67b3f052-4da8-4380-95ea-f6fa966a9553)

The memory increases over time.

I try debug with Memory_profiler module and the result are in the image below
![image](https://github.com/minio/minio-py/assets/81610119/6e2665ed-b319-4cf4-898b-f1a867d7dfa8)

Enviroment:
+ container
+ image: python:3.8-slim
+ cpu: amd64
+ minio sdk version: minio==7.2.7
+ file size: 3kb - 20kb

**Comment by balamurugana** [comment]
I see `0.3MiB` increment in the profile output. Are you referring as memory leak?

**Comment by Hieu-github** [comment]
@balamurugana yes. And in the next call, the memory is not release 0.3MiB.

**Comment by balamurugana** [comment]
It could be http client connection pool thing. Use `get_object()` and handle file download your own. Check the memory usage on the process.

**Comment by Hieu-github** [comment]
When I use `get_object()` func. the result is
![image](https://github.com/minio/minio-py/assets/81610119/89385c70-e3b5-4e21-82c5-722d7f77f111)
I realized that The code doesn't seem to fully reclaim the memory allocated to the response stream.

**Comment by balamurugana** [comment]
It is urllib3 connection pool thing. Pass your own pool manager to `Minio` class for optimization.
