### ISSUE TITLE
RequestTimeTooSkewed

### ISSUE THREAD

**Issue by Martiix** [minio/minio-py#1428]
We have a minio server and docker containers as clients trying to copy objects from one bucket to another on the same server. Uploading and downloading works fine, but sometimes on the copy_object action we get the error RequestTimeTooSkewed. 

The error often happens during moving of large artifacts bigger than 5GB, which makes sense since copy_object only supports up to 5Gib, but it sometimes happens on smaller artifacts with less than 1GB as well.  So since the large artifacts take longer, it could be a coincidence that it happens often on the same big artifact.

We create a minio object and then use that object to copy over multiple files in a for loop which can at times take 20-30 minutes. Does the timestamp come from creating the minio object or at the time of call to copy_object?

example error:
minio.error.S3Error: S3 operation failed; code: RequestTimeTooSkewed, message: The difference between the request time and the server's time is too large., resource: /***/filename

This started happening when we started running the client in a docker container and simultaneously upgraded from minio major version 6 to 7. Both docker container and host is on UTC time, same as the minio server. 

Any help appreciated!

**Comment by balamurugana** [comment]
It looks like your requests held long time somewhere in the middle at the time of MinIO server upgrade. I am not sure what can be done at client side in this situation. As you know the server is in the middle of upgrade, retrying your client is the right way to do.

**Comment by Martiix** [comment]
I have added a retry to the function, but still facing this when the server is under high load. Any other suggestions?

**Comment by balamurugana** [comment]
You would need to check the server why it is failing with RequestTimeTooSkewed
