### ISSUE TITLE
Minioadmin delete members group

### ISSUE THREAD

**Issue by SowaSova** [minio/minio-py#1443]
Hello!

First of all, great thanks for the Admin API functionality

For now, as I get it right we cannot delete group while users are there? And I see that nor "group_add" method nor "group_remove" doesn't give us the functionality for that, because "isRemove" parameter is only for a Group obj:
```
        data = {
            "group": group_name,
            "isRemove": True
        }
        if members is not None:
            data["members"] = members
```
and even if we send data like with isRemove=False with needed list of users, they want be removed from group

**Comment by balamurugana** [comment]
> For now, as I get it right we cannot delete group while users are there?

Logically it should be. If you see any issues, open it with MinIO server.
