### ISSUE TITLE
No WebIdentityToken send in action AssumeRoleWithWebIdentity after upgrading from 7.2.9 to 7.2.10

### ISSUE THREAD

**Issue by ivotentijexxllnc** [minio/minio-py#1456]
After updating to minio-py from 7.2.9 to 7.2.10, we noticed that all our requests to S3 (actual Amazon S3) were failing with 400 Bad Request
We use K8s ServiceAccount for S3 access
We think it might have been caused by: https://github.com/minio/minio-py/pull/1446/files

An example of how our code looks like:
`with open("test.txt", "w") as destination:
    minioClient = minio.Minio(
        credentials=minio.credentials.IamAwsProvider(),
        endpoint="s3.eu-west-1.amazonaws.com",
        secure=True,
        region="eu-west-1",
    )

    file_data = minioClient.get_object(
        bucket_name="our_bucket",
        object_name="object_in_bucket",
    )

    for chunk in file_data.stream(128 * 1024):
        destination.write(chunk)`

**Comment by balamurugana** [comment]
I think we do not support `access_token` tag anymore. @donatello should have more insight.

**Comment by crd1985** [comment]
I have the same problem. 

It is counterintuitive that an increment in the patch version of a package breaks compatibility. The change proposed in https://github.com/minio/minio-py/pull/1446/files should have been discussed and released under a new major version, or at least been explained in the same PR or an issue.
