### ISSUE TITLE
Invalid Address Used for IMDSv2

### ISSUE THREAD

**Issue by sam-mosleh** [minio/minio-py#1459]
When using `IamAwsProvider` to retrieve credentials, the address used to fetch the session token is invalid, resulting in an error.

## Steps to reproduce
Run the following code snippet in an EC2 instance:
```python
from minio.credentials.providers import IamAwsProvider
IamAwsProvider().retrieve()
```
### Expected Behavior
The credentials should be retrieved successfully without any errors.
### Actual Behavior
An exception is raised:
```
ValueError: http://169.254.169.254/role-name failed with HTTP status code 404
```
## Additional Context
- EC2 instance has IMDSv2 set to Required (IMDSv1 is disabled)
- Versions: `master`, `7.2.11`
- Related to #1437

**Comment by balamurugana** [comment]
I am closing on behalf of https://github.com/minio/minio-py/pull/1465
