### ISSUE TITLE
Use last object if NextMarker is not set and IsTruncated is true

### ISSUE THREAD

**Issue by fkautz** [minio/minio-py#152]
NextMarker may not be populated, use the last object seen if this is the case.

**Comment by harshavardhana** [comment]
> NextMarker may not be populated, use the last object seen if this is the case.

All recursive cases need to handle this since we won't have the NextMarker available. Here is the sample implementation in golang library 

~~~
  switch {
        case recursive == true:
                var marker string
                for {
                        result, err := a.listObjects(bucket, marker, prefix, "", 1000)
                        if err != nil {
                                ch <- ObjectStatCh{
                                        Stat: ObjectStat{},
                                        Err:  err,
                                }
                                return
                        }
                        for _, object := range result.Contents {
                                ch <- ObjectStatCh{
                                        Stat: object,
                                        Err:  nil,
                                }
                                marker = object.Key                <<<-------- Right here 
                        }
                        if !result.IsTruncated {
                                break
                        }
                }
~~~ 

In-fact for a delimited case we don't need to handle NextMarker since we are going to be printing 1000 at a time anyways and traversing through delimiter is based on prefix so we are good.

**Comment by harshavardhana** [comment]
> In-fact for a delimited case we don't need to handle NextMarker since we are going to be printing 1000 at a time anyways and traversing through delimiter is based on prefix so we are good.

In-fact now that i think about it delimited but more than 1000 entries could be a valid case with in the delimited and prefixed path. Need to fix this across all libraries too.
