### ISSUE TITLE
Putting a small object that is too large or too small should fail before sending request

### ISSUE THREAD

**Issue by fkautz** [minio/minio-py#171]
Both of these should fail before sending request:
```py
# put an object with length set too small.
client.put_object(bucket, 'string_object', 10, 'hello world')

# put an object with length set too large
client.put_object(bucket, 'string_object', 12, 'hello world')
```

**Comment by harshavardhana** [comment]
Note:  Perhaps we can type this error appropriately with IncompleteBody() one of the valid s3 error responses.

**Comment by fkautz** [comment]
S3's failure response says there is a mismatch in x-amz-sha256 (Not sure why, perhaps they are pre-allocating and testing that buffer). In the java library, we created a custom DataSizeMismatchException. We can do the same here.
