### ISSUE TITLE
Version in git repo doesn't match pypi?

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-py#230]
https://github.com/minio/minio-py/blob/master/minio/__init__.py#L20

We should commit the version number here first before we push.

**Comment by abperiasamy** [comment]
Go ahead and remove this release.  This is totally not acceptable.

**Comment by fkautz** [comment]
Based on previous conversation, this was redacted, and latest version published as 0.2.1.

**Comment by harshavardhana** [comment]
Same here, tag 0.2.1
