### ISSUE TITLE
ntp running & synchronized. 

### ISSUE THREAD

**Issue by koolhead17** [minio/minio-py#285]
In our documentation it should be clearly mentioned that machine should have ntp installed and working for time synchronization.

$ python listB.py
Traceback (most recent call last):
  File "listB.py", line 11, in <module>
    buckets = client.list_buckets()
  File "/usr/local/lib/python2.7/dist-packages/minio/minio.py", line 194, in list_buckets
    raise err
minio.error.ResponseError: ResponseError: code: RequestTimeTooSkewed, message: The difference between the request time and the current time is too large., request_id: 70BE74CEACD1EBBE,host_id: T26jT/YGRZjNc5QYC47+S0U/5LzPzgJpgaw4mWxWjwS6CWzO9U28bv9Uyh8MpWUkP77fPgCyzu8=, resource: None, xml: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>RequestTimeTooSkewed</Code><Message>The difference between the request time and the current time is too large.</Message><RequestTime>20151124T221801Z</RequestTime><ServerTime>2015-11-25T19:24:47Z</ServerTime><MaxAllowedSkewMilliseconds>900000</MaxAllowedSkewMilliseconds><RequestId>70BE74CEACD1EBBE</RequestId><HostId>T26jT/YGRZjNc5QYC47+S0U/5LzPzgJpgaw4mWxWjwS6CWzO9U28bv9Uyh8MpWUkP77fPgCyzu8=</HostId></Error>

I fixed it installing ntp on ubuntu

$ sudo apt-get install ntp
$ sudo ntpdate pool.ntp.org

$ date
Thu Nov 26 00:55:50 IST 2015

$ python listB.py
bucket: andoria 2015-08-05 02:43:22+00:00
bucket: anythinglikenothing 2015-11-13 02:06:25+00:00
bucket: bikinibottom 2015-08-05 00:45:56+00:00
bucket: bs-blobs 2015-08-05 00:47:46+00:00
bucket: deflector 2015-08-05 00:44:26+00:00
bucket: ferenginar 2015-08-05 02:43:11+00:00
bucket: jamesmoriarty 2015-11-12 01:54:00+00:00
bucket: kline 2015-11-23 14:07:08+00:00
bucket: miniocloud 2015-08-25 19:07:42+00:00
bucket: mymagicfolder 2015-11-16 03:02:40+00:00
bucket: mynewmirror2 2015-11-16 02:56:46+00:00
bucket: newbucketidontknow 2015-11-17 04:37:21+00:00
bucket: nothinglikeanything 2015-09-07 08:14:38+00:00
bucket: peppadog 2015-11-20 00:54:53+00:00
bucket: prq 2015-11-19 19:40:15+00:00

**Comment by harshavardhana** [comment]
> RequestTimeTooSkewedThe difference between the request time and the current time is too large.20151124T221801Z2015-11-25T19:24:47Z90000070BE74CEACD1EBBET26jT/YGRZjNc5QYC47+S0U/5LzPzgJpgaw4mWxWjwS6CWzO9U28bv9Uyh8MpWUkP77fPgCyzu8=

The error is handled properly - ntp configuration is automatic these days for all operating systems.  I don't think we need to document this specifically for Linux. 

Once we have a full FAQ for server error responses then we can have this added there.  Not necessary for libraries.
