### ISSUE TITLE
docs: adding Minio as storage backend with Django 

### ISSUE THREAD

**Issue by koolhead17** [minio/minio-py#380]
We need to test https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html with Minio as backend & if everything works well, send a PR for same.

**Comment by harshavardhana** [comment]
ping @koolhead17

**Comment by yml** [comment]
It would be nice to have the regular django-storages approach also documented and to compare and contrast it with https://github.com/tomhoule/django-minio-storage that uses minio python client.

**Comment by koolhead17** [comment]
Thanks for contributing the plugin @yml Let me run it quickly on my end and add a recipe for same. 👍

**Comment by yml** [comment]
@koolhead17 I am looking forward to read your recipe with django-storages (boto).
It would be interesting to get insight from you about the advantages /disadvantages between using boto / minio-py in term of performance and reliability.

**Comment by donatello** [comment]
ping @koolhead17

**Comment by koolhead17** [comment]
Our community member wrote post on Django with Minio Backend, [https://medium.com/@sarit.r/how-to-setup-simple-django-s3-with-your-own-minio-server-28a47b89f56e#.ejpn5pdc6](https://medium.com/@sarit.r/how-to-setup-simple-django-s3-with-your-own-minio-server-28a47b89f56e#.ejpn5pdc6). 

![1-teyfxrbyy6ae2tpobabchg](https://cloud.githubusercontent.com/assets/41746/20891315/245f4108-bb30-11e6-9b40-ed37735ffd74.png)

We can close this.

**Comment by yml** [comment]
@koolhead17 I don't think so the article you reference add both dependencies : 

* django-minio-storage
* django_storages

But then only use `django-minio-storage` and do not show how to configure django_storages the aws S3 backend to use  a minio server.

I find the article rather confusing.

**Comment by koolhead17** [comment]
@yml @elcolie has used minio-django-storage in this post.  
When you mention performance/reliability can you help us in understanding better in matrix I should check for?

**Comment by yml** [comment]
In his post he uses django-minio-storages but add both `boto` and `django_storages` none of which are used or useful for django-minio-storages.

According to the author the status of [django-minio-storages](https://github.com/tomhoule/django-minio-storage)

>This library is still a work in progress and not suitable for production use yet.

So I would love to be able to point to a production ready alternative like django_storages (it uses boto under the cover).

**Comment by koolhead17** [comment]
Sure @yml

**Comment by GarimaKapoor** [comment]
@koolhead17 any updates on this, If needed take help from @donatello to fix this.

**Comment by koolhead17** [comment]
@GarimaKapoor I have not been able to find how to run alternative s3 compatible service as django_storage backend with s3 plugin in the official document.

**Comment by harshavardhana** [comment]
> @GarimaKapoor I have not been able to find how to run alternative s3 compatible service as django_storage backend with s3 plugin in the official document.

Closing this as a cookbook related bug not minio-py.
