### ISSUE TITLE
docs: Missing function signature from presigned_post_policy

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-py#384]
Missing
https://github.com/minio/minio-py/blob/master/API.md#presigned_post_policy

Has 
https://github.com/minio/minio-py/blob/master/API.md#presigned_put_objectbucket_name-object_name-expirestimedeltadays7

**Comment by harshavardhana** [comment]
Missing here as well - https://docs.minio.io/docs/python-client-api-reference#section-presigned_post_policy

**Comment by koolhead17** [comment]
@harshavardhana Please close this, it has been added.
