### ISSUE TITLE
remove_object change?

### ISSUE THREAD

**Issue by tomhoule** [minio/minio-py#391]
Hi,

I am working on my minio storage backend adapter for django (https://github.com/tomhoule/django-minio-storage), and I noticed that a test case I wrote a few weeks ago started failing with the latest version of minio-py.

Minio-py used to throw a `ResponseError` when trying to delete a non-existent object, and now it doesn't. I couldn't find information about this here so I'm reporting it in case it was not intentional. Feel free to close the issue if it was.

Sorry I can't be more precise with version numbers, I am just starting to put the project under CI.

**Comment by harshavardhana** [comment]
We havent changed anything recently. ResponseError on remove object is incorrect to start with it must be an older Minio server which was not s3 compliance. 

Under s3's behavior remove object on a non existent object does not throw any error it always returns 204 success no content

**Comment by tomhoule** [comment]
That's certainly it, I changed the minio version too. Thanks for the clarification!
