### ISSUE TITLE
Implement AWS China region support

### ISSUE THREAD

**Issue by koolhead17** [minio/minio-py#396]
Our Python Client library should also support  AWS China region s3.cn-north-1.amazonaws.com.cn

It has been implemented in minio-go, implementation reference:  https://github.com/minio/minio-go/commit/190ac7b4b7e7ba8a669553674b748bdcace6c59e

**Comment by mr-karan** [comment]
I'd like to get started by working on this issue. Can you assign me please? @koolhead17
