### ISSUE TITLE
Python3 incompability in signer.py

### ISSUE THREAD

**Issue by okrause** [minio/minio-py#418]
Just did a
pip3 install minio
and got
minio (2.0.2)

I see problems with put_object on Python3 (3.5.2).

Example code:

```

from minio import Minio
from minio.error import ResponseError

minioClient = Minio('127.0.0.1:9000',
                access_key='xxx',
                secret_key='xxx',
                secure=True)

try:
    minioClient.fput_object('mybucket', 'myobject.ogg', 'my-testfile')
except ResponseError as err:
    print(err)

```

I used the sample code from website, even though it has wrong endpoint and keys for my setup. Point is, it boils out earlier:

#> echo "test" > my-testfile
#> python3 test.py    
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    minioClient.fput_object('mybucket', 'myobject.ogg', 'my-testfile')
  File "/usr/local/lib/python3.5/site-packages/minio/api.py", line 564, in fput_object
    content_type=content_type)
  File "/usr/local/lib/python3.5/site-packages/minio/api.py", line 1436, in _do_put_object
    content_sha256=sha256_hex)
  File "/usr/local/lib/python3.5/site-packages/minio/api.py", line 1700, in _url_open
    region = self._get_bucket_region(bucket_name)
  File "/usr/local/lib/python3.5/site-packages/minio/api.py", line 1646, in _get_bucket_region
    region = self._get_bucket_location(bucket_name)
  File "/usr/local/lib/python3.5/site-packages/minio/api.py", line 1670, in _get_bucket_location
    self._secret_key, None)
  File "/usr/local/lib/python3.5/site-packages/minio/signer.py", line 199, in sign_v4
    headers['X-Amz-Content-Sha256'] = content_sha256.decode('ascii')
AttributeError: 'str' object has no attribute 'decode'

**Comment by harshavardhana** [comment]
We addressed a similar issue - https://github.com/minio/minio-py/issues/417 can you take a look if its not a setup issue?

**Comment by vadmeste** [comment]
> We addressed a similar issue - #417 can you take a look if its not a setup issue?

@harshavardhana, I have the same problem too in my machine. It disappears only when I disable secure flag. Will try to understand what's going on.

**Comment by okrause** [comment]
I had a look. There is no real solution specified except "used a different platform". I am also on OSX.

I played around with running the on Python2 and Python3 in comparision.
If I specify "Secure=False" while connecting, the code runs with Python2 and Python3 fine. I assume it avoids the problematic code path entirely.

If a set "Secure=True", it boils out with above error for Python3. Python2 yields an SSL error:
...
  File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 624, in urlopen
    raise SSLError(e)
urllib3.exceptions.SSLError: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:590)

My urllib3 for python2 is "urllib3 (1.19)"

This seems unrelated to the Python3 issue. Python3 fails before even trying to open a connection, If I understand correctly.

For my project I can live with Secure=False and are set. If you need me to test more things, I am happy to do so.

**Comment by okrause** [comment]
BTW: Updated the sample code to the code I used for above examples.

**Comment by vadmeste** [comment]
str.decode is no more supported in Python 3.x

**Comment by okrause** [comment]
Seems to be fixed. Python3 now runs into the same TLSV1 error as python2. Behaviour is consistent, problem seems unrelated.
Many thanks for the quick fix.

**Comment by harshavardhana** [comment]
> Seems to be fixed. Python3 now runs into the same TLSV1 error as python2. Behaviour is consistent, problem seems unrelated.
> Many thanks for the quick fix.

You are welcome @okrause - we will soon make a release.
