### ISSUE TITLE
How to supply directory?

### ISSUE THREAD

**Issue by elcolie** [minio/minio-py#421]
I use commit 
```
commit d7c4b1a7263d3d4e7ac6e45b0d5c2f9ad35f4b89
Author: koolhead17 <atul@minio.io>
Date:   Sun Nov 20 00:06:31 2016 +0530
```

And got this

```
Sarits-MacBook-Air-2:examples el$ ls
bucket_exists.py			get_partial_object.py			presigned_get_object.py			remove_object.py
copy_object.py				hello_world.txt				presigned_post_policy.py		set_bucket_notification.py
fget_object.py				list_buckets.py				presigned_put_object.py			set_bucket_policy.py
fput_object.py				list_incomplete_uploads.py		put_object.py				stat_object.py
get_bucket_notification.py		list_objects.py				remove_all_bucket_notification.py
get_bucket_policy.py			listen_notification.py			remove_bucket.py
get_object.py				make_bucket.py				remove_incomplete_upload.py
Sarits-MacBook-Air-2:examples el$ python fput_object.py
Traceback (most recent call last):
  File "fput_object.py", line 28, in <module>
    client.fput_object('kimbucket', 'hello_world.txt', '/Users/el/Code/uih-portal/minio-py/examples', 'text/plain')
  File "/Users/el/.pyenv/versions/3.5.1/lib/python3.5/site-packages/minio-2.0.2-py3.5.egg/minio/api.py", line 553, in fput_object
IsADirectoryError: [Errno 21] Is a directory: '/Users/el/Code/uih-portal/minio-py/examples'
Sarits-MacBook-Air-2:examples el$ pwd
/Users/el/Code/uih-portal/minio-py/examples
```

**My computer:**<br>
OSX 10.11.6
Python 3.5.1

**Questions:**<br>
How to supply an absolute and relative directory path correctly?

**Comment by harshavardhana** [comment]
> I use commit
> 
> commit d7c4b1a7263d3d4e7ac6e45b0d5c2f9ad35f4b89
> Author: koolhead17 <atul@minio.io>
> Date:   Sun Nov 20 00:06:31 2016 +0530
> And got this
> 
> Sarits-MacBook-Air-2:examples el$ ls
> bucket_exists.py			get_partial_object.py			presigned_get_object.py			remove_object.py
> copy_object.py				hello_world.txt				presigned_post_policy.py		set_bucket_notification.py
> fget_object.py				list_buckets.py				presigned_put_object.py			set_bucket_policy.py
> fput_object.py				list_incomplete_uploads.py		put_object.py				stat_object.py
> get_bucket_notification.py		list_objects.py				remove_all_bucket_notification.py
> get_bucket_policy.py			listen_notification.py			remove_bucket.py
> get_object.py				make_bucket.py				remove_incomplete_upload.py
> Sarits-MacBook-Air-2:examples el$ python fput_object.py
> Traceback (most recent call last):
>   File "fput_object.py", line 28, in <module>
>     client.fput_object('kimbucket', 'hello_world.txt', '/Users/el/Code/uih-portal/minio-py/examples', 'text/plain')
>   File "/Users/el/.pyenv/versions/3.5.1/lib/python3.5/site-packages/minio-2.0.2-py3.5.egg/minio/api.py", line 553, in fput_object
> IsADirectoryError: [Errno 21] Is a directory: '/Users/el/Code/uih-portal/minio-py/examples'
> Sarits-MacBook-Air-2:examples el$ pwd
> /Users/el/Code/uih-portal/minio-py/examples

Looks like a bug @elcolie - thanks for reporting will fix it.

**Comment by harshavardhana** [comment]
oh wait! fput_object cannot upload an entire directory, it can only upload one file at a time.

**Comment by harshavardhana** [comment]
Are you trying to upload all the contents in the directory?

**Comment by elcolie** [comment]
No. I just a single file
```
from minio import Minio
from minio.error import ResponseError

client = Minio('localhost:9000',
               access_key="KBP6WXGPS387090EZMG8",
               secret_key="DRjFXylyfMqn2zilAr33xORhaYz5r9e8r37XPz3A")

# Put an object 'my-objectname' with contents from 'my-filepath'
try:
    client.fput_object('kimbucket', 'hello_world.txt', '/Users/el/Code/uih-portal/minio-py/examples', 'text/plain')
except ResponseError as err:
    print(err)
```

**Comment by elcolie** [comment]
@harshavardhana Thank you for your light speed response. Any information you need please let me know I will provide everything

**Comment by harshavardhana** [comment]
> from minio import Minio
> from minio.error import ResponseError
> 
> client = Minio('localhost:9000',
>                access_key="KBP6WXGPS387090EZMG8",
>                secret_key="DRjFXylyfMqn2zilAr33xORhaYz5r9e8r37XPz3A")
> 
> # Put an object 'my-objectname' with contents from 'my-filepath'
> try:
>     client.fput_object('kimbucket', 'hello_world.txt', '/Users/el/Code/uih-portal/minio-py/examples', 'text/plain')
> except ResponseError as err:
>     print(err)

Then it should be like this 

```py
from minio import Minio
from minio.error import ResponseError

client = Minio('localhost:9000',
               access_key="KBP6WXGPS387090EZMG8",
               secret_key="DRjFXylyfMqn2zilAr33xORhaYz5r9e8r37XPz3A")

# Put an object 'my-objectname' with contents from 'my-filepath'
try:
    client.fput_object('kimbucket', 'hello_world.txt', '/etc/issue'', 'text/plain')
except ResponseError as err:
    print(err)
```

Now `/etc/issue` is a file here. - https://docs.minio.io/docs/python-client-api-reference#fput_object

**Comment by elcolie** [comment]
@harshavardhana Thank you very much

**Comment by AshaJagadish91** [comment]
@elcolie Is there any way to push the entire directory and its contents to MinIO client ?
