### ISSUE TITLE
Python3 - invalid signature, str vs bytes, in sha256, in put_object

### ISSUE THREAD

**Issue by rrozestw** [minio/minio-py#435]
In api.py, in function put_object there is a line:

`data_sha256_hex = encode_to_hex(get_sha256(current_data))`

which causes the upload code using put_object fail when running under python 3.5 with invalid signature error. Sha256 hex string contains "r'" and "'" (sic). It makes signatures computed and sent different.
The line shall be:

`data_sha256_hex = encode_to_hex(get_sha256(current_data)).decode('ascii')`

As I went with other solution to my problems, I don't have time to fully fix this issue (as it seems that in some places bytes are used; in some - strings - I'd has to be a more systematic fix to support python3 IMHO).

**Comment by harshavardhana** [comment]
This is fixed in master already. Thanks for reporting will be making a new release. @rrozestw

**Comment by harshavardhana** [comment]
ping // cc @donatello

**Comment by rrozestw** [comment]
I tested master today - there is no fix for that.

**Comment by donatello** [comment]
I ack. the bug. Able to reproduce. Working on a fix.

**Comment by rrozestw** [comment]
Thank you for you excellent support!
