### ISSUE TITLE
presigned_get_object should throw error for invalid keys?

### ISSUE THREAD

**Issue by ChillarAnand** [minio/minio-py#455]
```
mc.presigned_get_object('foo', 'invalid_key', expires=timedelta(days=1))
```

returns an url without throwing an error?

**Comment by harshavardhana** [comment]
> mc.presigned_get_object('foo', 'invalid_key', expires=timedelta(days=1))
> returns an url without throwing an error?

presigned URL is a client side operation with no server side request.  Unless the request is sent to server client cannot tell if the keys are invalid .

**Comment by ChillarAnand** [comment]
@harshavardhana  Thanks for clarification.
