### ISSUE TITLE
Connections to service are not being re-used - starting new HTTP connection for every request.

### ISSUE THREAD

**Issue by akheron** [minio/minio-py#458]
Hi!

Looking at the code, the minio client uses HTTP pooling. Still, each time I issue a `client.get_object()` or `client.put_object()`, I get the following log message: `Starting new HTTP connection (34): minio`, with the number increasing each time.

I use the same `minio.Minio` object for all requests, so the host and port are the same each time.

```
$ pip freeze | grep minio
minio==2.0.6
```

**Comment by donatello** [comment]
@akheron How do you get lines of log like "Starting new HTTP connection (34): minio"? I don't see any lines like that in the code. If you could provide a minimal example code it would be easier to understand what is going on.

**Comment by akheron** [comment]
What I'm trying to say that minio-py is starting new connections even though I think it should reuse existing connections.

The logging comes from urllib3: https://github.com/shazow/urllib3/blob/0cb7780a0613baa518be26df4b623ecb0ab3cbe5/urllib3/connectionpool.py#L206

Here's code to reproduce:

```python
#!/usr/bin/env python3

from io import BytesIO
import logging

from minio import Minio, ResponseError


logging.basicConfig(level=logging.INFO)

bucket_name = 'test'
client = Minio(
    'minio:9000',
    access_key='<hidden>',
    secret_key='<hidden>',
    secure=False,
)

try:
    client.make_bucket(bucket_name)
except ResponseError as exc:
    if exc.code == 'BucketAlreadyOwnedByYou':
        pass
    else:
        raise

for i in range(10):
    object_name = 'data_%d' % i
    data = chr(i).encode('ascii')

    client.put_object(
        bucket_name,
        object_name,
        BytesIO(data),
        len(data),
    )
```

Output to console:
```
$ python miniotest.py 
INFO:urllib3.connectionpool:Starting new HTTP connection (1): minio
INFO:urllib3.connectionpool:Starting new HTTP connection (2): minio
INFO:urllib3.connectionpool:Starting new HTTP connection (3): minio
INFO:urllib3.connectionpool:Starting new HTTP connection (4): minio
INFO:urllib3.connectionpool:Starting new HTTP connection (5): minio
INFO:urllib3.connectionpool:Starting new HTTP connection (6): minio
INFO:urllib3.connectionpool:Starting new HTTP connection (7): minio
INFO:urllib3.connectionpool:Starting new HTTP connection (8): minio
INFO:urllib3.connectionpool:Starting new HTTP connection (9): minio
INFO:urllib3.connectionpool:Starting new HTTP connection (10): minio
```

**Comment by donatello** [comment]
@akheron Thanks for the example - I am able to reproduce the problem.

I am updating the title to reflect that it is a bug.

The problem is that connections are not being released properly after usage. I am working on a fix.
