### ISSUE TITLE
tlsv1 alert internal error

### ISSUE THREAD

**Issue by tmbdev** [minio/minio-py#463]
Using today's version of minio-py

This is on Ubuntu 16.04.

```
>>> m = minio.Minio("charon.local:9000", "", "")
>>> list(m.list_objects_v2("imgclass"))
...
/usr/local/lib/python2.7/dist-packages/minio-2.0.6-py2.7.egg/minio/api.pyc in _get_bucket_location(self, bucket_name)
   1707                                       body=None,
   1708                                       headers=headers,
-> 1709                                       preload_content=False)
   1710 
   1711         if self._trace_output_stream:

/usr/local/lib/python2.7/dist-packages/urllib3/poolmanager.pyc in urlopen(self, method, url, redirect, **kw)
    163             response = conn.urlopen(method, url, **kw)
    164         else:
--> 165             response = conn.urlopen(method, u.request_uri, **kw)
    166 
    167         redirect_location = redirect and response.get_redirect_location()

/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.pyc in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, **response_kw)
    585             conn = conn and conn.close()
    586             release_conn = True
--> 587             raise SSLError(e)
    588 
    589         except SSLError:

SSLError: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:590)

```

**Comment by vadmeste** [comment]
@tmbdev, 

minio-py uses TLS by default to connect to the server, you need to explicity set secure flag to False
`> m = minio.Minio("charon.local:9000", "", "", secure=False)`

**Comment by tmbdev** [comment]
Thanks. It seems though as if there should be a better error message than
"internal error", since it's obviously not an internal error.

**Comment by harshavardhana** [comment]
> Thanks. It seems though as if there should be a better error message than
> "internal error", since it's obviously not an internal error.

The internal error is returned by Go's tls implementation not sure why such an error in the first place, but we have no control at the point when we see this error.  On the servers logs you would see "TLSv1 not configured" messages. 

We will explore if we can enhance and capture this error closing the bug here.
