### ISSUE TITLE
certifi version is OLD

### ISSUE THREAD

**Issue by uchuugaka** [minio/minio-py#470]
I was shocked this uninstalled my much much newer certifi with an older version.
Collecting certifi<=2015.4.28 (from minio)
  Downloading https://pypi.apple.com/packages/86/35/9758a67004a266047c779ae40a3d937869bfc6fc3422f6c606b8afbc9d23/certifi-2015.04.28-py2.py3-none-any.whl (373kB)
    100% |████████████████████████████████| 378kB 200kB/s 
Installing collected packages: certifi, minio
  Found existing installation: certifi 2016.9.26
    Uninstalling certifi-2016.9.26:
      Successfully uninstalled certifi-2016.9.26

You should really require >= not <= with a package dep that is intended to help provide CA trust info.

**Comment by harshavardhana** [comment]
Thanks @uchuugaka we will fix it.

**Comment by harshavardhana** [comment]
Also on a related NOTE certifi had a long standing bug with distribution folks over cert files - that is why we had to stick with urllib3 + certifi combination of this sort. 

Can you validate if they all work properly? @uchuugaka

**Comment by uchuugaka** [comment]
Ok, what is the recommended/preferred test of working properly?

**Comment by harshavardhana** [comment]
> Ok, what is the recommended/preferred test of working properly?

We need to do test for validity your PR is fine we will do the testing and validation. Thanks

**Comment by indradhanush** [comment]
I just cloned the repo and ran `python setup.py install` under a venv, and I noticed that the latest version of `certifi` got installed. 

Here's the output of `pip freeze | grep certifi`:
`certifi==2017.1.23`

My venv is on `python2.7` and I'm on OSX El Capitan, just in case.

**Comment by harshavardhana** [comment]
@uchuugaka has already fixed this issue in master.
