### ISSUE TITLE
api: return stat results from fget_object

### ISSUE THREAD

**Issue by hashbackup** [minio/minio-py#480]
HashBackup stores the etag from a put operation (usually md5) and verifies it on a get operation.  fget_object already does a stat_object before the get, so it would be easy to return from fget_object.  I can do a PR for that if acceptable.

**Comment by harshavardhana** [comment]
still not sure what you wrote above can you explain again @hashbackup ?

**Comment by hashbackup** [comment]
fget_object doesn't return a Python value - it just creates a file.  But it does a stat_object() to get the object etag, then uses the etag to construct partial filenames so it can resume an aborted download.

My original suggestion was to return the result of stat_object() from fget_object(), so that when you do an fget_object(), you also get the etag of the object "for free", without having to do another stat_object().

But looking again at the code, the only reason fget_object() does a stat_object() is to get the etag to use for a filename.  Rather than do an API call for that, it makes more sense to just hash the bucket name + object name strings and use that to construct a partial download filename.  It saves a network API call.

For programs that actually want the etag for verification, like HashBackup, they can do a stat_object() and get it.

It ends up being an efficiency thing: programs that don't want etag don't do a stat_object(), fget is faster because it avoids an API call, and programs that do want etag can do one stat_object() instead of 2.

**Comment by hashbackup** [comment]
After thinking about it more, I think the stat_object() is necessary.  A hash on the bucket + object name won't work because the object content could be changed after an interrupted fget_object.  In that case, you wouldn't want to resume using the previously saved (partial) content since it is now out of date.

So back to the original request: add 1 line, "return stat" at the end of fget_object

**Comment by harshavardhana** [comment]
> After thinking about it more, I think the stat_object() is necessary. A hash on the bucket + object name won't work because the object content could be changed after an interrupted fget_object. In that case, you wouldn't want to resume using the previously saved (partial) content since it is now out of date.

Correct that is the reason to stat inside to make sure we don't end up over appending on a previously different file.
