### ISSUE TITLE
doc: fput_object returns either etag or MultipartUploadResult

### ISSUE THREAD

**Issue by hashbackup** [minio/minio-py#481]
fput_object already returns either etag (smallish files) or MultipartUploadResult, but it isn't documented to return anything.  It would be useful to document the return value so that etag or mur.etag could be stored and verified for a future get operation.  Want a PR for that?

**Comment by harshavardhana** [comment]
> fput_object already returns either etag (smallish files) or MultipartUploadResult, but it isn't documented to return anything. It would be useful to document the return value so that etag or mur.etag could be stored and verified for a future get operation. Want a PR for that?

Sure thing please send a PR @hashbackup
