### ISSUE TITLE
api: add optional headers dict to put_object, fput_object, and copy_object

### ISSUE THREAD

**Issue by hashbackup** [minio/minio-py#482]
Many tools support S3 storage classes.  HashBackup does.  To do that, a header needs to be included in put and copy requests:
```
headers = {'x-amz-storage-class': 'STANDARD_IA'}
```
This can't really be done in the constructor when creating the client, because within a bucket, files can be in different storage classes.  When uploading small files less than 52K, Infrequent Access is actually more expensive than Standard storage because for IA, Amazon always charges for at least 128K.

I can take a look at doing this if it would be acceptable.

The change would be:
- add optional headers dict to put/fput/copy object apis, default is {}
- for small objects, pass the header dict to _do_put_object
-- in _do_put_object, add the Content-Length, Content-Type, and Content-Md5 headers to the header dict instead of creating a new dict
- for large objects, pass headers to _do_put_multipart_object; the headers go in the Initiate Multipart Upload request.  Looks a little messier, but same concept
- copy_object already has a header-like argument, "conditions".  It's just a class over a header dictionary.

Looks like 2 ways to do this:

1. add some new methods to CopyConditions, like set_storage_class and include a conditions arg in put_object and fput_object, like copy_object
-or-
2. add header arg to all 3.  This would be a little more flexible, because any header could be added, not just storage class.  And storage class is not exactly a "copy condition", even though very similar.

After looking at all the different header options for a put (http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html), I think it makes more sense to add the optional header argument to all 3 apis instead of using copyconditions.  Adding headers would enable:
- permissions
- ACLs
- storage class
- user-defined meta data
- cache controls
- tags
- server-side encryption

**Comment by hashbackup** [comment]
I did this and tested it for fput_object.  I suck at git, here's a diff if you want to take a look at what I was thinking:
```
*** api.py.~1~	2017-02-17 15:01:01.000000000 -0500
--- api.py	2017-02-23 00:47:09.000000000 -0500
***************
*** 546,548 ****
      def fput_object(self, bucket_name, object_name, file_path,
!                     content_type='application/octet-stream'):
          """
--- 546,549 ----
      def fput_object(self, bucket_name, object_name, file_path,
!                     content_type='application/octet-stream',
!                     headers={}):
          """
***************
*** 557,558 ****
--- 558,560 ----
          :param content_type: Content type of the object.
+         :param headers: Optional headers for the request.
          """
***************
*** 575,577 ****
                                         file_data.read(file_size),
!                                        content_type=content_type)
  
--- 577,580 ----
                                         file_data.read(file_size),
!                                        content_type=content_type,
!                                        headers=headers)
  
***************
*** 818,820 ****
      def put_object(self, bucket_name, object_name, data, length,
!                    content_type='application/octet-stream'):
          """
--- 822,825 ----
      def put_object(self, bucket_name, object_name, data, length,
!                    content_type='application/octet-stream',
!                    headers={}):
          """
***************
*** 839,840 ****
--- 844,846 ----
          :param content_type: mime type of object as a string.
+         :param headers: Optional headers for the request.
          :return: None
***************
*** 862,864 ****
                                     current_data,
!                                    content_type=content_type)
  
--- 868,871 ----
                                     current_data,
!                                    content_type=content_type,
!                                    headers=headers)
  
***************
*** 1516,1518 ****
      def _do_put_object(self, bucket_name, object_name, data,
!                        content_type='application/octet-stream'):
          """
--- 1523,1526 ----
      def _do_put_object(self, bucket_name, object_name, data,
!                        content_type='application/octet-stream',
!                        headers={}):
          """
***************
*** 1524,1525 ****
--- 1532,1534 ----
          :param content_type: Content type of put request.
+         :param headers: Optional headers for the put request.
          """
***************
*** 1533,1539 ****
  
!         headers = {
!             'Content-Length': len(data),
!             'Content-Type': content_type,
!             'Content-Md5': get_md5_base64digest(data)
!         }
  
--- 1542,1546 ----
  
!         headers['Content-Length'] = len(data)
!         headers['Content-Type'] = content_type
!         headers['Content-Md5'] = get_md5_base64digest(data)
```
I tested this by adding a file to S3 using the header described above to set the storage class to Infrequent Access and verified that the file ended up on S3 correctly.

One gotcha I ran into is that I used an all lower-case header, causing a KeyError in generate_canonical_request on this line:
```
        value = headers[header.title()]
```
This is sort of a good thing, because it traps headers that have different case, but headers are often documented in all lowercase so it will probably confuse users to throw this error.

I changed the code like this:
```
*** signer.py.~1~	2017-02-17 15:01:01.000000000 -0500
--- signer.py	2017-02-23 00:33:24.000000000 -0500
***************
*** 255,265 ****
      header_lines = []
!     for header in headers:
          header = header.lower().strip()
          signed_headers.append(header)
-     signed_headers = sorted(signed_headers)
- 
-     for header in signed_headers:
-         value = headers[header.title()]
          value = str(value).strip()
!         header_lines.append(header + ':' + str(value))
  
--- 255,263 ----
      header_lines = []
!     for header, value in headers.items():
          header = header.lower().strip()
          signed_headers.append(header)
          value = str(value).strip()
!         header_lines.append(header + ':' + value)
!     signed_headers.sort()
!     header_lines.sort()
```
This simpler code works with any header case, although it does not check for duplicate headers and probably should: I think a duplicate header in different cases will generate an incorrect signature and S3 will throw an error.  This code does 2 sorts instead of 1, but each is 2.5x faster because they sort inplace.  I'd suggest using header_set = set(), set it in the loop, and raise an error on duplicate headers.

I'm working on my git foo today, haha...

**Comment by harshavardhana** [comment]
> permissions
> ACLs
> storage class
> user-defined meta data
> cache controls
> tags
> server-side encryption

The reason to avoid these is the fundamental reason for this library to exist, otherwise we would simply use AWS SDKs ourselves.  These headers have no real meaning outside of AWS S3 - Minio sdks are meant to be an abstracted version not requiring the intelligence of knowing what kind of object storage server you are using - all it needs to be have is S3 API compatible so that when you point your application to any other server than AWS S3 it should work and shouldn't require you to change your application or to go through some change. 

Anything outside of this if you require some specific server side features like tags, SSE - you should stick to AWS SDKs which are better suited to support these features. It is not necessary for minio SDKs to mimic exactly what AWS SDKs.

**Comment by hashbackup** [comment]
Okay.  I want to replace boto because it's so huge (116K lines) and all I really need is the S3 support, not EC2 and all that.  But it needs to work for anything S3 compatible.  I don't use any of these features except storage class, and don't mind using my own hacked version of minio for it.  I much appreciate the work on it, to allow me to move away from boto

**Comment by harshavardhana** [comment]
Since we implemented PutObjectWithMetadata already in minio-go library - minio-py is going to follow this and implement this feature nonetheless. 

https://github.com/minio/minio-py/pull/486 - reopening the request.
