### ISSUE TITLE
ImportError: cannot import name 'Minio'

### ISSUE THREAD

**Issue by firestarter87** [minio/minio-py#495]
Just trying to run standard script from the docs http://docs.minio.io/docs/python-client-api-reference

Tried with Python 2.7.13 & 3.6.0 + installed minio via Pip

**Comment by harshavardhana** [comment]
> Just trying to run standard script from the docs http://docs.minio.io/docs/python-client-api-reference
> 
> Tried with Python 2.7.13 & 3.6.0 + installed minio via Pip

are you sure your PYTHONPATH is correct? can you paste the sample program you are using?

**Comment by harshavardhana** [comment]
```
$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from minio import Minio
>>> from minio.error import ResponseError
>>> 
>>> minioClient = Minio('play.minio.io:9000',
...                   access_key='Q3AM3UQ867SPQQA43P2F',
...                   secret_key='zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG',
...                   secure=True)
>>> 
```

```
$ python3
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from minio import Minio
>>> from minio.error import ResponseError
>>> 
>>> minioClient = Minio('play.minio.io:9000',
...                   access_key='Q3AM3UQ867SPQQA43P2F',
...                   secret_key='zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG',
...                   secure=True)
>>> 
```

**Comment by firestarter87** [comment]
Sorry to waste your time, I named my file minio.py wich caused the error. I'm only a hobbyist...

**Comment by harshavardhana** [comment]
> Sorry to waste your time, I named my file minio.py wich caused the error. I'm only a hobbyist...

Feel free to close this bug.. Thanks
