### ISSUE TITLE
read ~/.mc/config.json consistently in all libraries

### ISSUE THREAD

**Issue by tmbdev** [minio/minio-py#502]
I'm building tools and libraries that allow people to use Minio/S3 storage with deep learning frameworks. This means that users are going to switch freely between writing Python code, Go code, and command line tools. This involves a lot of end user programming and scripting.

It would be nice if these different tools could share a common authentication infrastructure. In particular, it would be convenient if minio-py had an option of taking its keys and path shortcuts from ~/.mc/config.json

Of course, I can write a wrapper library, but having the option of having consistent paths and key management between the different Minio libraries and command line tools would seem to be a nice feature to have.

**Comment by harshavardhana** [comment]
Setting this to priority high before we triage this properly, need to discuss this further internally.

**Comment by deekoder** [comment]
@harshavardhana will update details that unblock this bug to move fwd.

**Comment by harshavardhana** [comment]
This needs to be fixed in similar manner as the credentials PR being implemented on minio-go https://github.com/minio/minio-go/pull/646

Required credential providers to support for 

- AWS Envs
- AWS Credentials file
- AWS IAM Roles
- Minio Envs
- Minio Client config file

**Comment by vadmeste** [comment]
ETA: 20 Apr

**Comment by ebozduman** [comment]
Pinging @vadmeste for status?

**Comment by kannappanr** [comment]
Closing this issue as this is not a high priority. We will be looking to add this feature in the future.
