### ISSUE TITLE
Parallel upload through fput_object API

### ISSUE THREAD

**Issue by amitojSNPS** [minio/minio-py#503]
Uploading a 7.5 gig file through mc client takes 30 seconds, while minio-py API fput_object takes about 3 minutes for the same task.
There should be an option for parallel upload in the API as well which can match the mc client performance.

**Comment by deekoder** [comment]
@amitojSNPS  we will discuss this and let you know further details.

**Comment by deekoder** [comment]
We have decided to implement this. It's already done in minio-go.
