### ISSUE TITLE
module' object has no attribute 'Retry on urllib3 at Centos with Python 2.7.10

### ISSUE THREAD

**Issue by NikolasDaroit** [minio/minio-py#509]
I discovered Minio yesterday and it's amazing. Tried on dev, using a Mac, with Python 2.7.10, and Minio 2.2.1.

On Mac, following the quick-start example:

```
>>> # Initialize minio
Client with an endpoint and access/secret keys.
... minioClient = Minio('play.minio.io:9000',
...                     access_key='Q3AM3UQ867SPQQA43P2F',
...                     secret_key='zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG',
...                     secure=True)
>>> minioClient
<minio.api.Minio object at 0x1061a2a50>

```

At AWS Centos:

```
>>> minioClient = Minio('play.minio.io:9000',
...                     access_key='Q3AM3UQ867SPQQA43P2F',
...                     secret_key='zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG',
...                     secure=True)
Traceback (most recent call last):
  File "<console>", line 4, in <module>
  File "build/bdist.linux-x86_64/egg/minio/api.py", line 152, in __init__
    retries=urllib3.Retry(
AttributeError: 'module' object has no attribute 'Retry'
```

I couldn't install it by pip at Centos.

But this way it works

```
git clone https://github.com/minio/minio-py
cd minio-py
python setup.py install

```

**Comment by MrRedAmber** [comment]
I haven't found the full solution but I believe this problem is encountered because of a problem with the way `urllib3` is getting imported into `minio-py`

**Comment by harshavardhana** [comment]
How so. ?

**Comment by hackintoshrao** [comment]
Tried with Centos container, works fine for me, 

Here are the steps, 

- `docker run -it centos`
- `# curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"`
- `# python get-pip.py && pip install Minio`
- `# python`
- `>>> from minio import Minio`
- `>>>minioClient = Minio('play.minio.io:9000',access_key='Q3AM3UQ867SPQQA43P2F',secret_key='zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG',secure=True)`
- `>>> minioClient` 
- `>>> minio.api.Minio object at 0x7f4c998a7c10`

**Comment by krisis** [comment]
@NikolasDaroit initializing `minioClient` works as expected for me [too](https://github.com/minio/minio-py/issues/509#issuecomment-302569249), when tried on a centos Docker instance, with minio-2.2.1. By the way, minio-2.2.2 is available. Could you check if the issue is still present for you?

**Comment by NikolasDaroit** [comment]
@krisis tried it again but the issue still happen.

**Comment by wandenberg** [comment]
Try to execute `sudo pip3 install --upgrade urllib3`
I was having the same issue in a Ubuntu 14.04

**Comment by krisis** [comment]
@NikolasDaroit did you try @wandenberg's suggestion?

**Comment by NikolasDaroit** [comment]
Despite the fact that I'm using python 2.7 with pip 2.7, upgrading urllib3 solved the problem. Thanks @wandenberg @krisis  and all the others for the time and effort.
