### ISSUE TITLE
Make possible to return partial URL

### ISSUE THREAD

**Issue by fazpu** [minio/minio-py#516]
Hi,

Problem:
* minio is deployed in docker swarm cluster under service name **minio_service**
* When connecting to minio service via the minio.Minio client, I would input the endpoint parameter as **minio_service**
* Now, when I call e.g. the presigned_get_object method, the reutrned url is e.g. **http://minio_service/example_bucket/example_file...**

Of course, such URL does not exist and the request would fail.

Required state:
* there should be option to return only the partial address, e.g. example_bucket/example_file...
* I propose minio.Minio method should have additional argument **partial_url** with default value False. If set to True, only partial URLs would be returned.

Why I am interested:
* I am currently working on large PR for django-minio-storage (https://github.com/tomhoule/django-minio-storage/pull/14)
* It is necessary to combine django-defined base static/media URL with the file path in minio

**Comment by harshavardhana** [comment]
Presigned only works if you have the full URL, partial URLs will not work and will be consistent with S3 API. 

Why do you need this in core Minio API? - if you need to do such a translation you need to keep a separate indirection outside of Minio API.  I cannot see why this would be needed in core functionality.

**Comment by fazpu** [comment]
Hi, the problem can be overcomed outside of this repository. 

But here is my philosophical take on it:

* When you use the AWS S3 service, you can send the data and always know the URL format that will return.
* However, with the minio, the situation is different. It is meant to be deployed somewhere on a server. The services that might communicate with the minio might not use URL at all, they can just reference the docker service.
* But, in order to make the content in minio accessable to the outside world, you need to alter the URL returned from minio.
* Hence, minio behaves differently from the S3 and thus it would be nice to easily overcome this by built-in functionality.

Anyway, good job with the minio-py ;-)

**Comment by harshavardhana** [comment]
> When you use the AWS S3 service, you can send the data and always know the URL format that will return.
> However, with the minio, the situation is different. It is meant to be deployed somewhere on a server. The services that might communicate with the minio might not use URL at all, they can just reference the docker service.
> But, in order to make the content in minio accessable to the outside world, you need to alter the URL returned from minio.
> Hence, minio behaves differently from the S3 and thus it would be nice to easily overcome this by built-in functionality.

Minio is no different than S3 . Say if you upload a file on https://play.minio.io:9000 where a bucket name is `testbucket` and object name is `object.txt` then your URL to access the file directly is 

https://play.minio.io:9000/testbucket/object.txt

So URL construction or kowing the deployment is all deployment specific which the application is already aware. minio-py cannot do anything special in this regard other than what your application would do on its own. 

So i think this doesn't lie in the scope of minio-py.

**Comment by hackintoshrao** [comment]
> So i think this doesn't lie in the scope of minio-py. 

Can this be closed ?

**Comment by harshavardhana** [comment]
This can be closed @deekoder
