### ISSUE TITLE
listen_bucket_notification() failed with IOError

### ISSUE THREAD

**Issue by rbrik** [minio/minio-py#523]
I tried to listen for changes on my bucket. The call `client.listen_bucket_notification('mybucket')` results in the following exception:

>Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\minio\api.py", line 516, in listen_bucket_notification
    query=query, preload_content=False)
  File "C:\Python27\lib\site-packages\minio\api.py", line 1861, in _url_open
    query=query)
  File "C:\Python27\lib\site-packages\minio\helpers.py", line 224, in get_target_url
    str(value)).replace('/', '%2F')
  File "C:\Python27\lib\nturl2path.py", line 61, in pathname2url
    raise IOError, error
IOError: Bad path: s3:ObjectCreated:*

I use:
- Windows 7
- python 2.7.13 
- minio python library 2.2.2
- minio server
Version: 2017-05-05T01:14:51Z
Release-Tag: RELEASE.2017-05-05T01-14-51Z
Commit-ID: 40985cc4e3eec06b7ea82dc34c8d907fd2e7aa12

**Comment by vadmeste** [comment]
@rbrik, it looks more like a mistake when passing arguments somewhere, could you paste a sample code which is causing this ?

**Comment by rbrik** [comment]
Just passed the bucket name `client.listen_bucket_notification('mybucket')` without prefix, suffix or events. 

> from minio import Minio
client = Minio('192.168.17.128:9000',
               access_key='9VUIHT3R5GY9U41R7CMH',
               secret_key='LNsXs8A+izcz4LTt6Oh3cpB6UxADylCZ1Gj31H0g',
               secure=False)
client.make_bucket('mybucket', location='us-east-1')
events = client.listen_bucket_notification('mybucket')
for event in events:
    print event

The call end up in `nturl2path.pathname2url(p)` where the event string "s3:ObjectCreated:*" is splitted with ":" into three fragments. The method seems not to be able to handle this.

>  comp = p.split(':')
    if len(comp) != 2 or len(comp[0]) > 1:
        error = 'Bad path: ' + p
        raise IOError, error

**Comment by vadmeste** [comment]
I can confirm that I have the same problem but only under Windows. I'll investigate further.

**Comment by vadmeste** [comment]
Using urllib.quote instead of url.pathname2url was enough to fix the problem. Also tests are passing.

**Comment by rbrik** [comment]
Also tried using `urllib.quote()` instead. Seems to work for me too. Do you add that to the next release?

**Comment by harshavardhana** [comment]
> Also tried using urllib.quote() instead. Seems to work for me too. Do you add that to the next release?

We will add it to the next release.. @vadmeste can you send a fix?
