### ISSUE TITLE
Download as zip

### ISSUE THREAD

**Issue by CGenie** [minio/minio-py#524]
Hello,

The UI offers possibility of selecting multiple objects and downloading them as zip file.
It would be very nice to have this functionality in the Python client as well.

**Comment by harshavardhana** [comment]
> The UI offers possibility of selecting multiple objects and downloading them as zip file.
> It would be very nice to have this functionality in the Python client as well.

minio-py is a client SDK implementing S3 APIs, this is out of scope for minio-py and will not be implemented. 

Minio browser on the other hand provides richer functionality for this and has a server side component doing this. So it cannot be implemented on the client side.

**Comment by deekoder** [comment]
Closing this issue. Please let me know if you think the sdks ought to do this still and we can discuss further.

**Comment by sugare** [comment]
How can I get to download as zip url?

**Comment by Alamin02** [comment]
This will be a very nice to have feature for client sdk.

**Comment by harshavardhana** [comment]
> This will be a very nice to have feature for client sdk.

This is an application logic, not meant for client SDKs
