### ISSUE TITLE
mc presigned urls don't work if port is specified

### ISSUE THREAD

**Issue by abipaul** [minio/minio-py#527]
"/home/minio/mc share download --expire=30m mymini/bucket/filename"

generates wrong presigned url if you use port number while configuring mymini

minio config should work with(out) port number specified in endpoint

**Comment by harshavardhana** [comment]
Thanks for the bug report @abipaul

**Comment by vadmeste** [comment]
Taking this.

**Comment by vadmeste** [comment]
The problem is that, curl and browser strips :80 or :443 when sending Host header. So I think the best solution is to make clients proactively strip these ports before generating presigned urls.
