### ISSUE TITLE
Unicode object name on python 2.7 causes exception

### ISSUE THREAD

**Issue by Yurmusp** [minio/minio-py#529]
Trying to make django-minio-storage work with Python 2.7
In current active fork I have pull request here
https://github.com/py-pa/django-minio-storage/pull/15

In standard test with Unicode object name I get exception.
After some digging (and temporary code changes) for finding 
what is original exception I found this call stack:
```
__________ UploadTests.test_upload_and_get_back_file_with_funky_name ___________
tests/test_app/tests/upload_tests.py:75: in test_upload_and_get_back_file_with_funky_name
    self.media_storage.save("áčďěščřžýŽŇůúť.txt", ContentFile(b"12345"))
.tox/py27/lib/python2.7/site-packages/django/core/files/storage.py:53: in save
    name = self.get_available_name(name, max_length=max_length)
.tox/py27/lib/python2.7/site-packages/django/core/files/storage.py:77: in get_available_name
    while self.exists(name) or (max_length and len(name) > max_length):
minio_storage/storage.py:108: in exists
    self.bucket_name, self._sanitize_path(name))
.tox/py27/lib/python2.7/site-packages/minio/api.py:1045: in stat_object
    object_name=object_name)
.tox/py27/lib/python2.7/site-packages/minio/api.py:1861: in _url_open
    query=query)
.tox/py27/lib/python2.7/site-packages/minio/helpers.py:213: in get_target_url
    object_name = encode_object_name(object_name)
.tox/py27/lib/python2.7/site-packages/minio/helpers.py:481: in encode_object_name
    return urlencode(object_name)
/opt/python/2.7.12/lib/python2.7/urllib.py:61: in pathname2url
    return quote(pathname)
/opt/python/2.7.12/lib/python2.7/urllib.py:1299: in quote
    return ''.join(map(quoter, s))
E   KeyError: u'\xe1'
```

If you can see. We use urllib on python 2.7 and it is no unicode-ish.
We need to do things via urllib3 to support unicode.
Can you guys fix it?
My failing build result is here if that can be helpful:
https://travis-ci.org/py-pa/django-minio-storage/jobs/239789339

**Comment by harshavardhana** [comment]
As a work-around you should just use python3 which has native unicode support. Getting it to work on python2.7 can be a challenge with lots of hacks @Yurmusp ?

**Comment by Yurmusp** [comment]
I can not.

**Comment by harshavardhana** [comment]
> I can not.

why not?

**Comment by Yurmusp** [comment]
You know what. I digged around. 
I think I do not really need full unicode support. 
What I need  is proper UTF-8 support in base string of python 2.7 if passed to your API.
So that 
if your API obtains only UTF-8 base strings, it then properly works and
returns only UTF-8 base strings.
Currently I have issue with this.

In partiular,  your API returns Unicode string sometimes, not base string in utf-8.
For example,

client.list_objects(name, "")
returns objects with unicode string.

So that further iteration on objects to to remove them causes exception with unicode name.
55             for obj in client.list_objects(name, ""):
56                 client.remove_object(name, obj.object_name)

Call stack below:
==================================== ERRORS ====================================
 ERROR at teardown of RetrieveTestsWithPublicBucket.test_public_url_generation _
tests/test_app/tests/utils.py:61: in tearDown
    obliterate_bucket(self.bucket_name("tests-media"))
tests/test_app/tests/utils.py:56: in obliterate_bucket
    client.remove_object(name, obj.object_name)
.tox/py27/lib/python2.7/site-packages/minio/api.py:1086: in remove_object
    object_name=object_name)
.tox/py27/lib/python2.7/site-packages/minio/api.py:1861: in _url_open
    query=query)
.tox/py27/lib/python2.7/site-packages/minio/helpers.py:213: in get_target_url
    object_name = encode_object_name(object_name)
.tox/py27/lib/python2.7/site-packages/minio/helpers.py:481: in encode_object_name
    return urlencode(object_name)
/opt/python/2.7.12/lib/python2.7/urllib.py:61: in pathname2url
    return quote(pathname)
/opt/python/2.7.12/lib/python2.7/urllib.py:1299: in quote
    return ''.join(map(quoter, s))
E   KeyError: u'\xdc'

Also visible here:
https://travis-ci.org/py-pa/django-minio-storage/jobs/239833388#L287

Full test source is here:
https://github.com/py-pa/django-minio-storage/blob/master/tests/test_app/tests/utils.py#L52

**Comment by harshavardhana** [comment]
Well we have a fix for it in the master and also the PR we just referenced #530

**Comment by Yurmusp** [comment]
You mean for unicode? That would be cool.

**Comment by Yurmusp** [comment]
and to what I read and see it is the most proper solution. So that your interface receives and returns unicode strings and work with them right.

**Comment by harshavardhana** [comment]
Yes @Yurmusp we already have initial work done by @vadmeste in a separate PR. The new PR simplifies the usage.  We will make a release soon which should help you address the unicode problems for python 2.7 as well.

**Comment by Yurmusp** [comment]
Let me know if you have PR that I can try before release. So that I could move on my end with something working while you complete release. Let me know if this is possible. Thanks.

**Comment by harshavardhana** [comment]
> Let me know if you have PR that I can try before release. So that I could move on my end with something working while you complete release. Let me know if this is possible. Thanks.

Yes @Yurmusp you would have to use latest master with this PR #530

**Comment by Yurmusp** [comment]
I left some review feedback on your PR. Please, take a look.
