### ISSUE TITLE
AttributeError: 'PartMetadata' object has no attribute 'md5hasher'

### ISSUE THREAD

**Issue by Yurmusp** [minio/minio-py#543]
In latest 2.2.3 I get this error:

File "/home/vagrant/.virtualenvs/web/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 93, in save
    self.name = self.storage.save(name, content, max_length=self.field.max_length)
  File "/home/vagrant/.virtualenvs/web/local/lib/python2.7/site-packages/django/core/files/storage.py", line 63, in save
    name = self._save(name, content)
  File "/home/vagrant/.virtualenvs/web/local/lib/python2.7/site-packages/minio_storage/storage.py", line 102, in _save
    content_type)
  File "/home/vagrant/.virtualenvs/web/local/lib/python2.7/site-packages/minio/api.py", line 897, in put_object
    data, length, metadata=metadata)
  File "/home/vagrant/.virtualenvs/web/local/lib/python2.7/site-packages/minio/api.py", line 1665, in _stream_put_object
    md5_hex = part_metadata.md5hasher.hexdigest()
AttributeError: 'PartMetadata' object has no attribute 'md5hasher'

**Comment by harshavardhana** [comment]
Fixed in master branch already @Yurmusp - we need to make a new release..

**Comment by Yurmusp** [comment]
I see. Thanks.

**Comment by Yurmusp** [comment]
When it will come? in few weeks?
This bug looks like a blocker.

**Comment by harshavardhana** [comment]
> I see. Thanks.

You can try `pip install git+git://github.com/minio/minio.git@master`

**Comment by harshavardhana** [comment]
> This bug looks like a blocker.

Should be this week. Waiting on one more PR #542

**Comment by Yurmusp** [comment]
Sounds good. Thank you.

**Comment by Yurmusp** [comment]
That command fails for me as:
Collecting git+git://github.com/minio/minio.git@master
  Cloning git://github.com/minio/minio.git (to master) to /tmp/pip-j2wl4O-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-j2wl4O-build/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-j2wl4O-build/

**Comment by Yurmusp** [comment]
(web)vagrant@localdev:~/.prism/log$ ls /tmp/pip-j2wl4O-build
appveyor.yml  cmd              Dockerfile.aarch64  Dockerfile.release.aarch64  hound.yml  MAINTAINERS.md  minio.spec                     pip-egg-info  README_ZH.md
browser       CONTRIBUTING.md  Dockerfile.armhf    Dockerfile.release.armhf    LICENSE    main_test.go    NOTICE                         pkg           vendor
buildscripts  Dockerfile       Dockerfile.release  docs                        main.go    Makefile        pip-delete-this-directory.txt  README.md

**Comment by Yurmusp** [comment]
My pip is 9.0.1 . and I'm on py27

**Comment by harshavardhana** [comment]
> (web)vagrant@localdev:~/.prism/log$ ls /tmp/pip-j2wl4O-build
> appveyor.yml cmd Dockerfile.aarch64 Dockerfile.release.aarch64 hound.yml MAINTAINERS.md minio.spec pip-egg-info README_ZH.md
> browser CONTRIBUTING.md Dockerfile.armhf Dockerfile.release.armhf LICENSE main_test.go NOTICE pkg vendor
> buildscripts Dockerfile Dockerfile.release docs main.go Makefile pip-delete-this-directory.txt README.md

Sorry there was a typo ``pip install git+git://github.com/minio/minio-py.git@master`` it should be `minio-py`.

**Comment by Yurmusp** [comment]
This works. Thank you.

**Comment by Yurmusp** [comment]
Do you know if there are way to add similar reference to setup.py somehow instead of version number?

**Comment by harshavardhana** [comment]
> Do you know if there are way to add similar reference to setup.py somehow instead of version number?

You have to use something called as `dependency_links` http://python-packaging.readthedocs.io/en/latest/dependencies.html#packages-not-on-pypi

**Comment by harshavardhana** [comment]
Fixed by release 2.2.4
