### ISSUE TITLE
Provide exception on wrong metadata naming

### ISSUE THREAD

**Issue by moenka** [minio/minio-py#552]
I was fiddling with the python api for minio/s3 and wanted to add custom metadata to my files.
I came to the point where my files got uploaded correctly and my metadata seemed to be added as there was no error from python. When I wanted to see the stats of the uploaded files I always got empty metadata. This confused me in a really intriguing way and I spend ~3 days finding the cause of this problem until today when I stumbled over the fact that metadata on Amazon S3 needs to be named `x-amz-meta-*`.

To help other poeple tp not make the same mistake and waste time I'd like to see the python module to throw an exception when the metadata keys don't adhere to the Amazon naming convention as this is what I would expect (this clearly is an error and this needs to be pointed out by python).

If you plan to support non Amazon conform metadata please add a possibility to the module to configure an own regexp for metadata naming.

Also imho this should be pointed out in the documentation (at least with a link to http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html#UserMetadata) for users like me that never before worked with Amazon S3 but are interested in minio itself. The implementation of the custom regexp with the Amazon naming as predefined value would also suffice as documentation.

**Comment by harshavardhana** [comment]
Thanks for opening the bug . Makes complete sense we are going to do a signature change in the API which would make it cleaner.

**Comment by deekoder** [comment]
We are doing this in minio-go to start with. Will update minio-py in future https://github.com/minio/minio-go/issues/747

**Comment by deekoder** [comment]
We have not had the cycles to fix this issue. Will close it and reopen it when we are able to. This is also a great item for community contribution, if anyone wants to take it up.
