### ISSUE TITLE
Assistance using put_object with NumPy arrays

### ISSUE THREAD

**Issue by csheaff** [minio/minio-py#554]
Hello, I'm trying to figure out the best way to store numpy arrays into a minio server by converting to a form suitable for the put_object command. What sort of conversion is best before inserting as an argument into the method? My best guess is to pickle the object, but when I try to use put_object with this, i get a an error related to the object having no read() method. Apparently it isn't of some binary class referred to as io.RawIOBase. Could someone give me a clue?

**Comment by poornas** [comment]
You could try this
```
import os

from minio import Minio
from minio.error import ResponseError
import numpy as np
client = Minio("play.minio.io:9000",
                access_key="Q3AM3UQ867SPQQA43P2F",
                secret_key=   "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG")
from tempfile import NamedTemporaryFile
try:
   # save numpy array to named temporary file
    a = np.array([1, 2, 3, 4])
    tempfile = NamedTemporaryFile()
    np.save(tempfile, a)
    tempfile.seek(0)

    if not client.bucket_exists('mybucket123'):
        client.make_bucket('mybucket123')

    # upload the temp file to server
    client.fput_object('mybucket123','my-objectname',tempfile.name)

    # download object and load it into a numpy array 
    client.fget_object('mybucket123','my-objectname','gettempfile')
    g = np.load('gettempfile')
    if np.array_equal(g,a):
        print("numpy array the same")
    else:
        print("numpy array not saved correctly.")
```

**Comment by csheaff** [comment]
Thanks, but I was hoping to get around having to use fput. My arrays are very large and take a long time to write to disk.

**Comment by poornas** [comment]
@csheaff , how big are your arrays?

you could instead convert to bytes for using put_object
```
    a = np.array([1, 2, 3, 4])
    buf =a.tobytes()
    client.put_object('mybucket123','my-objectname2',io.BytesIO(buf),len(buf))
    recv = client.get_object('mybucket123','my-objectname2')
    b = np.frombuffer(recv.read(),dtype='int')
```

**Comment by csheaff** [comment]
from what module can I find recv?

**Comment by harshavardhana** [comment]
> from what module can I find recv? my array shape is something like (50, 1000, 1000)

recv is not a module @csheaff it is just a response object returned by `client.get_object()`  this response object is io.Base compatible implements `read()` method. 

All you have to do is put_object with bytes of numpy array wrapped around in io.BytesIO() and you are good to upload.

**Comment by csheaff** [comment]
woops, sorry i was blind there. seems to work well! thanks much. Can you recommend a way to interface to a minio server from MATLAB? I would basically like to do the same thing with MATLAB arrays. Would it be best to call a python script and run that API?

**Comment by harshavardhana** [comment]
> woops, sorry i was blind there. seems to work well! thanks much. Can you recommend a way to interface to a minio server from MATLAB? I would basically like to do the same thing with MATLAB arrays. Would it be best to call a python script and run that API?

Yes matlab arrays will work the same was numpy arrays. @csheaff
