### ISSUE TITLE
get_policy call fails with TypeError

### ISSUE THREAD

**Issue by poornas** [minio/minio-py#558]
When functional tests are run against azure gateway, get_policy call fails with a TypeError. The client sdk does not guard against server running None for statements while appending policy statements in policy.py

Traceback (most recent call last):
File "/usr/bin/minio-py-functional", line 333, in <module>
main()
File "/usr/bin/minio-py-functional", line 277, in main
policy_name = client.get_bucket_policy(bucket_name)
File "/usr/local/lib/python3.5/dist-packages/minio/api.py", line 368, in get_bucket_policy
policy._append_statements(statements, policy_dict.get('Statement', []))
File "/usr/local/lib/python3.5/dist-packages/minio/policy.py", line 429, in _append_statements
for s in append_statements:
TypeError: 'NoneType' object is not iterable

**Comment by donatello** [comment]
The Azure gateway response is not correct here - if there are no policies set, the get policy call should return an error - both s3 and minio server return a 404 error:

```
<Error><Code>NoSuchBucketPolicy</Code><Message>The bucket policy does not exist</Message><Key></Key><BucketName></BucketName><Resource>/bucket/</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
```

and in s3:

```
<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>NoSuchBucketPolicy</Code><Message>The bucket policy does not exist</Message><BucketName>vadmeste</BucketName><RequestId>B93FA31B56838F07</RequestId><HostId>4vGdcClynoPiT8MKAKoN5NsBq2RHMhVOr1m5SoU9lvOTWeG1hmNL5o6Y++Vu6sV/</HostId></Error>
```

So this is a bug in minio gateway, and not in the SDK.

**Comment by poornas** [comment]
@krishnasrinivas, can you comment on this?

**Comment by harshavardhana** [comment]
Agree with @donatello assessment here if there are no policies server should return 404 in compliance with S3 behavior. Looks this bug exists with GCS gateway as well..

**Comment by deekoder** [comment]
server side  should return appropriate error message.
