### ISSUE TITLE
Mint tests fails on ListObjectsV2 when server is running in gateway mode.

### ISSUE THREAD

**Issue by poornas** [minio/minio-py#569]
ListObjectsV2 fails on all 3 gateways when running Mint.

```
Stack trace for azure:
Traceback (most recent call last):
  File "/usr/bin/minio-py-functional", line 333, in <module>
    main()
  File "/usr/bin/minio-py-functional", line 257, in main
    object_name).get_exception()
minio.error.InternalError: InternalError: message: We encountered an internal error. Please try again.

Stack trace for s3:
Traceback (most recent call last):
  File "/usr/bin/minio-py-functional", line 333, in <module>
    main()
  File "/usr/bin/minio-py-functional", line 257, in main
    object_name).get_exception()
minio.error.InternalError: InternalError: message: We encountered an internal error. Please try again.

Stack trace for gcs:
Traceback (most recent call last):
  File "/usr/bin/minio-py-functional", line 333, in <module>
    main()
  File "/usr/bin/minio-py-functional", line 277, in main
    policy_name = client.get_bucket_policy(bucket_name)
  File "/usr/local/lib/python3.5/dist-packages/minio/api.py", line 368, in get_bucket_policy
    policy._append_statements(statements, policy_dict.get('Statement', []))
  File "/usr/local/lib/python3.5/dist-packages/minio/policy.py", line 429, in _append_statements
    for s in append_statements:
TypeError: 'NoneType' object is not iterable

```

**Comment by harshavardhana** [comment]
> Stack trace for gcs:
> Traceback (most recent call last):
>   File "/usr/bin/minio-py-functional", line 333, in <module>
>     main()
>   File "/usr/bin/minio-py-functional", line 277, in main
>     policy_name = client.get_bucket_policy(bucket_name)
>   File "/usr/local/lib/python3.5/dist-packages/minio/api.py", line 368, in get_bucket_policy
>     policy._append_statements(statements, policy_dict.get('Statement', []))
>   File "/usr/local/lib/python3.5/dist-packages/minio/policy.py", line 429, in _append_statements
>     for s in append_statements:
> TypeError: 'NoneType' object is not iterable

This is perhaps already fixed by #559

**Comment by harshavardhana** [comment]
> Stack trace for azure:
> Traceback (most recent call last):
>   File "/usr/bin/minio-py-functional", line 333, in <module>
>     main()
>   File "/usr/bin/minio-py-functional", line 257, in main
>     object_name).get_exception()
> minio.error.InternalError: InternalError: message: We encountered an internal error. Please try again.
> 
> Stack trace for s3:
> Traceback (most recent call last):
>   File "/usr/bin/minio-py-functional", line 333, in <module>
>     main()
>   File "/usr/bin/minio-py-functional", line 257, in main
>     object_name).get_exception()
> minio.error.InternalError: InternalError: message: We encountered an internal error. Please try again.

Perhaps a server side issue. Do we know the test here which failed? @poornas

**Comment by poornas** [comment]
ListObjectsV2 seems to have failed while setting up the test. Ran it again - Content-Length header is missing. 

The gateway logs are:
```
ERRO[0261] Unable to save an object /cb4f13c3-e94f-480b-afce-59e317acb2a6/2b9dec2e-ad5b-419c-a709-5ce66485b7aa  cause=storage: service returned error: StatusCode=411, ErrorCode=MissingContentLengthHeader, ErrorMessage=Content-Length HTTP header is missing.
RequestId:85340ff3-001e-0011-5a45-249461000000
Time:2017-09-02T23:43:00.1305482Z, RequestId=85340ff3-001e-0011-5a45-249461000000, QueryParameterName=, QueryParameterValue= source=[gateway-handlers.go:314:gatewayAPIHandlers.PutObjectHandler()] stack=gateway-azure.go:417:(*azureObjects).PutObject gateway-handlers.go:306:gatewayAPIHandlers.PutObjectHandler gateway-router.go:88:(gatewayAPIHandlers).PutObjectHandler-fm
ERRO[1539] Unable to create object part.                 cause=Put https://minioazure1.blob.core.windows.net/420b72d7-c1ce-4e80-821a-8348bd37545e/e1d7fb0c-573e-4867-a65a-58f0bb1244f4-large?blockid=MDAwMTMuNWYzNjNlMGU1OGE5NWYwNmNiZTliYmM2NjJjNWRmYjY%!D(MISSING)&comp=block: dial tcp: i/o timeout source=[object-handlers.go:870:objectAPIHandlers.PutObjectPartHandler()] stack=gateway-azure.go:556:(*azureObjects).PutObjectPart object-handlers.go:867:objectAPIHandlers.PutObjectPartHandler api-router.go:46:(objectAPIHandlers).PutObjectPartHandler-fm
```

**Comment by poornas** [comment]
This issue seems to be fixed - not reproducible with latest minio master. minio-py tests run successfully with gateway endpoints.

**Comment by harshavardhana** [comment]
Feel free to close the bug. You opened the issue @poornas
