### ISSUE TITLE
minio-py fails erroneously with minio.error.InvalidEndpointError: InvalidEndpointError: message: Amazon S3 hostname should be s3.amazonaws.com

### ISSUE THREAD

**Issue by davidthewatson** [minio/minio-py#570]
I have minio installed to our kubernetes cluster on amazon. The hostname ends in amazonaws.com but is not S3. When I run the minio-py with the correct credentials, the code fails here:

https://github.com/minio/minio-py/blob/master/minio/helpers.py#L276-L279

The check for s3 ignores the fact that I may have an external IP exposed through amazon that is not s3, but rather minio - in this case hosted on our kubernetes cluster.

Do you need a pull request?

**Comment by harshavardhana** [comment]
Yes feel free to send a PR. @davidthewatson we shouldn't do endswith instead do an exact match.

**Comment by davidthewatson** [comment]
I'm not sure I follow.

How does an exact match help here?

To me, it seems that this code is trying to ensure a canonical form to s3
URLs that doesn't actually exist in the real world. Keep in mind, I can
call my k8s minio endpoint s3, because there are a number of unique
substrings in that amazonaws.com URL.

Can you clarify? The most obvious solution to me was to delete the s3 check.

**Comment by harshavardhana** [comment]
Not necessarily it requires a different refactor to make the region handling work properly.

It should just be that there should be a regex `s3-*.amazonaws.com`

**Comment by harshavardhana** [comment]
Getting back on this issue @davidthewatson are you still planning to send a PR?
