### ISSUE TITLE
allow cloudfront url to create a presigned url

### ISSUE THREAD

**Issue by subho007** [minio/minio-py#573]
Is it possible to add this as an option `ALIAS_NAME` or something similar ?

**Comment by harshavardhana** [comment]
For AWS specific functionalities such as CCloudFront it is better to stick with `boto` library. 

Why do you think its helpful for `minio-py` ? Isn't it not possible for you to do this outside of minio-py ?

**Comment by ebozduman** [comment]
@subho007 : 
Closing this issue as "Won't fix"...
Please let us know if you disagree or have a compelling reason for us to implement it, but we think this is not something we need to address as part of Minio-py SDK as it belongs to AWS and `boto` library.
