### ISSUE TITLE
Python3: multible policies wont work

### ISSUE THREAD

**Issue by the-infinity** [minio/minio-py#585]
Because policy.py uses iteritems() in line 381 and 402, adding more then one policy fails if you don't use python2.

**Comment by vadmeste** [comment]
@the-infinity, thanks for reporting this. dict.iteritems() is replaced by dict.items() in this PR https://github.com/minio/minio-py/pull/586.

However, I am not sure what you did to trigger this bug, can you check this on your side or paste a simple code to test.

**Comment by the-infinity** [comment]
I tried to add more then one policy for the same bucket, but different directories.
