### ISSUE TITLE
Support for HTTP Proxies

### ISSUE THREAD

**Issue by dadicool** [minio/minio-py#588]
While minio is usually deployed on-premise and the connection between client and server doesn't need to traverse HTTP Proxies, in large infrastructure setups or distributed ones between VPCs, the need for traversing proxies is real.

This could be achieved simply by using ProxyManager instead of PoolManager.

PR coming :)

**Comment by harshavardhana** [comment]
You can change it yourself too as a work-around for now. 

```
  minio_client._http = urllib3.ProxyManager(
            timeout=urllib3.Timeout.DEFAULT_TIMEOUT,
            cert_reqs='CERT_REQUIRED',
            retries=urllib3.Retry(
                total=5,
                backoff_factor=0.2,
                status_forcelist=[500, 502, 503, 504]
            )
        )
```
