### ISSUE TITLE
Accept SSL cert as an argument for minio-py functional tests 

### ISSUE THREAD

**Issue by ebozduman** [minio/minio-py#593]
minio-py SDK test ran against the latest minio release, `minio.RELEASE.2017-11-15T22-20-02Z`, fails with the following error message:
```
HTTPSConnectionPool(host='192.168.1.22', port=9000): Max retries exceeded with url: /minio-py-test-c2e57adb-90cb-484e-b007-cceaf0da8876/ (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)'),))
```
We need to support self-signed certificates.

**Comment by leah4kosh** [comment]
any updates on when you'll support self-signed certificates?

**Comment by harshavardhana** [comment]
> any updates on when you'll support self-signed certificates?

you can create your own http client based on urllib3, this bug is open for an entirely different reason @leah4kosh 

You are allowed to provide a custom httpClient as shown below following this doc you should be able to use self signed certs with minio-py https://urllib3.readthedocs.io/en/latest/advanced-usage.html#custom-ssl-certificates-and-client-certificates

```py
import urllib3

httpClient = urllib3.PoolManager(
                timeout=urllib3.Timeout.DEFAULT_TIMEOUT,
                        cert_reqs='CERT_REQUIRED',
                        ca_certs='/path/to/my/self-signed/bundle.crt',
                        retries=urllib3.Retry(
                            total=5,
                            backoff_factor=0.2,
                            status_forcelist=[500, 502, 503, 504]
                        )
            )

minioClient = Minio('localhost:9000',
                    access_key='ACCESS_KEY',
                    secret_key='SECRET_KEY',
                    secure=True,
                    http_client=httpClient)
```

**Comment by deekoder** [comment]
Do we still need this @ebozduman  and @harshavardhana.

**Comment by harshavardhana** [comment]
> Do we still need this @ebozduman and @harshavardhana.

The reason was largely to be able to do SSL for mint tests with a flag, but this is not necessary for now.
