### ISSUE TITLE
python minio client may cause thread exhaust

### ISSUE THREAD

**Issue by kiss187** [minio/minio-py#595]
- python: 3.5
- minio-client: 2.2.6
- minio-server info: 
VERSION 2017-10-27T18:59:02Z
MEMORY
Used: 7.5 MB | Allocated: 50 GB | Used-Heap: 7.5 MB | Allocated-Heap: 29 MB
PLATFORM
Host: 6cbd0abfd258 | OS: linux | Arch: amd64
RUNTIME
Version: go1.9.2 | CPUs: 12

I use python script to create img and save record into db, and use minio python client upload to minio server.
```python
minio_client = Minio('192.168.1.144:9000',
                     access_key='',
                     secret_key='',
                     secure=False)


def upload(file_path, key_name):
  try:
    minio_client.fput_object('intellid',
                             key_name,
                             file_path,
                             content_type='image/png',
                             metadata={'Content-Disposition': 'attachment'})
  except ResponseError as err:
    logging.exception(file_path)
    logging.exception('upload failed!')


def main():
  main_id = threading.get_ident()
  db = default_session()
  gens = db.query(Generation).filter(Generation.status == None).limit(5).all()

  processed = 0
  while gens and len(gens) != 0:
    for gen in gens:
      compositions = copy.deepcopy(gen.composition['compositions'])
      for composition in compositions:
        composition['img_path'] = path.join(data_home, path.basename(
          db.query(Img).filter(Img.guid == composition[
            'guid']).first().oss))

      out_img = compose(gen.composition['width'], gen.composition['height'],
                        gen.composition['linkType'], compositions)

      key_name = 'ori/' + str(uuid.uuid4()) + '.png'
      key_name_thumb = 'thumb/' + str(uuid.uuid4()) + '.png'

      tmp = path.join(prod_out, key_name)
      thumb_tmp = path.join(prod_out, key_name_thumb)

      out_img.save(tmp)
      res = post_proc(tmp, thumb_tmp, 300)

      guid = uuid.uuid1().int >> 65
      while True:
        img = db.query(Img).filter(Img.guid == guid).first()
        if not img:
          break
        guid = uuid.uuid1().int >> 65
      minio_oss = minio_oss_prefix + key_name
      minio_oss_thumb = minio_oss_prefix + key_name_thumb

      new_img = Img(guid=guid, oss=minio_oss, thumb_oss=minio_oss_thumb,
                    file_type='PNG', img_type='AI', attr=res)
      print("before upload acitve_thread {}.".format(threading.active_count()))
      upload(tmp, key_name)
      upload(thumb_tmp, key_name_thumb)
      print("after upload acitve_thread {}.".format(threading.active_count()))
      db.add(new_img)
      db.commit()
      gen.guid = guid
      gen.status = 0
      processed += 1
      db.commit()
      print("processed {}.".format(processed))
    # end for
    gens = db.query(Generation).filter(Generation.status == None).limit(
      5).all()
  # end while


if __name__ == '__main__':
  main()

```
> partial log print:
before upload acitve_thread 319.
after upload acitve_thread 322.
processed 107.
before upload acitve_thread 322.
after upload acitve_thread 325.
processed 108.
before upload acitve_thread 325.
after upload acitve_thread 328.
processed 109.

**problem:** the minio client will create `ThreadPool` with 3 thread (code location: minio/api.py line 1511). And these thread (minio.thread_pool.Worker) will nerver exit. After every iteration in loop, the active thread number will increase 3. Finally the total threads in current process will exceed the linux limit(2048 in `ulimit -a`).

I'm a novice in minio. appreciation for any help. thanks.

**Comment by harshavardhana** [comment]
Thanks for letting us know @kiss187 , we will take a look. Looks like the current implementation we are not garbage collecting the lingering threads properly.

**Comment by kiss187** [comment]
@harshavardhana , thank you!

**Comment by harshavardhana** [comment]
I wrote a sample program @kiss187 and i have been able to upload 11MiB object around a 1000 times with final result 
```py
from minio import Minio
from minio.error import ResponseError
import threading

server_endpoint = '10.0.0.13:9000'
access_key = 'USWUXHGYZQYFYFFIT3RE'
secret_key = 'MOJRH0mkL1IPauahWITSVvyDrQbEEIwljvmxdq03'
secure = False

client = Minio(server_endpoint, access_key, secret_key, secure=secure)

for i in xrange(1000):
    print("before upload active_thread {}.".format(threading.active_count()))
    client.fput_object('testbucket', 'my-objectname', 'bigfile')
    print(threading.enumerate())
    print("after upload active_thread {}.".format(threading.active_count()))
```

```
after upload active_thread 3001.
```

The code that is written in threadpool does cleanly indicate when the task is done, but from what it looks like threading just seems to keep reporting them as active.  The only reason i can think of is its waiting on garbage collection these threads are in limbo to be gc'ed at some point in time. 

So question for you in the sample code that you shared

- did you actually observe a thread exhaustion and failure? 
- what is your current `ulimit -n` value?  my current `ulimit -n` is 1024? 
- what is 2048 in your case? can you paste the entire `ulimit -a` output?

**Comment by kiss187** [comment]
@harshavardhana sorry about I forgot to print the exception log in last comment. For saving time, I use the images generated last time.

my test code:
```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from minio import Minio
from minio.error import ResponseError
import threading
import sys
import logging

minio_client = Minio('192.168.1.144:9000',
                     access_key='...',
                     secret_key='...',
                     secure=False)


def upload(file_path, key_name):
  try:
    minio_client.fput_object('test',
                             key_name,
                             file_path,
                             content_type='image/png',
                             metadata={'Content-Disposition': 'attachment'})
  except ResponseError as err:
    logging.exception(file_path)
    logging.exception('upload failed!')


def main():
  record_file = sys.argv[1]
  with open(record_file, 'r', encoding='utf-8') as f:
    for i, line in enumerate(f):
      record = line.split()
      file_path, key_name = record[0], record[1]
      upload(file_path, key_name)
      print("loop-{}, acitve_thread - {}".format(i+1, threading.active_count()))


if __name__ == '__main__':
  main()
```
there are different 4000+ images record in file.

exception log:
> ....
loop-1374, acitve_thread - 2029
loop-1375, acitve_thread - 2032
loop-1376, acitve_thread - 2032
loop-1377, acitve_thread - 2035
loop-1378, acitve_thread - 2035
loop-1379, acitve_thread - 2038
loop-1380, acitve_thread - 2038
Traceback (most recent call last):
  File "minio_local_upload.py", line 38, in <module>
    main()
  File "minio_local_upload.py", line 33, in main
    upload(file_path, key_name)
  File "minio_local_upload.py", line 21, in upload
    metadata={'Content-Disposition': 'attachment'})
  File "/home/zju/project/mihui_design_gen/.venv/lib/python3.5/site-packages/minio/api.py", line 567, in fput_object
    content_type, metadata)
  File "/home/zju/project/mihui_design_gen/.venv/lib/python3.5/site-packages/minio/api.py", line 773, in put_object
    data, length, metadata=metadata)
  File "/home/zju/project/mihui_design_gen/.venv/lib/python3.5/site-packages/minio/api.py", line 1511, in _stream_put_object
    pool = ThreadPool(_PARALLEL_UPLOADERS)
  File "/home/zju/project/mihui_design_gen/.venv/lib/python3.5/site-packages/minio/thread_pool.py", line 65, in __init__
    Worker(self.tasks_queue, self.results_queue, self.exceptions_queue)
  File "/home/zju/project/mihui_design_gen/.venv/lib/python3.5/site-packages/minio/thread_pool.py", line 41, in __init__
    self.start()
  File "/usr/lib/python3.5/threading.py", line 844, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

- `ulimit -n` output:
> 65536

- `ulimit -a` output:
> core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 63554
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65536
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 2048
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

**Comment by U039b** [comment]
Hi!
When do you think this bug will be fixed?

**Comment by nnehdi** [comment]
I found where is the problem. It's how Minio.thread_pool.ThreadPool class manages the threads.
I wrote a test code and saw that threads were not released.
```

from minio.thread_pool import ThreadPool


def _task_callback(input):
    print(input)


def _run_threads():
    pool = ThreadPool(3)
    parameters_list = ["a", "b", "c"]
    pool.parallel_run(_task_callback, parameters_list)


for i in range(1, 170):
    _run_threads()
    print("loop-{}, active_thread - {}".format(i, threading.active_count()))
```

Here is the results 
```

loop-14, active_thread - 43
a
b
c
loop-15, active_thread - 46
a
b
c
loop-16, active_thread - 49
a
b
c
loop-17, active_thread - 52
a
b
c
loop-18, active_thread - 55
a
b
c
loop-19, active_thread - 58
a
b
c
loop-20, active_thread - 61
a
b
c
loop-21, active_thread - 64
a
b
c
```

We are still working on the problem.

**Comment by nnehdi** [comment]
The problem solved. As I guessed the problem was ThreadPool class. This class starts some Workers with infinite loop (while True) in _ _ init _ _ method and these workers never stop. 

I changed the thread_pool.py file as follow and that worked for me. I mentioned the changes that I have made with #changed comment.
```

import sys
from threading import Thread
from .compat import queue

class Worker(Thread):
    """ Thread executing tasks from a given tasks queue """
    def __init__(self, tasks_queue, results_queue, exceptions_queue):
        Thread.__init__(self)
        self.tasks_queue = tasks_queue
        self.results_queue = results_queue
        self.exceptions_queue = exceptions_queue
        # changed
        # self.daemon = True
        self.daemon = False
        self.start()

    def run(self):
        fast_quit = False

        # changed
        # while True:
        while not self.tasks_queue.empty():
            func, args, kargs = self.tasks_queue.get()
            if not fast_quit:
                try:
                    result = func(*args, **kargs)
                    self.results_queue.put(result)
                except Exception as e:
                    self.exceptions_queue.put(e)
                    fast_quit = True
            # Mark this task as done, whether an exception happened or not
            self.tasks_queue.task_done()


class ThreadPool:
    """ Pool of threads consuming tasks from a queue """
    def __init__(self, num_threads):
        self.results_queue = queue()
        self.exceptions_queue = queue()
        self.tasks_queue = queue(num_threads)
        self.num_threads = num_threads

        # changed
        # for _ in range(num_threads):
        #     Worker(self.tasks_queue, self.results_queue, self.exceptions_queue)

    def add_task(self, func, *args, **kargs):
        """ Add a task to the queue """
        self.tasks_queue.put((func, args, kargs))

    def parallel_run(self, func, args_list):
        """ Add a list of tasks to the queue """
        for args in args_list:
            self.add_task(func, args)

        # changed
        for _ in range(self.num_threads):
            Worker(self.tasks_queue, self.results_queue, self.exceptions_queue)

        # Wait for completion of all the tasks in the queue
        self.tasks_queue.join()
        # Check if one of the thread raised an exception, if yes
        # raise it here in the function
        if not self.exceptions_queue.empty():
            raise self.exceptions_queue.get()


    def result(self):
        """ Return the result of all called tasks """
        return self.results_queue

```

**Comment by harshavardhana** [comment]
This is excellent debugging. Thanks for doing that feel free to send PR @nnehdi

**Comment by nnehdi** [comment]
Thank You, I will send it to you soon.
