### ISSUE TITLE
I want see a progress bar

### ISSUE THREAD

**Issue by rkdls** [minio/minio-py#601]
when i put some file using minio-py 
```sh
fput_object()
```
it is good for some small file but large file, it is take a long time while uploading.

so user's doesn't know it is in progress or not.

so could you add option like ```progress_use``` ?

thanks.

**Comment by deekoder** [comment]
We have not had the cycles to fix this issue. Will close it and reopen it when we are able to. This is also a great item for community contribution, if anyone wants to take it up.

**Comment by kannappanr** [comment]
Sent a PR for this issue, so reopening this issue.

**Comment by kannappanr** [comment]
Do not have the cycle right now to fix this issue. Closing it now.

**Comment by rkdls** [comment]
Can I open this issue? I want to PR about it

**Comment by harshavardhana** [comment]
> Can I open this issue? I want to PR about it

Sure

**Comment by rkdls** [comment]
Can you explain what an ETA is?
I'm working on it. It can be displayed every 5MB.

**Comment by kannappanr** [comment]
@rkdls Thanks for working on the PR. I was just checking to see when you will have the PR ready for review.

**Comment by kannappanr** [comment]
Closing this PR as https://github.com/minio/minio-py/pull/723 has been merged.
