### ISSUE TITLE
When setting minio using https and port 80 python sdk will connect to port 443

### ISSUE THREAD

**Issue by aotsukiqx** [minio/minio-py#610]
I set up my minio server by docker run -p 80:9000 and configured using https protocol.
By using python sdk to connect minio server with specified http_client, I got connection error.
After investigation, I found minio/helpers line 224 striped port from endpoint_url：
    # Strip 80/443 ports since curl & browsers do not
    # send them in Host header.
    if parsed_url.port == 80 or parsed_url.port == 443:
        host = parsed_url.hostname
Since using http://your.url.com:80 will get same behavior by browser, suggests remove this strip from code to let user can using this two port in abnormal way.

Thanks

**Comment by harshavardhana** [comment]
This bug should be on minio-py project instead
