### ISSUE TITLE
put_object with invalid object name and body 1MiB throws wrong exception

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-py#616]
{"message": "HTTPConnectionPool(host='147.75.68.3', port=9001): Max retries exceeded with url: /minio-py-test-f8744398-525d-4d68-a7cb-eb68c4fd3edd//a/b/c/1018c782-7705-48a6-ba73-64d103434d21 (Caused by ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))", "duration": 3772, "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py\", line 600, in urlopen\n    chunked=chunked)\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py\", line 356, in _make_request\n    conn.request(method, url, **httplib_request_kw)\n  File \"/usr/lib/python3.5/http/client.py\", line 1106, in request\n    self._send_request(method, url, body, headers)\n  File \"/usr/lib/python3.5/http/client.py\", line 1151, in _send_request\n    self.endheaders(body)\n  File \"/usr/lib/python3.5/http/client.py\", line 1102, in endheaders\n    self._send_output(message_body)\n  File \"/usr/lib/python3.5/http/client.py\", line 936, in _send_output\n    self.send(message_body)\n  File \"/usr/lib/python3.5/http/client.py\", line 905, in send\n    self.sock.sendall(datablock)\nConnectionResetError: [Errno 104] Connection reset by peer\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 629, in test_negative_put_object_with_path_segment\n    MB_1)\n  File \"/usr/local/lib/python3.5/dist-packages/minio/api.py\", line 782, in put_object\n    metadata=metadata)\n  File \"/usr/local/lib/python3.5/dist-packages/minio/api.py\", line 1459, in _do_put_object\n    content_sha256=sha256_hex\n  File \"/usr/local/lib/python3.5/dist-packages/minio/api.py\", line 1767, in _url_open\n    preload_content=preload_content)\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/poolmanager.py\", line 321, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py\", line 678, in urlopen\n    **response_kw)\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py\", line 678, in urlopen\n    **response_kw)\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py\", line 678, in urlopen\n    **response_kw)\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py\", line 649, in urlopen\n    _stacktrace=sys.exc_info()[2])\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py\", line 388, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='147.75.68.3', port=9001): Max retries exceeded with url: /minio-py-test-f8744398-525d-4d68-a7cb-eb68c4fd3edd//a/b/c/1018c782-7705-48a6-ba73-64d103434d21 (Caused by ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1676, in main\n    test_negative_put_object_with_path_segment(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 633, in test_negative_put_object_with_path_segment\n    raise Exception(err)\nException: HTTPConnectionPool(host='147.75.68.3', port=9001): Max retries exceeded with url: /minio-py-test-f8744398-525d-4d68-a7cb-eb68c4fd3edd//a/b/c/1018c782-7705-48a6-ba73-64d103434d21 (Caused by ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))\n", "function": "put_object(bucket_name, object_name, data, length, content_type, metadata)", "name": "minio-py:test_negative_put_object_with_path_segment", "status": "FAIL", "args": {"data": "LimitedRandomReader(1MiB)", "length": 1048576, "bucket_name": "minio-py-test-f8744398-525d-4d68-a7cb-eb68c4fd3edd", "object_name": "/a/b/c/1018c782-7705-48a6-ba73-64d103434d21"}}

**Comment by kannappanr** [comment]
#615 has been merged, hence closing this issue
