### ISSUE TITLE
Multi-part SSE Example?

### ISSUE THREAD

**Issue by pwdonald** [minio/minio-py#622]
Hello! I'm considering Minio for a project but can't seem to find very detailed documentation on the current state of encryption at rest. It seems that there is some functionality as outlined in the examples but when I try to PUT a file larger than 5mb--resulting in multiple parts--I get the following error:

`minio.error.APINotImplemented: APINotImplemented: message: A header you provided implies functionality that is not implemented.`

I assume this isn't a limitation of the Python client specifically but since I was unable to find documentation stating the intended behavior for multi-part PUT operations I decided I would ask.

So my question, is this the intended behavior? If so, is there a milestone for adding multi-part SSE?

**Comment by harshavardhana** [comment]
> Hello! I'm considering Minio for a project but can't seem to find very detailed documentation on the current state of encryption at rest? It seems that there is some functionality as outlined in the examples but when I try to PUT a file larger than 5mb--resulting in multiple parts--I get the following error:
> 
> minio.error.APINotImplemented: APINotImplemented: message: A header you provided implies functionality that is not implemented.
> 
> I assume this isn't a limitation of the Python client specifically but since I was unable to find documentation stating the intended behavior for multi-part PUT operations I decided I would ask.

Minio server doesn't support SSE for multipart APIs yet.

**Comment by pwdonald** [comment]
Thanks for the quick reply, just for clarity--it is indeed a server limitation and not specific to the Python implementation?

**Comment by harshavardhana** [comment]
> Thanks for the quick reply, just for clarity--it is indeed a server limitation and not specific to the Python implementation?

Yes it is a server limitation @pwdonald
