### ISSUE TITLE
list_objects() and list_objects_v2() methods fail when executed on GCS

### ISSUE THREAD

**Issue by zupan** [minio/minio-py#631]
I have a two object storage environments setup. One with the Minio Server and the other one on GCS.
Both environments have the exact same folder structure and when migrating from Minio server to GCS the list object functionality started returning errors.

```
Traceback (most recent call last):
  File "/home/zupan/bin/miniconda/lib/python3.6/site-packages/minio/parsers.py", line 108, in get_child_text
    return self.element.find('s3:{}'.format(name), _S3_NS).text
AttributeError: 'NoneType' object has no attribute 'text'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "minio-test.py", line 37, in <module>
    list_files("models/")
  File "minio-test.py", line 33, in list_files
    return Remote().list_files(file_dir)
  File "minio-test.py", line 25, in list_files
    for current_object in objects:
  File "/home/zupan/bin/miniconda/lib/python3.6/site-packages/minio/api.py", line 857, in list_objects
    bucket_name=bucket_name)
  File "/home/zupan/bin/miniconda/lib/python3.6/site-packages/minio/parsers.py", line 234, in parse_list_objects
    is_truncated = root.get_child_text('IsTruncated').lower() == 'true'
  File "/home/zupan/bin/miniconda/lib/python3.6/site-packages/minio/parsers.py", line 112, in get_child_text
    'Message: {}').format(self.root_name, name, error.message)
AttributeError: 'AttributeError' object has no attribute 'message'
```

minio-py version is 3.0.3

After debugging the minio-py source code, I traced the root of the problem to the difference in the returned *ListBucketResult* XML element. I found out that only for the `list_objects` and `list_objects_v2` methods GCS backend returns `<ListBucketResult xmlns=\'http://doc.s3.amazonaws.com/2006-03-01\'>` whereas all other methods that I've tested, return `<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">` as expected.

This is the line where it fails due to the expected _S3_NS being different than the returned URL by the GCS. https://github.com/minio/minio-py/blob/master/minio/parsers.py#L104

**Comment by harshavardhana** [comment]
This problem is GCS is not fully S3 compatible if you use `minio gateway gcs` you should be able to get around this problem.

Fixing minio-py would make it less stricter.

**Comment by kannappanr** [comment]
Please use gcs using gateway as mentioned in the previous comment. closing this issue as not an issue. please feel free to file an issue if you have further questions.
