### ISSUE TITLE
Build shouldn't require test dependencies

### ISSUE THREAD

**Issue by yurivict** [minio/minio-py#643]
Currently, build fails:
> distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('nose>=1.0')

'test' should be a separate target.

**Comment by deekoder** [comment]
@abraarsyed absolutely. @vadmeste  can you give @abraarsyed some help in doing the fix for this issue?

**Comment by vadmeste** [comment]
Sorry for the delay @abraarsyed, you can ping me any time in https://slack.minio.io

**Comment by abraarsyed** [comment]
Thanks @deekoder :D 

@vadmeste Not a problem, will do that right away :)

**Comment by abraarsyed** [comment]
I was going through the files and I am just thinking out loud. 

Do I have to remove the occurence of `tests_requires`  from setup.py file since that is the file for building from source. Am I thinking in the right direction and is this what is expected to do?
