### ISSUE TITLE
Chinese version of API doc needs to be updated to reflect set/getBucketPolicy fix (PR#639)

### ISSUE THREAD

**Issue by ebozduman** [minio/minio-py#645]
For issue #635 (PR#639), we have to modify the Chinese version of the API document, `../docs/zh_CN/API.md`
All the references to Policy.READ_ONLY，Policy.WRITE_ONLY，Policy.READ_WRITE, Policy.NONE, and set_bucket_policy and get_bucket_policy signatures (removal of `prefix`) need to be modified/replaced.

**Comment by deekoder** [comment]
I have pinged @dingjs  for this.
