### ISSUE TITLE
List objects recurisvely with same prefix gives only first item

### ISSUE THREAD

**Issue by phm3** [minio/minio-py#648]
When the structure looks like it:
├── 123456
│   └── data
│       ├── 1
│       ├── 2
│       └── 3

Listing object by `list_objects` with prefix `123456/data/` and `recursive=True` returns only 1

VERSION:   2018-02-09T22:40:05Z

**Comment by phm3** [comment]
`Python 2.7.6 (default, Nov 23 2017, 15:49:48)`
When I use boto3, everything works as expected, so I am conflicted, what went wrong. I try to replicate it.

**Comment by poornas** [comment]
Thanks @phm3, I used python 2.7.5 for the above test. Can you send the code snippet you used if you are able to replicate the issue?

**Comment by poornas** [comment]
@phm3, were you able to replicate it again?

**Comment by phm3** [comment]
I ran the test only for fetching the objects and now i have it correct, so I suspect there was something else in the code which interfered with the method

    python test.py 
    ('test', '123456/data/1', datetime.datetime(2018, 4, 13, 8, 47, 11, 621000, tzinfo=<UTC>), 'd41d8cd98f00b204e9800998ecf8427e', 0, None)
    ('test', '123456/data/2', datetime.datetime(2018, 4, 13, 8, 47, 32, 500000, tzinfo=<UTC>), 'd41d8cd98f00b204e9800998ecf8427e', 0, None)
    ('test', '123456/data/3', datetime.datetime(2018, 4, 13, 8, 47, 42, 726000, tzinfo=<UTC>), 'd41d8cd98f00b204e9800998ecf8427e', 0, None)
    ('test', '123456/data/4', datetime.datetime(2018, 4, 13, 8, 47, 48, 44000, tzinfo=<UTC>), 'd41d8cd98f00b204e9800998ecf8427e', 0, None)
