### ISSUE TITLE
Provide a helper function to verify/transform ObjectName

### ISSUE THREAD

**Issue by ahivert** [minio/minio-py#651]
An ObjectName with not authorized characters will generate `SignatureDoesNotMatch` which is not very helpfull.

According to Amazon S3 [doc](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html) some chars must be avoid. 

It should be cool to have a helper function which we can call to transform name before send it to minio.

ex:
```
def get_compliant_name(filename, replacement_char='_'):
    return re.sub(r'[\\^`><{}\[\]#%~|"]', replacement_char, filename)
```

**Comment by deekoder** [comment]
This is a nice ask. @ahivert  the calling application could do that. Minio complies with S3 protocol so we are obligated to return similar error messages.

**Comment by harshavardhana** [comment]
> An ObjectName with not authorized characters will generate SignatureDoesNotMatch which is not very helpfull.
> 
> According to Amazon S3 doc some chars must be avoid.

can you provide the object name? all UTF-8 characters are supported - AWS S3 simply mentions these characters to avoid but it would work properly if the signature is generated properly and object names are properly URL encoded.

**Comment by ahivert** [comment]
Did not try to URL encode the objectName I will try !

My object name is like this :
`Project#1~96783~98976432.pdf`

Le lun. 16 avr. 2018 à 20:39, Harshavardhana <notifications@github.com> a
écrit :

**Comment by ahivert** [comment]
Just tried and you are right @harshavardhana. Urlencode the objectname resolves char problems.

```python
object_name = urllib.quote(filename.encode('utf-8'))
```

Thank's ! :slightly_smiling_face:
