### ISSUE TITLE
put_object doesn't save metadata. save only 'x-amz-meta-KEY' keys

### ISSUE THREAD

**Issue by gzvulon** [minio/minio-py#655]
**Description:**
When I try to save dict to metadata with put_object, 
it saves only keys which starts with 'x-amz-meta'
all other key are ignored, nested dicts are rising errors

**Versions:** 
3.0.5 and 4.0.0

**sample code to reproduce:**
```python
import minio
import io
client = minio.Minio('localhost:9000')
data_str="somestr"
oname='pp/gg.txt'
data = io.BytesIO(jpeg_str.encode())
client.put_object('uploads', oname, data, len(data_str), metadata= {
    'x-amz-meta-testing': 'values',
    'x-amz-meta-setting': 'zombies',
    'amz-meta-setting': 'zombiesddd',
    'hhh':34,
    'u_u': 'dd',
    'y-fu-bar': 'zoo'
})
stat = client.stat_object('uploads', oname)
print(stat.metadata)
```
**Actual output:**
> {'X-Amz-Meta-Setting': 'zombies', 'X-Amz-Meta-Testing': 'values'}

**Expected output:**
same as original metadata dict

Is it by design?

**Comment by poornas** [comment]
@gzvulon, you are right - this is a bug. Will send in a fix shortly.
