### ISSUE TITLE
fput_object: AWS S3 multipart upload fails

### ISSUE THREAD

**Issue by anpr** [minio/minio-py#675]
minio version: 4.0.2

## Reproduce Steps

The bug happened on our system, and some minimal steps would be this (not tested, sorry):
```python
from minio import Minio
minio_client = Minio(...) # setup to run against AWS S3
amz_meta_data = {'x_amz_meta-sha256': 'foo'}
minio_client.fput_object(bucket_name='our-bucket-name',
                         object_name='large_file.jpeg',
                         file_path='/path/to/large_file.jpeg',
                         content_type='image/jpeg',
                         metadata=amz_meta_data)
```

## Current Behaviour

An `InvalidArgument: InvalidArgument: message: Invalid Argument` exception is thrown, the upload is not finished.

## Possible Solution

I debugged this, and what happens is apparently that an AWS S3 multipart upload is initiated, which consists of (among other things) a [Initiate Multipart Upload](https://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadInitiate.html) and an [Upload Part](https://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadUploadPart.html) request.

The initiate multipart request runs through, but the upload part request has a 400 error response:
```
<Error><Code>InvalidArgument</Code><Message>Metadata cannot be specified in this context.</Message><ArgumentName>x-amz-meta-sha256</ArgumentName><ArgumentValue>1f/29/1f29c29fb3fde0d6f9a211d74872c1b0b267d09e83e6a18bfb7b1a4d71c0352e
```

Some googling found [this answer on the AWS forum](https://forums.aws.amazon.com/thread.jspa?threadID=223994), where it is pointed out that you shouldn't pass metadata to the upload part request, only to the initiate multipart upload request.

Therefore, I suspect the solution is to adjust the minio code accordingly.

**Comment by harshavardhana** [comment]
> Some googling found this answer on the AWS forum, where it is pointed out that you shouldn't pass metadata to the upload part request, only to the initiate multipart upload request.

You are right we will fix this, I am assuming fput_objects works without metadata
