### ISSUE TITLE
Upload bytes

### ISSUE THREAD

**Issue by nasirali1** [minio/minio-py#677]
Is there a way to upload bytes object to aws s3? Something similar as below:

some_runtime_serialized_object = b'Inital value'
s3Client.put_object("output-bkt", "something/serialzed.pickle", some_runtime_serialized_object, sys.getsizeof(some_runtime_serialized_object))

I am trying to avoid to write it to disk and then upload to aws-s3 using minio. Boto3 provides this feature. However, I already have all minio api implemented and want to reuse it for aws-s3.

**Comment by harshavardhana** [comment]
Can you provide a full sample program which doesn't seem to be working in your case?

**Comment by nasirali1** [comment]
## SAMPLE CODE
from minio import Minio
import sys
from io import BytesIO
s3Client = Minio('s3.amazonaws.com', access_key='KEY', secret_key='KEY', secure=True)
some_runtime_serialized_object = BytesIO(b'Here we have some more data')
s3Client.put_object("output-bkt", "something/ff.gz", some_runtime_serialized_object, some_runtime_serialized_object.tell())

## MORE INFO
I solved the issue. sys.getsizeof was the culprit. You may close this issue. Thanks!
