### ISSUE TITLE
.list_objects and metadata

### ISSUE THREAD

**Issue by jayrbolton** [minio/minio-py#679]
When I do the following:

```py
objects = minio_client.list_objects_v2(bucket_name)
for obj in objects:
  print(obj.metadata)
```

It gives `None` as the metadata for all objects when the object definitely has metadata. This is true for both `list_objects` and `list_objects_v2`.

To reproduce:

```py
metadata = {'xyz': 'xyz'}
minio_client.fput_object(bucket_name, 'object_id', '/tmp/hello-world.txt', metadata=metadata)
stat = minio_client.stat_object(bucket_name, 'object_id')
stat.metadata  # -> {'X-Amz-Meta-Xyz': 'xyz'}
objects = minio_client.list_objects(bucket_name)
for obj in objects:
   print(obj.metadata)  # -> None
   print(minio_client.stat_object(bucket_name, obj.object_name).metadata)  # -> {'X-Amz-Meta-Xyz': 'xyz'}
```

**Comment by kannappanr** [comment]
@jayrbolton Thanks for filing the issue. We were able to reproduce the issue. We will send a fix for this issue soon.

**Comment by harshavardhana** [comment]
List objects never return metadata as part of the listing in the S3 protocol - you need to use stat_object to get the object metadata.

**Comment by kannappanr** [comment]
@jayrbolton Based on comments by @harshavardhana , we will fix the documentation.

**Comment by jayrbolton** [comment]
Thanks, that works. Is there a bulk request for fetching metadata on multiple objects?

**Comment by kannappanr** [comment]
I don't think there is an S3 API.
