### ISSUE TITLE
Return URL on fput

### ISSUE THREAD

**Issue by ranvijayj** [minio/minio-py#689]
Hi, 

Is there a way I can store the URL to access the object as soon as I put the object using fput api?

I want to upload and then share the image with my other application.

**Comment by ranvijayj** [comment]
`In [14]: a=minioClient.fput_object('maylogs', 'tessdsadst.log', '/tmp/test.log')`

`In [15]: a`
`Out[15]: 'd41d8cd98f00b204e980099823f8427e'`

Getting a hash but how can I get image URL that I can access?

**Comment by kannappanr** [comment]
@ranvijayj For the user to anonymously access the object, you should set anonymous download access for the object or the bucket or the object prefix within the bucket.
You can construct the URL yourself, for example in the case of `play`, the connection is `https` and the endpoint is `play.minio.io:9000`. For a bucket named `test` and an object named `image.png`, the url will be `https://play.minio.io:9000/test/image.png` 

In some cases, if virtual domain style is enabled on the server side, then this will become `https://test.play.minio.io:9000/image.png`. This is generally not very common.

Depending on your requirements, you can also use `https://docs.minio.io/docs/python-client-api-reference.html#presigned_get_object`

**Comment by kannappanr** [comment]
@ranvijayj Closing this issue as answered. Please feel free to open a new issue, if you have any other question.
