### ISSUE TITLE
Force closing connection?

### ISSUE THREAD

**Issue by alejandroandreu** [minio/minio-py#694]
Is there a way to force closing a connection when using `minio.Minio`? Let's assume that I create some buckets, do some operations and want to close the connection explicitly. Is this possible?

**Comment by kannappanr** [comment]
@alejandroandreu, In general, it is internally managed in Python. If it is required, you can have your own implementation of urllib3.poolmanager to do this.

**Comment by alejandroandreu** [comment]
Ok good, thanks!
