### ISSUE TITLE
list_objects never populating is_dir=True?

### ISSUE THREAD

**Issue by trel** [minio/minio-py#695]
I'm trying to understand the `is_dir` key of the objects returned by `client.list_objects()` and `client.list_objects_v2()`.

I am only ever seeing the value set to `False`

```
<Object: bucket_name: testingbucket object_name: b'thefolder/' last_modified: 2018-09-05 00:46:46+00:00 etag: d41d8cd98f00b204e9800998ecf8427e size: 0 content_type: None, is_dir: False, metadata: None>
```

I was expecting to see this folder reporting with `is_dir: True`.

I am testing with AWS S3 proper.  Does that matter?

Am I holding it wrong?

**Comment by harshavardhana** [comment]
you are correct we should fix this @trel

**Comment by trel** [comment]
Thanks.

I’ve got a workaround for now by just testing via `.endswith('/')`.
