### ISSUE TITLE
Unable to catch exception while using stat_object

### ISSUE THREAD

**Issue by CoolBoi567** [minio/minio-py#701]
Since there is no `object_exists()` function, I used `stat_object()` function to check if an object with same name exists in a bucket and catch it with an exception to pass it just that one.
Good that I got the **NoSuchKey Error** for objects which don't exist.
But I am not able to catch that specific exception.

Temporary fix which I am using is the following one. It will work fine, but may even ignore other errors if occurred.
```
try:
     res = minioClient.stat_object('jam', sha1 + '.txt')
     return Response('''{
         "status": "error",
         "response": "The content object already exists in Minio"
     }''', mimetype="application/json")
except:
     pass
```

**Comment by CoolBoi567** [comment]
I already tried this. Doesn't work out.
Debugger catches an exception saying:
    ```NameError: global name 'NoSuchKey' is not defined```

While if I try catching all exceptions, it says

**Comment by harshavardhana** [comment]
@CoolBoi567 the example posted by @kannappanr works perfectly fine

```
python /tmp/test.py 
NoSuchKey: message: The specified key does not exist.
```

**Comment by kannappanr** [comment]
@CoolBoi567 Closing this issue as answered. Please feel free to reach out to us, if you have further questions.
