### ISSUE TITLE
parallel file download

### ISSUE THREAD

**Issue by h5rdly** [minio/minio-py#705]
Hi,

First of all, cheers for this great library. While trying to figure out how to talk to S3 with "vanilla" python, I found minio-py, which is wonderfully easy to follow around, and it ended up with a self contained [snippet](https://gist.github.com/h5rdly/30e3dbb28f46ca5fdc404155438017c9) for downloading a part of a file from S3.

I was wondering - boto3 has has the S3Transfer class, which downloads from S3 concurrently. Does this use another request type, or is this the regular ranged download split between threads? Is this something that can be added to minio-py?

Thanks,
Eli

**Comment by kannappanr** [comment]
@h5rdly Thanks for using `minio-py`. Can you elaborate more on the functionality that you are expecting?  Do you expect that just a single object be downloaded in ranges in parallel? or Do you expect lots of small files to be downloaded in parallel also?

**Comment by h5rdly** [comment]
Hi,

A single file would be a great start. Perhaps something around the shape of:
```python
from multiprocessing import Pool, Array
.
.


def _get_partial_object_top_level(params_tuple):
    ''' Top level shadow copy to allow usage with mp.Pool.map() '''
    
    minio_instance, bucket, key, start, end = params_tuple
    .
    .
    .
    
    return part_of_file
    
    
def get_parallel_file(bucket_name, object_name):
    
    # Create pool and parameters for each _get_partial_object_top_level(...) instance
    pool = Pool()
    file_size = ZZ.stat_object(bucket_name, object_name).size	
    pool_params = (.. ) # Iterator of tuples with bucket name, key name ,start and end of each chunk
    
    # Call the parallel map function and reassemble the file
    file_parts = pool.map(_get_partial_object_top_level, pool_params)
    file = b''.join(file_parts)
    
    return file
```

?

Or you could use `multiprocessing.Array`, I think it may be faster. Would you like me to test out some options and make a pull request?

**Comment by deekoder** [comment]
@h5rdly  we are asking the community for help for some of these features. Will you be able to help us?

**Comment by h5rdly** [comment]
@deekoder I would love to, haven't contributed to open projects before

**Comment by deekoder** [comment]
@h5rdly  we can help you. Why dont you do the code and we can show you how to send a PR?

**Comment by kannappanr** [comment]
Closing this issue now. Have marked this issue for future. Will re-open this issue when we get time to do this.
