### ISSUE TITLE
Some gaps in the documentation

### ISSUE THREAD

**Issue by knipknap** [minio/minio-py#717]
I have a hard time finding information about some of the information found in the Python Client API docs:

- `get_object()` returns an `urllib3.response.HTTPResponse` object, while `fget_object` returns an object that contains a lot of extra information (like `stat_object()` does). I am guessing that this info is also included in the HTTP response header when using `get_object()`, but the docs don't say. Is there a way to parse this into a stat()-like object, or will I have to make a separate API call using `stat_object()`?

- The docs for `list_objects()` mention querying by prefix, but I don't find any further information on the concept, and performance impact, of doing that. I also checked the rest of the Minio documentation, but found nothing useful.

- Similarly, how does the .is_dir attribute work? How do you create an object that is a directory? And it mentions prefixes in the same documentation, so how do those relate do directories?

- Is there any way to query on metadata?

- What's an etag? Is it a unique ID for an objects? And if so, how can I get an object based on that?

- Is there a way to query based on content_type?

Any help would be appreciated.

**Comment by kannappanr** [comment]
@knipknap 

Here is what you can do with `get_object` to get the same information like `stat_object`

```
from minio import Minio
from minio.error import ResponseError

client = Minio('127.0.0.1:9000',
               access_key='minio',
               secret_key='minio123',
               secure=False)

# Get a full object
try:
    data = client.get_object('bucket', 'object')
    content_size = int(data.headers['content-length'])
    print(content_size)
    print(data.headers['content-type'])
    print(data.headers['etag'])
    print(data.headers['last-modified'])

except ResponseError as err:
    print(err)
```
As far as `list_objects` api is concerned, please take a look at https://docs.aws.amazon.com/AmazonS3/latest/API/v2-RESTBucketGET.html

`is_dir` attribute is set if the object listed is a directory. `prefix` is more like if you have lots of objects in a bucket and have already grouped based on a prefix, then you can use the prefix to filter out and get just that subset f objects.

There isn't a way to query based on metadata and content-type. Please look at https://docs.aws.amazon.com/AmazonS3/latest/API/v2-RESTBucketGET.html for more information.

`ETag` is a S3 concept. Please look at https://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonResponseHeaders.html for more info on this.

**Comment by knipknap** [comment]
Awesome, Thanks for the fast and clear response! This answers all of my questions :-).

**Comment by kannappanr** [comment]
@knipknap Thanks for using minio-py. I will go ahead and close this issue. We will also take a look at your questions again and see, if we need to add any of these in our documentation.
