### ISSUE TITLE
Customizable metadata JSON encoder

### ISSUE THREAD

**Issue by smomni** [minio/minio-py#726]
An "TypeError: expected string or bytes-like object" is raised if I pass `metadata={'None': None}` to `fput_object`. To bypass this error, you would have to map None as "null". However, the desired encoding would be `{"None": null}` which is not possible in the current implementation ("null" != null).

Same error is raised when passing nested metadata, such as `{'foo': 'bar', 'system_info': {'orange': 'apple'}}`

See [json.JSONEncoder](https://docs.python.org/3.6/library/json.html#json.JSONEncoder) for reference.

**Comment by kannappanr** [comment]
@smomni I am not sure if S3 supports nested metadata

https://docs.aws.amazon.com/AmazonS3/latest/user-guide/add-object-metadata.html#add-object-metadata-user-defined

https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html.

Regarding to be able to pass null as a value, can you not work around it by passing an empty string?

**Comment by smomni** [comment]
@kannappanr Thanks for the reply!

I tried both null and nested values with the aws cli but got similar errors (`'NoneType' object has no attribute 'encode'` and `'collections.OrderedDict' object has no attribute 'encode'`) as the cli is written in Python as well.

You may be right that nested structures are not supported. As for null values, empty strings shall suffice as replacement.
