### ISSUE TITLE
Minio Python API Client: CERTIFICATE_VERIFY_FAILED with self signed certificate

### ISSUE THREAD

**Issue by knipknap** [minio/minio-py#730]
I am using the Minio Python API client to access a Minio server running in a docker container.
I have configured SSL by mounting the (self signed) public and private key into the container.

SSL appears to be working fine with curl, when I pass the CA certificate:

```
$ https_proxy= curl --cacert deploy/minio/certs/cacert.pem --resolve minio:2000:127.0.0.1 https://minio:2000
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Resource>/</Resource><RequestId>1567BC9DB72456EE</RequestId><HostId>3L137</HostId></Error>$
```

But the Python client doesn't work:

```
MaxRetryError: HTTPSConnectionPool(host='localhost', port=2000): Max retries exceeded with url: /files.ips.bucket/ (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)'),))
```

Here's how I set up the connection:

```
MINIO_ENDPOINT = os.environ.get('MINIO_STORAGE_ENDPOINT', "localhost:2000")
MINIO_ACCESS_KEY = os.environ.get('MINIO_ACCESS_KEY')
MINIO_SECRET_KEY = os.environ.get('MINIO_SECRET_KEY')
MINIO_REGION = None
MINIO_USE_HTTPS = True

connection = Minio(settings.MINIO_ENDPOINT,
                                 settings.MINIO_ACCESS_KEY,
                                 settings.MINIO_SECRET_KEY,
                                 settings.MINIO_USE_HTTPS,
                                 settings.MINIO_REGION)
```

I have searched the docs and Google to no avail - how do I tell the Python client to check against my root certificate?

**Comment by deekoder** [comment]
This is  a documentation issue. We will fix it here.

**Comment by deekoder** [comment]
@sinhaashish assigning this to @eco-minio

**Comment by ralston3** [comment]
Just an FYI, **+1**'ing this as the docs don't explicitly state "make your own `http_client` or use our default client". Could be something [as simple as an asterisk on this page](https://docs.min.io/docs/python-client-api-reference.html) (for the Python examples)

**Comment by solarist** [comment]
Is there any update to this? I am getting the same error with minio-py 5.0.8, Python 3.8.2, MinIO 2020-03-25T07:03:04Z on Ubuntu 18.04.3. I am setting the `http_client` with ca_cert pointing to the correct certificate. 
(Is this actually related to the fact that recent versions of Python implement their own openssl?)

**Comment by solarist** [comment]
So I managed to get rid of the error. In case of self signed certs, the ca_cert in http_client (or SSL_CERT_FILE) should point the the full chain of certificates (including root and all intermediate ones) . The error from urllib ain't actually very helpful here...

**Comment by zhangtai** [comment]
@solarist Can you please elaborate? I have similar issue, can access form web and mc client no issue, but can't connect via Python SDK. Thanks!

```log
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='my.domain', port=12345): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:1108)')))
```

**Comment by solarist** [comment]
@zhangtai try something like this, maybe it helps.
```
from minio import Minio
from minio.error import ResponseError
import urllib3

httpClient = urllib3.ProxyManager(
                'https://proxy_host.sampledomain.com:8119/',
                timeout=urllib3.Timeout.DEFAULT_TIMEOUT,
                cert_reqs='CERT_REQUIRED',
                ca_certs='/usr/local/share/ca-certificates/CA-Bundle.crt'
            )
minioClient = Minio('your_hostname.sampledomain.com:9000',
                    access_key='ACCESS_KEY',
                    secret_key='SECRET_KEY',
                    secure=True,
                    http_client=httpClient)
```
The file that `ca_certs` points to should have the full chain of certificates. Just as a general way to produce one see [here](https://medium.com/@superseb/get-your-certificate-chain-right-4b117a9c0fce) or any other tutorial on how to get the certificate chain right. Other option beside setting `ca_cert` in your `http_client` is to set the env variable `SSL_CERT_FILE` to the path of the file.

**Comment by balamurugana** [comment]
Please try latest release v7.0.0 and refer https://github.com/minio/minio-py/blob/7.0.0/docs/API.md. Please reopen if you still have the problem.

**Comment by SqrtPapere** [comment]
I currently have latest release of minio (7.1.0) but still facing this issue. I don't relly know much about certificates and proxies but why do I need one? I am just trying to connect to a minio cluster I have on a server in the same VPN. mc works but not the sdk.

I also tried with the code suggested by @solarist but I don't understand if I need to change the proxy address.

Can someone please explain? :)

**Comment by solarist** [comment]
Without proxy would be something like this:
```

from minio import Minio
import urllib3

httpClient = urllib3.PoolManager(
                cert_reqs='CERT_REQUIRED',
                ca_certs='/usr/local/share/ca-certificates/CA-Bundle.crt')
minioClient = Minio('your_hostname.sampledomain.com:9000',
                    access_key='ACCESS_KEY',
                    secret_key='SECRET_KEY',
                    secure=True,
                    http_client=httpClient)

```

**Comment by kingsabru** [comment]
Just in case you want to test Minio TLS connection with a self-signed certificate, [this article](https://devopscube.com/create-self-signed-certificates-openssl/) provides a working guide. Once you're done creating the necessary files/objects follow these additional steps:
1. Go to the Minio Operator Console and select your Tenant. In the **Security** section, add the **server.crt** and **server.key** to the **Minio Server Certificates** options. _You can ignore the Client and CA certificates options. You only need that if you'll be verifying client connections from the server._
2. In your Python script, specify the location of the **rootCA.crt** file (or any other name you used) as shown in @solarist [solution](https://github.com/minio/minio-py/issues/730#issuecomment-881601045). You can now connect over TLS.
