### ISSUE TITLE
Add tests to source distribution

### ISSUE THREAD

**Issue by jayvdb** [minio/minio-py#731]
Please add the tests to the sdist, and ideally any extra steps needed for `setup.py test` to work, to make it easier to package and test it.

**Comment by jayvdb** [comment]
Also the LICENSE needs to be included.

**Comment by harshavardhana** [comment]
Unable to understand why tests should be included? Isn't `git clone ` of this repo not helpful?

**Comment by jayvdb** [comment]
Spec files fetch the tarball from pypi https://build.opensuse.org/package/view_file/home:jayvdb:django/python-minio/python-minio.spec?expand=1

They do not want to clone a repo, choose a tag, etc, as those things are all different for each project.  pypi is the central authority on what each version consists of.
