### ISSUE TITLE
Minio Python SDK doesn't support touch operation

### ISSUE THREAD

**Issue by ahmedabt** [minio/minio-py#732]
The SDK does not support uploading a file with zero content length, this operation is used to touch files or create a virtual directory.

To reproduce the issue:
--------------------------
content = BytesIO(b"")
put_object(bucket_name=bucket_name, object_name="dummyfile", data=content, length=0)

Error:
------
minio.error.SignatureDoesNotMatch: SignatureDoesNotMatch: message: The request signature we calculated does not match the signature you provided.

If you tried the same operation using s3 boto python SDK, it works fine
s3_client.put_object(Bucket=bucket_name, Key="dummyfile", Body=b"")

**Comment by nitisht** [comment]
Thanks for reporting @ahmedabt , we'll take a look soon

**Comment by Praveenrajmani** [comment]
Hi @ahmedabt , Ofcourse we can create zero-sized objects in minio-py.

The following script works fine for me.

```
from minio import Minio
import io

client = Minio('localhost:9000',
               access_key='minio',
               secret_key='minio123',
               secure=False)

try:
    for i in range (0, 3):
        print i
        client.put_object('testbucket', "zero-"+str(i), io.BytesIO(b""),
                0, content_type='application/text')
except Exception as e:
    print(e)

```

And minio-py does not support `path` parameter in put. Please refer [https://docs.minio.io/docs/python-client-api-reference.html#put_object](url)

**Comment by ahmedabt** [comment]
"path" was just a typo. the issue was that the key is "dummy file" with space which is not allowed. I think we can close this ticket. thanks for checking it.
