### ISSUE TITLE
get_object doesn't return the object if the path does not starts with slash "/"

### ISSUE THREAD

**Issue by ahmedabt** [minio/minio-py#734]
Inconsistent behavior between minio sdk get_object and boto3 s3 get_object

## To reproduce the issue:
use object_name without a slash
get_object(bucket, "directory/dummy.file").read()
it will return 0 bytes, while if you tried using slash
get_object(bucket, "/directory/dummy.file").read()
it works

## In s3 SDK, it works with both scenarios
s3_client.get_object(Bucket=bucket, Key="directory/dummy.file")["Body"].read()
s3_client.get_object(Bucket=bucket, Key="/directory/dummy.file")["Body"].read()

**Comment by kannappanr** [comment]
Not sure what is going on in your case and which s3 you are connecting to.

This code works against play

```
from minio import Minio
from minio.error import ResponseError
from io import BytesIO

client = Minio('play.minio.io:9000',
                access_key='Q3AM3UQ867SPQQA43P2F',
                secret_key='zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG',
                secure=True)

try:
    print(client.get_object('test', 'abc/123').read())

except ResponseError as err:
    print(err)

```

**Comment by ahmedabt** [comment]
@kannappanr: actually it is still reproducible from my side but not on play using the example you shared

I am using minio SDK 4.0.7 and minio server RELEASE.2018-12-19T23-46-24Z and the actual path is much longer XXXX/XXXXX/XXXXXXXX/XXXX_XXXXXXXXXX/test-file1.txt

**Comment by kannappanr** [comment]
@ahmedabt I tried using version `RELEASE.2018-12-19T23-46-24Z` and unable to repro the issue there. Can you try to reproduce it on `play` with the exact `object` name that fails for you on your setup?

Also, can you give more info about your `minio` setup? which operating system are you running it on, minio mode etc.

**Comment by kannappanr** [comment]
@ahmedabt Can you please provide the information requested?

**Comment by harshavardhana** [comment]
Closing this issue as stale @ahmedabt feel free to reopen if it's still an issue.
