### ISSUE TITLE
minio.error.InvalidEndpointError: InvalidEndpointError: message: Hostname cannot have a scheme.

### ISSUE THREAD

**Issue by eorsavik** [minio/minio-py#737]
I have downloaded Minio python SDK from here :  https://docs.minio.io/docs/python-client-quickstart-guide.html

After installation, I come to example directory "/minio-py/examples" and tried to execute following python script:  "**bucket_exists.py**"

I found the following error:
**minio.error.InvalidEndpointError: InvalidEndpointError: message: Hostname cannot have a scheme.**

Could anyone tell me the reason for this error ?

sammy@D-113131822:~/minio-py/examples$ python bucket_exists.py
Traceback (most recent call last):
  File "bucket_exists.py", line 22, in <module>
    client = Minio('http://10.141.67.190:9010', access_key='IW9LUW5SE4Z34RAVHZ4S', secret_key='CS4FfMLrH8VUEzqyfya9uixaK3yhQ+IvJf5+vBHe')
  File "build/bdist.linux-x86_64/egg/minio/api.py", line 147, in __init__
  File "build/bdist.linux-x86_64/egg/minio/helpers.py", line 286, in is_valid_endpoint
minio.error.InvalidEndpointError: InvalidEndpointError: message: Hostname cannot have a scheme.

**Comment by nitisht** [comment]
@eorsavik can you try   

`client = Minio('10.141.67.190:9010', access_key='IW9LUW5SE4Z34RAVHZ4S', secret_key='CS4FfMLrH8VUEzqyfya9uixaK3yhQ+IvJf5+vBHe',secure=False)`

**Comment by eorsavik** [comment]
Hi Nitisht,
Even after adding "secure=False", I am facing the same error.

..../minio-py/examples$ python bucket_exists.py
Traceback (most recent call last):
  File "bucket_exists.py", line 22, in <module>
    client = Minio('http://10.141.67.190:9010', access_key='IW9LUW5SE4Z34RAVHZ4S', secret_key='CS4FfMLrH8VUEzqyfya9uixaK3yhQ+IvJf5+vBHe', **secure=False**)
  File "build/bdist.linux-x86_64/egg/minio/api.py", line 147, in __init__
  File "build/bdist.linux-x86_64/egg/minio/helpers.py", line 286, in is_valid_endpoint
minio.error.InvalidEndpointError: **InvalidEndpointError: message: Hostname cannot have a scheme.**
sammy@D-113131822:~/minio-py/examples$

Thanks...

**Comment by nitisht** [comment]
please remove http from the hostname, i.e. just use 10.141.67.190:9010

**Comment by eorsavik** [comment]
Thank you very much, Nitisht. It works now.

**Comment by xed** [comment]
I have the same error on python 3.8.1, downgrade to python 3.8.0 to fix this issue.

**Comment by vadmeste** [comment]
This seems duplicated to this https://github.com/minio/minio-py/issues/835

**Comment by vadmeste** [comment]
> I have the same error on python 3.8.1, downgrade to python 3.8.0 to fix this issue.

@xed  I think #835 is the correct issue to follow, not this one

**Comment by wittyquipper** [comment]
I'm trying the following code to access the Minio object using IPv6 hostname

```
from minio import Minio
minio_obj = Minio(
    '[540b:y0k0:172:983e:b6g2:3::]:9000',
    access_key='************************',
    secret_key='***************'
)
```
But I get the following error

```
InvalidEndpointError                      Traceback (most recent call last)
<ipython-input-93-8d37f84766f3> in <module>
----> 1 minio_obj = Minio(endpoint_url, access_key,secret_key, secure=True)

~/anaconda3/lib/python3.7/site-packages/minio/api.py in __init__(self, endpoint, access_key, secret_key, session_token, secure, region, http_client, credentials)
    140 
    141         # Validate endpoint.
--> 142         is_valid_endpoint(endpoint)
    143 
    144         # Validate http client has correct base class.

~/anaconda3/lib/python3.7/site-packages/minio/helpers.py in is_valid_endpoint(endpoint)
    335 
    336         if not _ALLOWED_HOSTNAME_REGEX.match(url.hostname):
--> 337             raise InvalidEndpointError('Hostname does not meet URL standards.')
    338     except AttributeError as error:
    339         raise TypeError(error)
```

`InvalidEndpointError: InvalidEndpointError: message: Hostname does not meet URL standards.
`I'm able to access the same using boto3 client though.

If I use `https://` in front of the url I get `InvalidEndpointError: message: Hostname cannot have a scheme.`

What would be causing this error?
