### ISSUE TITLE
How to add new metadata to some existing file using python SDK ?

### ISSUE THREAD

**Issue by eorsavik** [minio/minio-py#741]
How is it possible to add a new metadata to an existing file using python client API ?
My objective is to add multiple new custom metadata to some existing files. I do not see any API reference for that operation.

Secondly, I want to search all the files/objects having some specific metadata set to them. Is there any API for that ? 

I was referring the script "copy_object_with_metadata.py". In this script if we make source and destination pointing to the same file,  then probably we can set new metadata, but it will overwrite any existing one.

**Comment by kannappanr** [comment]
@eorsavik S3 doesn't have any APIs that allows this behavior. You will have to either keep the existing metadata or replace with yours. 

In your case, you can replace the existing metadata with yours. You will have download the existing metadata and add what you want to, then do a `copy` pointing to the same file.

**Comment by eorsavik** [comment]
Thank you so much, @kannappanr .
Is it possible to search objects based on object metadata ? 
Is there any API available for that ?

One way could be to call the 'stat_object' method for all the objects, parse the results and search for specific metadata.

Thanks..

**Comment by kannappanr** [comment]
@eorsavik There is no API to search based on metadata, but you can have bucket notification on your Put and Delete object requests and store the metadata in a database and then query it.

You can also do `stat_object` and then parse the results.

**Comment by eorsavik** [comment]
Thank you @kannappanr . Yes we have used stat_object to find the object containing some specific metadata. Bucket notification we have not tried yet.
