### ISSUE TITLE
Support max_keys parameter in list_object_v2

### ISSUE THREAD

**Issue by ahmedabt** [minio/minio-py#742]
Support max_keys parameter in list_object_v2 function to limits the maximum number of listed objects.

For reference: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.list_objects_v2

**Comment by kannappanr** [comment]
@ahmedabt Will check internally and get back to you on this request.

**Comment by kannappanr** [comment]
@ahmedabt If you look at documentation https://docs.minio.io/docs/python-client-api-reference.html#list_objects_v2 we return an iterator. You can stop iterating after the max keys are reached.

**Comment by ahmedabt** [comment]
@kannappanr it is not the same, the idea is to limit the time taken and the amount of data returned from the server.

**Comment by harshavardhana** [comment]
Pagination is not provided on purpose @ahmedabt Minio SDKs are richer APIs to avoids the complexities of S3 APIs.

Sending maxkeys lesser I don't think it reduces the time, it in-turn increases the chattiness where you are sending more requests to server to fetch next batch. Most time server spends is during list and sorting the first list, it is same for 100 or 1000 keys. Can you explain why was this conclusion reached ?

If you still want low level access then AWS SDKs are a better option, we don't see a good reason to do this feature.

**Comment by kannappanr** [comment]
@ahmedabt Closing this issue based on the previous comment. Please feel free to reach out to us if you have further questions.
