### ISSUE TITLE
please provide a get_or_create() method for buckets

### ISSUE THREAD

**Issue by guettli** [minio/minio-py#743]
This is  the example code:

```
try:
       minioClient.make_bucket("maylogs", location="us-east-1")
except BucketAlreadyOwnedByYou as err:
       pass
except BucketAlreadyExists as err:
       pass
```

Source: https://docs.minio.io/docs/python-client-quickstart-guide

This looks way to complicated for me.

Why not provide a convenient `get_or_create()` method?

**Comment by kannappanr** [comment]
@guettli We would like to keep the API here very simple.

Also, `BucketAlreadyExists` will be returned only in the case of `AWS S3`  when the bucket is owned by another user. code related to this can probably be removed from the documentation.

Only error remaining is `BucketAlreadyOwnedByYou`. Application can decide to either handle it or not.

**Comment by guettli** [comment]
to simplify it would make sense. 

Catching the exception, and then reraising it again does not make sense, to:
```

except ResponseError as err:
       raise
```

**Comment by harshavardhana** [comment]
Current API abstraction is meant for create bucket our APIs are based on currently agreed upon requirement and providing easy to use equivalents.

What you are asking is a higher level abstraction where we will be consuming multiple exceptions, this is not in our intention and it's an incorrect design from our point of view.

You should write this exception handling in your application.

**Comment by guettli** [comment]
my initial euphoria has sattled. Let's see what alternatives exist.
