### ISSUE TITLE
Minio example error : ImportError: No module named urllib3

### ISSUE THREAD

**Issue by eorsavik** [minio/minio-py#751]
I have downloaded minio sdk from here "https://docs.min.io/docs/python-client-quickstart-guide.html" and build it from source.

However when running the example program "list_buckets.py", it gives me following error:

sammy@localhost:~/minio-py/examples$ python list_buckets.py
Traceback (most recent call last):
  File "list_buckets.py", line 19, in <module>
    from minio import Minio
  File "/usr/local/lib/python2.7/dist-packages/minio/__init__.py", line 36, in <module>
    from .api import Minio
  File "/usr/local/lib/python2.7/dist-packages/minio/api.py", line 48, in <module>
    import urllib3
ImportError: No module named urllib3

Regards,
Aveek

**Comment by nitisht** [comment]
https://pypi.org/project/urllib3/ is a dependency you need to install @eorsavik . Can you install and try again?

**Comment by eorsavik** [comment]
Yes I did that. But looks like there are chain of dependencies. Now I am getting different import error. 
I am planning to uninstall the minio sdk which I installed from the source.  Once uninstalled, I will install it again using pip.

How can I uninstall minio sdk ? 
Is it the correct command ?  ==>  $python setup.py uninstall

**Comment by Praveenrajmani** [comment]
@eorsavik `python setup.py install` will install all the dependencies.

**Comment by Praveenrajmani** [comment]
To uninstall, You should manually remove the installation binary in your local dist-packages (`/usr/local/lib/python2.7/dist-packages`). Or simply doing a pip install will update the binary. 

Did u see any error while executing `python setup.py install` ?

**Comment by eorsavik** [comment]
Somehow I managed to uninstall minio sdk. 
Installed again using pip. It installed all the dependent modules as well. 
Now the example programs running fine.

Hence it is recommended to install sdk using pip.
