### ISSUE TITLE
SSLError(SSLEOFError(8, u'EOF occurred in violation of protocol (_ssl.c:590)'

### ISSUE THREAD

**Issue by eorsavik** [minio/minio-py#754]
While I was trying to execute the script "python list_buckets.py", it gives me following error.

=================
.......
  File "/home/aveek/.local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    **response_kw)
  File "/home/aveek/.local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    **response_kw)
  File "/home/aveek/.local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    **response_kw)
  File "/home/aveek/.local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    **response_kw)
  File "/home/aveek/.local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/aveek/.local/lib/python2.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='127.0.0.1', port=9000): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, u'EOF occurred in violation of protocol (_ssl.c:590)'),))
====================**

What could be the reason for this error ?
Python version I am using :  Python 2.7.12

TLS version I am using:
tls_version":"TLS 1.2

Is it possible the port 9000 is blocked in this case ?

Thanks,
Aveek

**Comment by nitisht** [comment]
Yes, looks like client is not able to connect to the server address (127.0.0.1:9000)

**Comment by poornas** [comment]
from [this](https://github.com/kennethreitz/requests/issues/3337) thread, looks like unsetting proxy settings might help.

**Comment by eorsavik** [comment]
No, that (Unset https_proxy and http_proxy) didn't help.
I see the following error message in the Minio server side.

ERRO[0032] Received non-HTTP message from new connection 10.81.34.160:48670 at server 10.81.34.242:9000  cause=junk message source=[listener.go:205:github.com/minio/minio/pkg/http.(*httpListener).start.func2()]

**Comment by nitisht** [comment]
do you have `secure=True` set in the client constructor? If you MinIO instance is not setup with TLS, please set `secure=False`

**Comment by eorsavik** [comment]
Thank you, Nitish, it solved the problem when I set secure=False.  
What I need to do if I want to setup MinIO instance with TLS ?

**Comment by nitisht** [comment]
you an refer https://docs.min.io/docs/how-to-secure-access-to-minio-server-with-tls

**Comment by eorsavik** [comment]
Thank you so much. :)

**Comment by nitisht** [comment]
Closing this as working as expected. Please join us on Slack for further questions http://slack.min.io
