### ISSUE TITLE
Downloads created with presigned_get_object() use internal host and only work from internal host instead of using MINIO_DOMAIN as expected

### ISSUE THREAD

**Issue by JonasT** [minio/minio-py#759]
None of the URLs presigned_get_object() spits out for me work, I just wait forever and minio never answers the request. The thing is though, with the same client browser, client ip, the same minio instance & same proxy (no restarts in between) I can go into the minio UI and generate an URL directly in there, and that one **works**.

The (shortened) URL which I get from presigned_get_object which *doesn't work*:
```
https://files...com/479...0026-tmpupbuck/...pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=430...iyr9%2F20190507%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190507T103903Z&X-Amz-Expires=600&X-Amz-SignedHeaders=host&X-Amz-Signature=297...e00
```
The (shortened) URL the UI gave me which works fine:
```
https://files...com/479...0026-tmpupbuck/...pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=430...iyr9%2F20190507%2F%2Fs3%2Faws4_request&X-Amz-Date=20190507T105820Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=461...44d
```

Is something with `presigned_get_object()` broken?

Edit: I use minio as in the `latest` docker image of today

**Comment by vadmeste** [comment]
@JonasT would you give us a minimal code which reproduces this in your case ?

**Comment by JonasT** [comment]
It always works locally without the proxy in between, so I'm not too sure what is going on. But on the production server it *never* works, and as you can see the one URL does look slightly different (it has a datacenter location embedded, the working one doesn't) so I wonder if that is related?

**Comment by JonasT** [comment]
(sorry, I phrased that vaguely: I was meant to say since in my dev environment it just works it will be difficult for me to trace this down to a shorter amount of code)

Is there any log file I could check that could give you a clue? In the docker container log I sadly can't see anything interesting, not even a line indicating a request happened

**Comment by vadmeste** [comment]
@JonasT when you say the presigned url doesn't work ? what do you mean ? what does happen exactly ?

**Comment by JonasT** [comment]
@vadmeste it hangs for a really long time (a minute or longer) then the browser gives me `Secure Connection Failed` which is probably the nginx forward proxy (to which I am connecting as the direct target) cutting off the request entirely. When I use the working URL from the UI through exactly the same proxy with the same browser with the same minio instance behind then I get an instant working download

**Comment by vadmeste** [comment]
@JonasT are you sure the hangs occurs at this line ?

`url = cl.presigned_get_object(bucket_name, obj_name, expires=expires)`

**Comment by JonasT** [comment]
@vadmeste no that one works fine, the hang occurs during the actual request! (the URL gets displayed to me, and I open it in the web browser)

So minio-py returns an URL just fine, it's just that the actual minio server doesn't properly hand me out the file if I ever try to use it. And any URL I get through the minio server's UI to the very same bucket & object works, and both URLs share the same host & domain & proxy but the minio-py one just doesn't work

**Comment by vadmeste** [comment]
@JonasT could you paste your Minio server and minio-py versions ?

**Comment by JonasT** [comment]
This is the minio server version as the UI tells me right on the affected production instance: `2019-05-02T19:07:09Z` (I use the `minio` image from docker hub)

And this is the minio-py version as installed in my custom ubuntu-based website backend docker image:
```
# docker-compose exec website bash -c "pip3 freeze | grep minio"
minio==4.0.16
```

**Comment by vadmeste** [comment]
@JonasT I am not able to reproduce this with the same version as mentioned, do you have any short python code which reproduces this ?

**Comment by JonasT** [comment]
I don't even have long code that reproduces it on my dev machine... so sadly no. But it happens 100% on my production machine, I just can't go and delete half the code there while it is up & running with visitors to find out what would be required to make it happen.

But I could add debug output of any sorts, or poke around in the minio server logs if that helps?

**Comment by JonasT** [comment]
Ok I found `MINIO_HTTP_TRACE` and observed two things:

1. The file access of my web browser is logged with an instant 403 with `SignatureDoesNotMatch`. The hang is just that for some reason it takes really long to get through the proxy. Not sure why but I suppose it doesn't really matter, since there shouldn't be a 403 in the first place

2. There are many accesses to the affected bucket and other objects in that bucket, but *not one single API request* to that exact object inside it before the actual 403'ed download. Shouldn't I see a minio linux API request coinciding with `presigned_get_object` that actually somehow requests an expiring access on the server? Surely the server can't somehow guess that a token was given out with a certain expiration time, so is the problem that such an API call should happen but isn't actually happening?

**Comment by JonasT** [comment]
I examined the two HTTP requests (one to the broken minio-py URL, and one to the working one from the share button in the UI) as they arrive on the server, and:

1. They got exactly the same request URL, except for the `X-Amz-Credential` parameter which has an additional `us-east-1` in the string as already mentioned above for the **broken** one and that not being present for the working one, and `X-Amz-Signature` being different, and `X-Amz-Date` being the same format but a slightly different time

2. X-Forwarded-For/X-Real-Ip, User-Agent, and all other headers are also the same, just jumbled about in order

And of course to one the response is 403 with `<Code>SignatureDoesNotMatch</Code>` and to the other it's 200 + download

**Comment by kannappanr** [comment]
@JonasT Is it possible that the `url` was generated using a wrong `secret key`?

**Comment by kannappanr** [comment]
This is a working python script
```
from minio import Minio
from minio.error import ResponseError
from datetime import timedelta

client = Minio('play.min.io:9000',
               access_key='Q3AM3UQ867SPQQA43P2F',
               secret_key='zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG', secure=True, region='us-east-1')

# presigned get object URL for object name, expires in 7 days.
try:
    print(client.presigned_get_object('test', 'issue', expires=timedelta(minutes=10)))
# Response error is still possible since internally presigned does get
# bucket location.
except ResponseError as err:
    print(err)
```
If you modify the secret key, in this script, it will still generate a pre-signed url but will result in `signaturemismatch`

**Comment by JonasT** [comment]
@kannappanr I just logged out and copied the secret from the python backend config and could log into the UI just fine, so I'm pretty sure it is correct.

However, the python backend logs in via `secure=False`/HTTP via internal direct connection unlike your example above, and while the actual download also arrives via HTTP (being HTTPS only up to the outside proxy) at the actual minio instance, it does so with `X-Forwarded-Proto: https`/`X-Forwraded-Ssl: on` which isn't set on the python backend connection. Also, the `Host` of the failing external download request matches the `MINIO_DOMAIN` name in minio's docker env, but **not** the host used by the python backend/minio-py to connect which is an internal docker host instead. That wouldn't happen to make a difference?

**Comment by JonasT** [comment]
Also I just checked the docs, and `MINIO_REGION` isn't present in my minio docker config/env which according to the docs that means it should be "unset". And my `Minio()` call in python also has no region parameter, which I assume corresponds to "unset" - so why does `us-east-1` appear in the `X-Amz-Credential` parameter? Is minio-py actually defaulting to `us-east-1` as region while the minio server considers it "unset", and maybe that is the problem?

**Comment by kannappanr** [comment]
@JonasT If no region is set, then by default it is assumed that the region is `us-east-1`.

**Comment by JonasT** [comment]
Ok I just made it work, by:

1. Taking the url which was generated with https + `MINIO_DOMAIN` in it by minio-py itself (which I haven't changed, minio-py / the minio server somehow in tandem figured out to do that)
2. Removing https + host and replacing it with http + internal docker host
3. Opening a bash prompt in the python backend container and wget'ing that modified URL

So yeah, it seems minio-py uses `MINIO_DOMAIN` to make the URL but somehow signs it as if using its own internal hostname instead, resulting in a broken/unusable URL

**Comment by JonasT** [comment]
Actually scratch that, it does generate it using the internal host :man_facepalming: I had code changing it to the `MINIO_DOMAIN` and forgot about it. So that's obviously the issue, but why would it not use the `MINIO_DOMAIN` to generate the URL and how can I make it do that? The server itself does that in the UI just fine, even though that is not how it is reached via the browser

**Comment by JonasT** [comment]
After further review and stumbling across https://github.com/minio/minio-go/issues/1046 just now, I think minio-py (and all other wrappers) should either:

1. request the proper external name from the server, after all it knows the name that is reachable from the outside and uses it for its own URL generation in the host even when reached differently

OR

2. add a parameter to allow me to specify this external host when calling `presigned_get_object()` (or alternatively as an additional parameter when instantiating the connection via `Minio(...)` itself, although that makes less sense in my head since for most other operations it appears to be irrelevant)

Requiring such an internal client to connect via the *external* host just to be able to generate externally usable public URLs makes no sense and is IMHO a bad requirement from a security standpoint, after all I'm using an internal target for a reason: I am in a protected network so I want to use it, anything that possibly risks routing outside if there is an issue with DNS or the router, even if just one unnecessary hop, is simply increasing the attack vector with no useful gain other than to work around this library limitation

**Comment by vadmeste** [comment]
@JonasT, generating a presigned url doesn't make any active connection to the server, so actually you can put any address when initializing your client

**Comment by JonasT** [comment]
ah that's a nice workaround :+1: :smile: however, in the medium turn I suggest you change this since it feels like counter-intuitive in terms of API design - it is not obvious `presigned_get_object` won't connect to the server, and the idea of making a second client that is not an actual client just to generate a proper URL is not exactly anything that came to my mind for any other similar API before

it'll solve the problem for me so I appreciate this workaround a lot :heart: but I still highly suggest to give `presigned_get_object()` a parameter to override this. if just to save all the other future users coming to the library the time to figure out this same problem

**Comment by kannappanr** [comment]
@JonasT We do connect to the server if `region` is not specified in the constructor. Because each `bucket` is associated to a ``region, we have to do that. But if the user provides the region, then it is not required to connect to the server.

In your case, the following code will work

```
from minio import Minio
from minio.error import ResponseError
from datetime import timedelta

client = Minio('test.com:9000',
               access_key='minio',
               secret_key='minio123', secure=False, region='us-east-1')

# presigned get object URL for object name, expires in 10 minutes.
try:
    print(client.presigned_get_object('mybucket', 'issue', expires=timedelta(minutes=10)))
# Response error is still possible since internally presigned does get
# bucket location.
except ResponseError as err:
    print(err)
```
assuming `MINIO_DOMAIN` is set to `test.com`

**Comment by JonasT** [comment]
One more reason to add a proper option to `predesigned_get_object`, isn't it?

**Comment by JonasT** [comment]
Actually, the current setup does worry me a lot. Because it *could* connect via the outside and I wouldn't even know, it's not like the host wouldn't be reachable that way as well.

I really think you should fix this and provide a non-hacky way to do this

**Comment by vadmeste** [comment]
> I still highly suggest to give `presigned_get_object()` a parameter to override this.

Are you saying we could add 'hostname' and 'region' parameter to presigned_get_object() ?

**Comment by JonasT** [comment]
@vadmeste yes exactly that would be my suggestion. Add an url_hostname, url_port and url_region parameter to `presigned_get_object()`. The workaround of instantiating an actual client is IMHO too risky to recommend, at least in environments where much safer local link is available and therefore accidentally requesting/establishing a route through outside is undesirable

**Comment by kannappanr** [comment]
We spoke about this internally, we can also extend this to use one credential to create presigned urls for other users also, then this API becomes too long. Instead of that, you can have a function that does this for you

```
from minio import Minio
from minio.error import ResponseError
from datetime import timedelta

def presignedurl(endpoint, accesskey, secretkey, isssl, bucket, objectname, region, expires):
    return Minio(endpoint,
               access_key=accesskey,
               secret_key=secretkey, secure=isssl, region=region).presigned_get_object(bucket, objectname, expires=expires)
```

It can be called like this

```
print(presignedurl("localhost:9000", "minio", "minio123", False, "test", "issue", "us-east-1", timedelta(minutes=100)))
```

**Comment by JonasT** [comment]
@kannappanr are you saying `then this API becomes too long` is more important than fixing the fact you're requiring me (and everyone else in this situation to instantiate `Minio()` when I definitely don't want to connect via that host for safety reasons??

I'm all for clean API design, but if your minimalism puts me at risk for an external route for traffic I definitely don't want there then IMHO you're overshooting monumentally.

Also how do *optional* additional keyword arguments cause the API to become "too long"? How does this affect anyone who doesn't make use of it? If this is really about the complexity of the function, why not just add a separate optional `presigned_get_object_with_other_host()` or something?

I just think you're putting the completely wrong priorities here

**Comment by JonasT** [comment]
(and if this wasn't obvious I'm fine with using the code sample above for my own project. I just think this is a significant shortcoming that should also fixed *for everybody else*, and they shouldn't need to google dig up this ticket then figure out they need to call some function in a more unusual way and they had better get it right or it would route outside of their internal data center network with actual *production credentials* since you can't even put fake credentials to make it work. Why do I even need to convince anyone that this is kind of a problem?)

**Comment by harshavardhana** [comment]
> @kannappanr are you saying `then this API becomes too long` is more important than fixing the fact you're requiring me (and everyone else in this situation) to instantiate `Minio()` when I definitely don't want to connect via that host for safety reasons, calling a function that may actually open up a connection in some cases?? (I get that it doesn't if you put the region, but that I even need to be careful about that should show that this is not the way to go)

@JonasT @kannappanr already showed how to do it, this is not standard behavior for our SDK and we don't want to have non-standard APIs just to satisfy this requirement. 

What is posted by @kannappanr already works in the situation what you want. We will not be implementing an additional API here.

**Comment by kannappanr** [comment]
@JonasT We can always add a check in the function that will require all the values to be passed.

I don't see any difference between what I have and what you had suggested earlier ```Add an url_hostname, url_port and url_region parameter to presigned_get_object(). ```

**Comment by JonasT** [comment]
@kannappanr the huge difference is that someone already said it could connect outside, and that means you are essentially making me call a function that is *designed* to call outside in some cases *which I will never want to*.

This is not a big problem if I get it right, but 1. will everyone get it right, and why would you want them to risk not getting it right just to save two very easy to understand parameters? And more importantly, 2. why would you want to risk to stick to the exact semantics when this connects outside and introducing security holes in other people's code when you ever forget to stick to these semantics exactly?

I guess if I'm really the only person with this setup your decision makes sense. But isn't the cloud *the* environment where people (especially those using on-premise, or your actual minio server and not the bog-standard S3 variant) would run into this all the time, and also the environment where people would usually want to solve this properly

Sorry, I'll really shut my mouth now. I am just hoping to give you some food for thought because apart from this your API is currently pretty neat which is why this somewhat sticks out

**Comment by JonasT** [comment]
Sorry, maybe I didn't fully understand your suggestion. If your suggestion is to change `presigned_get_object()` to always require all parameters, document that it never connects outside and make sure that it never does, then that does indeed sound like an improvement. However, it's still not obvious instantiating `Minio()` itself won't establish a connection, so while this would certainly make the usage less risky it's still somewhat counter-intuitive in my humble opinion and not as obviously safe as it should be

**Comment by harshavardhana** [comment]
> Sorry, maybe I didn't fully understand your suggestion. If your suggestion is to change `presigned_get_object()` to always require all parameters, document that it never connects outside and make sure that it never does, then that does indeed sound like an improvement. However, it's still not obvious instantiating `Minio()` itself won't establish a connection, so while this would certainly make the usage less risky it's still somewhat counter-intuitive in my humble opinion and not as obviously safe as it should be

We do welcome these suggestions @JonasT but it is overkill for us to mention these things, it is obvious that constructor won't make network requests - mentioning this simply makes it's verbose without adding new value.  This is how AWS SDKs are designed and we do follow the best practices here as rest of them.i

So AFAICS there is no action from us here, it is working as expected and there are wrappers which can be implemented in the application as needed.

**Comment by JonasT** [comment]
> We do welcome these suggestions @JonasT but it is overkill for us to mention these things

Is just mentioning that really already too much? And why is it obvious it doesn't connect? It certainly wasn't to me. To someone deeply familiar with S3 maybe, but why is that your only target audience especially if this is fixable with a sentence in the docs?

The bigger problem however is with `presigned_get_object()` which not only not obviously doesn't connect, but apparently does actually connect sometimes

Why not make at least some sort of FAQ entry for this sort of "special" scenario (I still think you may be underestimating how common it probably is) and document for both `Minio()` and `presigned_get_object()` that they will never ever connect outside so people can rely on it?

**Comment by kannappanr** [comment]
@JonasT  Will modify `presigned_get_object` documentation appropriately to make it clear. Closing this issue now. Please feel free to reach out to us if you have further questions.
