### ISSUE TITLE
ConnectionReset error in fget_object

### ISSUE THREAD

**Issue by abandiya** [minio/minio-py#766]
Whenever there is at least one connection in pool manager and I call fget_object, it fails with below exception:

```
minio_client.bucket_exists(bucket_name):
minio_client.fget_object(bucket_name, 
                            file_name, out_name)
```

> Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)

If I clear out the pool and call fget_object then it works.

```

minio_client.bucket_exists(bucket_name):
minio_client._http.clear()
minio_client.fget_object(bucket_name, 
                            file_name, out_name)
```

**Comment by kannappanr** [comment]
@abandiya Can you please provide more information or a sample code to reproduce the issue.

I tried 
```
from minio import Minio
from minio.error import ResponseError

client = Minio('play.min.io:9000',
               access_key='mcclean',
               secret_key='minio123')

try:
    print(client.bucket_exists('test'))
    print(client.fget_object('test', 'NA18537.vcf.gz.tbi', '/tmp/file'))
except ResponseError as err:
    print(err)
```
and was unable to reproduce the issue

Also what version of `minio-py` re you using?

**Comment by vadmeste** [comment]
Not able to reproduce the issue too, @abandiya, what's your minio-py version ?

Also, as @kannappanr suggested, it would be great if you could provide a complete sample code which reproduces this

**Comment by abandiya** [comment]
My code is pretty much the same as yours.
I am using 4.0.17 version of minio-py.
I am running RELEASE.2019-05-23T00-29-34Z of minio in docker.
Could this be a Minio server issue?

**Comment by vadmeste** [comment]
@abandiya is this error consistent in your case ?

Do you see any logs in Minio server side ? (`docker logs your_minio_container_name`)

**Comment by abandiya** [comment]
Sorry for late reply, Closing this as it is not reproducible in a different environment
