### ISSUE TITLE
Conda packaging

### ISSUE THREAD

**Issue by tjd2002** [minio/minio-py#768]
Please make minio-py available for installation with [conda](https://docs.conda.io/en/latest/).

Apart from being an easy way to install minio-py for use by developers, it enables software that depends on minio-py to be made available using conda (see, e.g. https://github.com/datajoint/datajoint-python/issues/293 )

Packaging could either be done by: 
1) Building the package during CI, then hosting it in a custom channel at anaconda.org (which can then be installed with `conda install -c minio minio`)
2) Creating a feedstock at conda-forge, which will result in conda packages being automatically built by their CI and posted at anaconda.org. (They can then be installed with `conda install -c conda-forge minio`)

The latter has the advantage of being quite trivial--you essentially just use conda-forge to wrap the pip package--but it would require that the version of the feedstock at conda-forge be manually bumped as part of the release process.

A [search on anaconda.org for minio](https://anaconda.org/search?q=minio) shows that at one point a couple years ago someone was building packages for minio-server and minio-client, but those have not been maintained.

Since conda can be cross-language, and can be used to install all sorts of stuff, it may be advisable to call the package `minio-py`, rather than just `minio`. (Although it is mostly used for python  package distribution, so it could also be a good idea to give it the same name as the pip package, i.e. `minio`.)

**Comment by kannappanr** [comment]
@tjd2002 Will take a look and get back to you.

**Comment by tjd2002** [comment]
OK, I have just proposed a new feedstock on conda-forge. If you want to go that route I can add you as the maintainer. 

(Note it is acceptable for folks outside the project to maintain packages on conda-forge; but obviously you all should be the maintainers there if you want to be!)

**Comment by tjd2002** [comment]
Relevant conda-forge docs: https://conda-forge.org/docs/maintainer/adding_pkgs.html

**Comment by tjd2002** [comment]
OK, minio 4.0.17 is now available on conda-forge! (Feedstock repo here: https://github.com/conda-forge/minio-feedstock)

```
conda install -c conda-forge minio
python -c 'import minio'
```

If one or more of the minio devs wants to take over as a maintainer of the conda-forge minio package, that would be awesome; just issue a PR against [the recipe](https://github.com/conda-forge/minio-feedstock/blob/master/recipe/meta.yaml) adding your GitHub username to the `extras/recipe-maintainers' section. (And then we can close https://github.com/conda-forge/minio-feedstock/issues/1 )

If not, then that package will just continue to exist as a community-supported package, with no official relationship with the minio devs or project. Many packages on conda-forge operate like this, with volunteers contributing to the recipe maintenance.

**Comment by harshavardhana** [comment]
> If not, then that package will just continue to exist as a community-supported package, with no official relationship with the minio devs or project. Many packages on conda-forge operate like this, with volunteers contributing to the recipe maintenance.

@tjd2002 this is acceptable to us

**Comment by tjd2002** [comment]
> @tjd2002 this is acceptable to us

OK! If you change your mind, or if any other minio user wants to help out just hop over to the feedstock.
