### ISSUE TITLE
Re-using client object for multi-threading leads to corrupt data

### ISSUE THREAD

**Issue by andrewtmendoza** [minio/minio-py#771]
Hello,

I have a singleton class to re-use a Minio client object:

![image](https://user-images.githubusercontent.com/4677802/59302282-77fb4280-8c48-11e9-8545-3f40150321de.png)

However, I've noticed some cases where the contents of multiple files are mixed together:
![image](https://user-images.githubusercontent.com/4677802/59302337-9bbe8880-8c48-11e9-9dcb-95cd0a799d2f.png)
In the image above, the contents of **var/log/nginx/nginx_l3svc.status** and **var/log/nginx/access.log** have been combined, separated by what appears to be a line of null values.

I'm using multi-threading to upload multiple files simultaneously - is it possible that the client object is not thread-safe? Instantiating a new client object within each thread seems to resolve the issue.

I am using Python 3.7 and Minio v4.0.11

**Comment by kannappanr** [comment]
@andrewtmendoza Thanks for filing this issue. We will take a look and get back to you.

**Comment by ebozduman** [comment]
@andrewtmendoza, 
Could you give us more details on how to reproduce the issue, like full script, the scenario, your setup, and/or any other related info to reproduce the problem in house?

By the way, you know your singleton class, `MinioClient`, instance creation in `get_instance(cls)` method is not thread safe.

**Comment by andrewtmendoza** [comment]
@ebozduman, we tried removing the singleton and creating a new client in each thread, but we got the same error.

After further investigation, we've found that Minio is not the cause of this error. We were trying to use multithreading with a tarfile, which turns out to be a known bug: https://bugs.python.org/issue23649

**Comment by ebozduman** [comment]
@andrewtmendoza ,
Thank you...
