### ISSUE TITLE
sorting order of the objects returned by list_objects

### ISSUE THREAD

**Issue by JeetThakare** [minio/minio-py#775]
What is the default sorting order of the object generator returned by `list_objects`?

**Comment by kannappanr** [comment]
Amazon S3 lists objects in UTF-8 character encoding in lexicographical order.

PTAL https://docs.aws.amazon.com/AmazonS3/latest/API/v2-RESTBucketGET.html

MinIO does the same. Please reach out to us at https://slack.min.io for such questions.
