### ISSUE TITLE
Minio generated 'access_key' and 'secret_key' are user login dependent. 

### ISSUE THREAD

**Issue by eorsavik** [minio/minio-py#776]
Minio generated 'access_key' and 'secret_key' are user login dependent. When we start the Minio server using different user login, it generate different 'access_key' and 'secret_key'. is it expected behavior ? 

In a solution how we can ensure Minio server always generate same 'access key' and 'secret key' although any user can start the server ?

Thanks

**Comment by nitisht** [comment]
you can set the environment variables `MINIO_ACCESS_KEY` and `MINIO_SECRET_KEY`

**Comment by eorsavik** [comment]
That's mean we need to parse the 'access_key' and 'secret_key' from the output log that Minio server generate and set the environment variable accordingly.
Is there any better way ?

If we run the Minio server as a Linux service (using systemd), is setting environment variable the only option  ? 

Thank you...

**Comment by nitisht** [comment]
You can set the credentials using environment variables @eorsavik . MinIO will honour the values set in these variables. Ref https://github.com/minio/minio-service/tree/master/linux-systemd#create-default-configuration

**Comment by kannappanr** [comment]
@eorsavik MinIO generates access and secret key only in the case of `standalone fs mode`. In all the other scenarios it is advisable to set the environment variable. Values set in Environment variable will override the ones generated by MinIO. So, in your case if you set the environment variables, they will take precedence.

**Comment by eorsavik** [comment]
Let me try. Will update accordingly.
Thank you so much...

**Comment by kannappanr** [comment]
ping @eorsavik. Were you able to try it out?

**Comment by eorsavik** [comment]
Sorry for the late reply.
Yes, it works fine. Thank you all for your support.

When Minio is run from 'systemctl', where does it generate log ?
Can we configure the location of Minio log file ?

Thank you so much ....

**Comment by kannappanr** [comment]
You should use `journalctl` to view the logs. Closing this as answered. Please feel free to reach out to us if you have further questions
