### ISSUE TITLE
Access Denied with custom policy

### ISSUE THREAD

**Issue by viewpointsa** [minio/minio-py#778]
Like in documentation :
```
cat > getonly.json << EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "s3:GetObject"
      ],
      "Effect": "Allow",
      "Resource": [
        "arn:aws:s3:::my-bucketname/*"
      ],
      "Sid": ""
    }
  ]
}
EOF
```

then

`mc admin policy add myminio getonly getonly.json`

Add new user 

`mc admin user add myminio newuser newuser123 getonly`

Add new configuration

`mc config host add myminio-newuser http://localhost:9000 newuser newuser123 --api s3v4`

And test it:
`mc cat myminio-newuser/my-bucketname/my-objectname`
Note: cp do not work

Now try with python code:
```
from minio import Minio
from minio.error import ResponseError

minioClient = Minio('localhost:9000',
                  access_key='newuser',
                  secret_key='newuser123',
                  secure=False)
                  
try:
    data = minioClient.get_object('my-bucketname', 'my-objectname')
except ResponseError as err:
    print(err)
```
Output:
`minio.error.AccessDenied: AccessDenied: message: Access Denied`

With wireshark I see 3 query with mc command:
```
http://localhost:9000/my-bucketname/?location=
http://localhost:9000/my-bucketname/?delimiter=%2F&max-keys=1000&prefix=my-objectname
http://localhost:9000/my-bucketname/my-objectname
```
Only first one is send with python api

**Comment by vadmeste** [comment]
@viewpointsa 'irstea', shouldn't it be 'my-bucketname' instead ? or vice versa ?

**Comment by viewpointsa** [comment]
sorry I'm have not hide every bucketname

**Comment by vadmeste** [comment]
> sorry I'm have not hide every bucketname

Sure, what you did seems to be correct, going to test this locally, can you tell us what are the versions of your Minio server and mc and minio-py ?

**Comment by viewpointsa** [comment]
Ok, I find the solution I must specify a region, in Minio constructor

```
minioClient = Minio('smile.viewpoint.fr:9000',
                  access_key='newuser',
                  secret_key='newuser123',
                  region='fr',
                  secure=True)
```

**Comment by laughing-nerd** [comment]
> Ok, I find the solution I must specify a region, in Minio constructor
> 
> ```
> minioClient = Minio('localhost:9000',
>                   access_key='newuser',
>                   secret_key='newuser123',
>                   region='fr',
>                   secure=True)
> ```

It worked! Thanks a lot
