### ISSUE TITLE
python client.stat_object raise 'NoSuchKey: message: The specified key does not exist.'

### ISSUE THREAD

**Issue by xdreamman** [minio/minio-py#780]
when I use python: minio 4.0.0 stat_object
bucket_name : image
object_name : human/import/boteye_select_vertical/20190418/20190418220/5120_01201_1555642445656%2B5120_01201_1555642446657/2019071602_1555642442789_74_1555642442740.jpg

%2B  == '+'

## Current Behavior
raise:  
NoSuchKey: message: The specified key does not exist.

## Steps to Reproduce (for bugs)

1. object_name include '+'
2. use stat_object

**Comment by nitisht** [comment]
Thanks for reporting @xdreamman we'll take a look

**Comment by Praveenrajmani** [comment]
@xdreamman looks like the object key `human/import/boteye_select_vertical/20190418/20190418220/5120_01201_1555642445656%2B5120_01201_1555642446657/2019071602_1555642442789_74_1555642442740.jpg` is already encoded. You should not encode/decode the encoded key and then pass it to stat_object?

**Comment by xdreamman** [comment]
@Praveenrajmani 
ok，I will try this tomorrow.

**Comment by Praveenrajmani** [comment]
@xdreamman The key in the presigned URL is already signed. Stat will not recognise this. You should use the actual key names in Stat.

**Comment by deekoder** [comment]
@xdreamman  let us know if your issue is not resolved. I will close this out. Feel free to reactivate if you want to discuss further.
