### ISSUE TITLE
Setting region='us-east-1' breaks `get_object` when the URL is not `localhost`

### ISSUE THREAD

**Issue by Shappenny** [minio/minio-py#781]
### Summary
I believe I found a bug while writing unit tests for a custom Python library that uses the minio-py SDK to talk to a MinIO server. Setting `region='us-east-1'` in the Minio constructor generates a `TypeError` in the urllib3 method `urlopen` call made by the minio-py API's `_url_open` method when the host name is not on the same host (e.g. `localhost`). The exact error message is provided in the Traceback section below.

This issue is present regardless of:
- the scheme being HTTP or HTTPS
- passing in a `urllib3.poolmanager.PoolManager` as the `http_client` to the Minio constructor
- passing in a `urllib3.Retry` object with or without `redirect=False`, `remove_headers_on_redirect=False`, `remove_headers_on_redirect=frozenset([])`, or `remove_headers_on_redirect=None` 

The apparent solutions are either:
- Don't pass `region` to the Minio constructor
- Use a `localhost` hostname (appears that this causes `conn.is_same_host(redirect_location)` to return `False` in urllib3's `urlopen` method in poolmanager.py)

### Details
Python version: 3.7.3
MinIO version: 4.0.18
urllib3 version: 1.23, 1.25.3 (tested under both)
OS & kernel: Ubuntu 16.04.1 4.15.0-51-generic

### Traceback
(edited for brevity)
```
Traceback (most recent call last):
  File "/long/bazelpath/object_storage_test.runfiles/org_pypi_minio/minio/api.py", line 672, in get_object
    sse=sse)
  File "/long/bazelpath/object_storage_test.runfiles/org_pypi_minio/minio/api.py", line 1487, in _get_partial_object
    preload_content=False)
  File "/long/bazelpath/object_storage_test.runfiles/org_pypi_minio/minio/api.py", line 1872, in _url_open
    preload_content=preload_content)
  File "/long/bazelpath/object_storage_test.runfiles/org_pypi_urllib3/urllib3/poolmanager.py", line 345, in urlopen
    kw['headers'].pop(header, None)
TypeError: pop() takes 2 positional arguments but 3 were given
```

**Comment by kannappanr** [comment]
@Shappenny I tried 
``
from minio import Minio
from minio.error import ResponseError

client = Minio('play.min.io',
               access_key='Q3AM3UQ867SPQQA43P2F',
               secret_key='zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG', 
               region='us-east-1')

try:
    data = client.get_object('test', 'issue')
    with open('/tmp/issue', 'wb') as file_data:
        for d in data.stream(32*1024):
            file_data.write(d)
except ResponseError as err:
    print(err)
```
Did not see any error. Th  Python version used was `3.6.7`, SDK was `4.0.18`. Can you please paste a sample code to reproduce if what I have works for you?

**Comment by kannappanr** [comment]
@Shappenny Can you please paste a sample code to reproduce if what I have works for you?

**Comment by kannappanr** [comment]
@Shappenny Closing this issue. Please feel free to re-open the issue when you have more information.
