### ISSUE TITLE
`sign_v4` should always add `X-Amz-Content-Sha256` header

### ISSUE THREAD

**Issue by scott-maddox** [minio/minio-py#786]
Currently, `sign_v4` sets the `X-Amz-Content-Sha256` header to 'UNSIGNED-PAYLOAD' when the request is going over HTTPS. However, as can be seen by running `mc --debug`, this header should always be set to the actual digest. I have not tested if the minio server enforces this requirement for all endpoints, but it does appear to enforce it for the admin endpoints (or at least for `minio/admin/v1/add-canned-policy`). Though, admittedly, the admin endpoints do not appear to be supported by this library, currently (hence why I'm writing my own API calls, and why I ran into this bug in `sign_v4`).

**Comment by harshavardhana** [comment]
This behavior is same as AWS S3 SDKs and their recommendation.. TLS traffic automatically protects content so there is no need to add additional checksums.

**Comment by harshavardhana** [comment]
Also this library shouldn't be used for admin APIs its meant for S3 APIs only.

**Comment by kannappanr** [comment]
@scott-maddox closing this issue based on the above comments. Please feel free to reach out to us if you have further questions.

**Comment by scott-maddox** [comment]
Then perhaps there should be an issue on the minio server to not require `X-Amz-Content-Sha256` on the `admin` interface? I'm unclear on which repo that would be, though.

As a side note, is there a reason admin API wrappers are only available in Go? It would be nice to have them in python.

**Comment by harshavardhana** [comment]
Admin interface is not S3 API @scott-maddox so doesn't have the same requirements, it can be additionally relaxed as well to have similar requirements.

The reason is we expect users to use `mc` CLI directly. It is meant for admins not for regular users using an S3 API.
