### ISSUE TITLE
list_buckets() and list_objects() returning empty list/empty generator on Huawei-Openstack in OpenTelecomCloud

### ISSUE THREAD

**Issue by brisoe** [minio/minio-py#788]
Dear all,

when using list_buckets() or list_objects() on an account/bucket in OpenTelecomCloud, the result is an empty list, allthough there are buckets/objects in that account.
Using the minio-client (on Windows or Linux), returns the correct results.
See below code for accessing the account:

```
s3_client = Minio(endpoint=s3_endpoint,
                  access_key=s3_accesskey,
                  secret_key=s3_secretkey,
                  region=s3_region,
                  secure=s3_secure)
the_bucket = s3_bucket
list_buckets = s3_client.list_buckets()  #Returns empty list
is_bucket = s3_client.bucket_exists(the_bucket)  #Returns True
list_objects = s3_client.list_objects(the_bucket)  #Returns empty generator object
[print(obj.object_name) for obj in list_objects]  #Throws the error below
```

Error-Message:

> Traceback (most recent call last):
>   File "C:\OSGEO4~2\apps\Python37\lib\site-packages\minio\parsers.py", line 104, in get_child_text
>     return self.element.find('s3:{}'.format(name), _S3_NS).text
> AttributeError: 'NoneType' object has no attribute 'text'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Program Files\JetBrains\PyCharm\helpers\pydev\pydevd.py", line 1741, in <module>
>     main()
>   File "C:\Program Files\JetBrains\PyCharm\helpers\pydev\pydevd.py", line 1735, in main
>     globals = debugger.run(setup['file'], None, None, is_module)
>   File "C:\Program Files\JetBrains\PyCharm\helpers\pydev\pydevd.py", line 1135, in run
>     pydev_imports.execfile(file, globals, locals)  # execute the script
>   File "C:\Program Files\JetBrains\PyCharm\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
>     exec(compile(contents+"\n", file, 'exec'), glob, loc)
>   File "D:/Users/BRISOE/PyCharm/MUC/hrl_2018/sobr_playground/minio_otc.py", line 19, in <module>
>     [print(obj.object_name) for obj in list_objects]
>   File "D:/Users/BRISOE/PyCharm/MUC/hrl_2018/sobr_playground/minio_otc.py", line 19, in <listcomp>
>     [print(obj.object_name) for obj in list_objects]
>   File "C:\OSGEO4~2\apps\Python37\lib\site-packages\minio\api.py", line 946, in list_objects
>     bucket_name=bucket_name)
>   File "C:\OSGEO4~2\apps\Python37\lib\site-packages\minio\parsers.py", line 238, in parse_list_objects
>     is_truncated = root.get_child_text('IsTruncated').lower() == 'true'
>   File "C:\OSGEO4~2\apps\Python37\lib\site-packages\minio\parsers.py", line 108, in get_child_text
>     'Message: {}').format(self.root_name, name, error.message)
> AttributeError: 'AttributeError' object has no attribute 'message'

Thanks in advance and Best Regards
Sören

**Comment by harshavardhana** [comment]
I don't think we expect minio-py to work properly unless they are S3 compatible - is OpenTelecomCloud S3 compatible ?

**Comment by brisoe** [comment]
Hey,
according to OpenTelecomCloud documentation it is compatible to most features (including list_buckets() and list_objects()):

[Compatibility of OBS REST APIs](https://docs.otc.t-systems.com/en-us/api_obs/obs/en-us_topic_0031666094.html)

Best Regards

**Comment by harshavardhana** [comment]
> according to OpenTelecomCloud documentation it is compatible to most features (including list_buckets() and list_objects()):

Would it be possible to add `trace_on()` to your requests?  we can see what is being returned by the server? @brisoe

**Comment by brisoe** [comment]
Below the result for `s3_client.trace_on(sys.stdout)`:

> GET / HTTP/1.1
> User-Agent: MinIO (Windows; AMD64) minio-py/4.0.20
> Host: obs.eu-de.otc.t-systems.com
> X-Amz-Date: 20190822T131919Z
> X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
> Authorization: AWS4-HMAC-SHA256 Credential=TFOMMLRV9AZVUCWPOOOO/20190822/eu-west-1/s3/aws4_request, SignedHeaders=host;user-agent;x-amz-content-sha256;x-amz-date, Signature=a217aeea11e25fd2478cf9810d029678af951a86d4fe4b9dace01bd590da2ba6
> 
> HTTP/1.1 200
> X-Amz-Request-Id: 051E0000016CB97B43D96DABC72CE23E
> X-Amz-Id-2: IIUmOeIFCRPw1n9sTdyoSf+2iE3v8jbSOVZmThjZLLLDpo+ZBXXGr5Oll0qp7Ism
> X-Reserved: amazon, aws and amazon web services are trademarks or registered trademarks of Amazon Technologies, Inc
> Content-Type: application/xml
> Date: Thu, 22 Aug 2019 13:19:19 GMT
> Content-Length: 938
> ---------END-HTTP---------
> ---------START-HTTP---------
> HEAD /hrl-bucket/ HTTP/1.1
> User-Agent: MinIO (Windows; AMD64) minio-py/4.0.20
> Host: obs.eu-de.otc.t-systems.com
> X-Amz-Date: 20190822T131919Z
> X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
> Authorization: AWS4-HMAC-SHA256 Credential=TFOMMLRV9AZVUCWPOOOO/20190822/eu-west-1/s3/aws4_request, SignedHeaders=host;user-agent;x-amz-content-sha256;x-amz-date, Signature=db890c3def8be8f6aa246969dd51ef676a3fc45beed04ff209adeec9ff175b5b
> 
> HTTP/1.1 200
> X-Amz-Request-Id: 051E0000016CB97B44206DB4CF78BF6A
> X-Amz-Id-2: eE7LBorn1IeeIkj2kNgeCOtIC2oYT48ZOb0nLY6O+TT06663aWMuARDEgx0I0O/H
> X-Reserved: amazon, aws and amazon web services are trademarks or registered trademarks of Amazon Technologies, Inc
> Content-Type: application/xml
> Date: Thu, 22 Aug 2019 13:19:19 GMT
> X-Amz-Bucket-Region: eu-de
> X-Default-Storage-Class: STANDARD
> Content-Length: 0
> ---------END-HTTP---------

I hope that helps.

Best Regards
Sören

**Comment by kannappanr** [comment]
@brisoe Can you try 
```
s3_client = Minio(endpoint=s3_endpoint,
                  access_key=s3_accesskey,
                  secret_key=s3_secretkey,
                  secure=s3_secure)
```

Also, can you paste the debug output when you use `mc`

It should be something like this

`mc ls alias --debug`

**Comment by brisoe** [comment]
**@kannappanr:**
When configuring the client without region, as you suggested, the error is still the same as quoted above. I can paste the http-trace and error-message if wanted.

Below the `mc` Log-Output for listing the buckets in that account:

> mc: <DEBUG> GET / HTTP/1.1
> Host: obs.eu-de.otc.t-systems.com
> User-Agent: MinIO (windows; amd64) minio-go/v6.0.32 mc/2019-08-21T19:59:10Z
> Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20190826/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
> X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
> X-Amz-Date: 20190826T060917Z
> Accept-Encoding: gzip
> 
> mc: <DEBUG> HTTP/1.1 200 OK
> Content-Length: 938
> Connection: Keep-Alive
> Content-Type: application/xml
> Date: Mon, 26 Aug 2019 06:09:14 GMT
> Via: 1.1 192.168.100.252 (McAfee Web Gateway 7.8.2.6.0.27882)
> X-Amz-Id-2: StT0rTo5cL/F08tqcCEyEIRjGWUxxRn06kXLFOzMCwCBkXC2zFy/DwvJ6vAbKmXh
> X-Amz-Request-Id: 05250000016CCC8AF6D05B2DCA8291A4
> X-Reserved: amazon, aws and amazon web services are trademarks or registered trademarks of Amazon Technologies, Inc
> 
> mc: <DEBUG> Response Time:  553.0868ms
> 
> mc: <DEBUG> GET / HTTP/1.1
> Host: obs.eu-de.otc.t-systems.com
> User-Agent: MinIO (windows; amd64) minio-go/v6.0.32 mc/2019-08-21T19:59:10Z
> Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20190826/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
> X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
> X-Amz-Date: 20190826T060917Z
> Accept-Encoding: gzip
> 
> mc: <DEBUG> HTTP/1.1 200 OK
> Content-Length: 938
> Connection: Keep-Alive
> Content-Type: application/xml
> Date: Mon, 26 Aug 2019 06:09:15 GMT
> Via: 1.1 192.168.100.252 (McAfee Web Gateway 7.8.2.6.0.27882)
> X-Amz-Id-2: wpML1yeQGAVRa7BSokhGo6lk7JvVuj/tCxOKlHqrU7QflwNQWYMbEU+WhQjV/7sN
> X-Amz-Request-Id: 05250000016CCC8AF7F75B338D91761D
> X-Reserved: amazon, aws and amazon web services are trademarks or registered trademarks of Amazon Technologies, Inc
> 
> mc: <DEBUG> Response Time:  234.3602ms

Best Regards

**Comment by harshavardhana** [comment]
This is mostly due to incompatibility in the implementation. Since minio-py works fine with S3 - this has to be manually debugged.

**Comment by brisoe** [comment]
**@kannappanr:**
Thanks for your efforts. I found out, it has nothing to do with the region set or not set. 

I did some debugging the last days and the `response.data` returned by the get-request of `urlopen()` contains the corect information. The bytestring-xml with the buckets.
The problem occurs somewhere when parsing the xml and retrieving the bucket information, most likely because a different namespace is used, not `xmlns="http://s3.amazonaws.com/doc/2006-03-01/"`.

Best Regards

**Comment by harshavardhana** [comment]
@brisoe we can't support custom XML namespaces, this restriction exists to avoid incompatiblities in future and make sure that we are always strictly S3 compatible.

Can you verify why the namespace was changed ?

**Comment by ysimonson** [comment]
It looks like the python client library looks for a root element called [`ListBucketsResult`](https://github.com/minio/minio-py/blob/941c517716a1a21d0ff11c68b5dfbc790c059613/minio/parsers.py#L192)

Where does the element name come from?

* According to the current S3 docs, the root element should be [`ListBucketsOutput`](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListBuckets.html)
* According to the *archived* S3 docs, the root element should be [`ListAllMyBucketsResult`](https://docs.aws.amazon.com/AmazonS3/latest/API/archive-RESTServiceGET.html) or [`ListBucketResult`](https://docs.aws.amazon.com/AmazonS3/latest/API/archive-v2-RESTBucketGET.html) (note `Bucket` is not pluralized)

**Comment by harshavardhana** [comment]
> It looks like the python client library looks for a root element called [`ListBucketsResult`](https://github.com/minio/minio-py/blob/941c517716a1a21d0ff11c68b5dfbc790c059613/minio/parsers.py#L192)

That looks like a bug @ysimonson NOTE: we cannot add still custom namespaces.

**Comment by ysimonson** [comment]
I'm kind of confused because it looks like the tests actually check for [`ListAllMyBucketsResult`](https://github.com/minio/minio-py/blob/3a8336ba797b25f5a9c58dfc45579a66e2c28062/tests/unit/list_buckets_test.py#L33) -- maybe that test isn't run though?

**Comment by ysimonson** [comment]
Alright, I tested this out and it looks like the `ListBucketsResult` bit is irrelevant, it's ignoring the root tag name. Changing the namespace to aws' addresses the issue, on my implementation at least.

**Comment by michaelschmit** [comment]
Tangent to this question, should this python client be able to connect to a minio instance running as an azure gateway?  I seem to be running into a similar issue where bucket_exists calls return false even though the bucket exists and make_bucket calls return bucket doesn't exist exceptions.  I believe this is the result of downstream 404 status codes being returned.

**Comment by michaelschmit** [comment]
I tested connecting with the python client locally with a minio azure gateway instance and it works.  The issue I am running into is access it through a reverse proxy.  Rather than pollute this issue I will create a separate one.

**Comment by balamurugana** [comment]
Please try with new release v7.0.0 and reopen with appropriate HTTP traces using `trace_on()` if problem still persist.
