### ISSUE TITLE
Multipart uploads fails on fips enabled RHEL because md5 hash not supported

### ISSUE THREAD

**Issue by petersedivec** [minio/minio-py#789]
We are trying to use the python put_object.  It's failing on anything larger than 5MB because we are required by RHEL STIG to have fips enabled.  md5 is not fips compliant and so it's disabled in the openssl package.  It appears md5 hash is being used to validate the multipart upload was successful and not for encryption, but this seems to be one of the biggest complaints in the community that md5 is NOT available for non-encryption related stuff.

## Expected Behavior
Would like the put_object function to work on a fips enabled platform or provide the ability to set the size limit for multipart upload so we can not use multipart upload until files are over 100MiB.
## Current Behavior
Fails with the following stack trace
```
[root@XXX rms-processed]# python /group/transfer/minio_push.py Traceback (most recent call last):
  File "/group/transfer/minio_push.py", line 59, in <module>
    minioClient.put_object(bucket_name, file, file_data, file_stat.st_size)
  File "/usr/lib/python2.7/site-packages/minio/api.py", line 867, in put_object
    part_size=part_size)
  File "/usr/lib/python2.7/site-packages/minio/api.py", line 1710, in _stream_put_object
    uploaded_parts)
  File "/usr/lib/python2.7/site-packages/minio/api.py", line 1784, in _complete_multipart_upload
    md5_base64 = get_md5_base64digest(data)
  File "/usr/lib/python2.7/site-packages/minio/helpers.py", line 636, in get_md5_base64digest
    return Hasher.md5(content).base64digest()
  File "/usr/lib/python2.7/site-packages/minio/helpers.py", line 594, in md5
    return cls(data, hashlib.md5)
  File "/usr/lib/python2.7/site-packages/minio/helpers.py", line 590, in __init__
    self.h = h(data)
ValueError: error:060800A3:digital envelope routines:EVP_DigestInit_ex:disabled for fips

```
## Possible Solution
Allow user to set size limit for multipart upload or utilize another hash to verify multipart upload

## Steps to Reproduce (for bugs)
Use put_object function and attempt to upload a file greater than 5MiB on a RHEL system with fips enabled
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/security_guide/chap-federal_standards_and_regulations

## Context
For our solution meant to support the Army we will not be able to allow users to upload files larger than 5MiB which would be a major barrier for our Knowledge Management System (KMS)

## Your Environment

* Version used (`minio version`): minio/minio:RELEASE.2019-06-01T03-46-14Z
* Environment name and version (e.g. nginx 1.9.1): Python 2.75
* Server type and version: HP Proliant
* Operating System and version (`uname -a`): RHEL 7.6 w
* Link to your project: Army project - not in public domain

**Comment by petersedivec** [comment]
Yep, that makes sense. Is that a feature minio will consider or do you
recommend we fork and work the sha256 for our own use case. At the moment
it is not a pressing issue for us. We may need it in October but wanted to
put it on the radar and get feedback from community.

**Comment by balamurugana** [comment]
`MD5` is a requirement for various S3 APIs as per AWS S3 specification. As the spec is slowly moving away from `MD5` and we are also adapting the changes. However we cannot break the compatibility.
