### ISSUE TITLE
how to Extending the time  delta settings in expires

### ISSUE THREAD

**Issue by ckl0804** [minio/minio-py#794]
python code : 
from future.backports.datetime import timedelta
        page_url = minioClient.presigned_get_object(bucket_name=bucket_name,object_name='0722.jpg',expires=timedelta(days=10))

the expires=timedelta Defaults to 7days. But now I need keep URL 30days, How todo?
if I set days=30,that Procedural error reporting，
erro info:
minio.error.InvalidArgumentError: InvalidArgumentError: message: Expires param valid values are between 1 sec to 604800 secs

**Comment by vadmeste** [comment]
@ckl0804 according to the S3 specification, the maximum allowed expiry duration is 7 days, you cannot pass 30 days in this case.

**Comment by kannappanr** [comment]
@ckl0804 Closing this issue as answered Please feel free to reach out to us at https://slack.min.io for further such questions.
