### ISSUE TITLE
compose_object 

### ISSUE THREAD

**Issue by nkhandker** [minio/minio-py#800]
compose object functionality in the python SDK so that streamed, chunks of data can be composed together to create a single file in s3

**Comment by vadmeste** [comment]
@nkhandker are you asking to add a new API in minio-py to create an object from a stream data source ?

**Comment by nkhandker** [comment]
No no, rather just any implementation of the "compose_object" function like
in go. I got tunnel vision when I was writing that feature request

**Comment by kannappanr** [comment]
@nkhandker So, basically you want to be able to create an object using data from multiple objects using server side copy. We do not have cycles to implement this feature right now.

**Comment by kannappanr** [comment]
@nkhandker Closing this issue now. Will re-open this issue when we have cycles to work on this.
