### ISSUE TITLE
AttributeError when raising InvalidXMLError

### ISSUE THREAD

**Issue by harpener** [minio/minio-py#801]
Hi guys,

we are getting an `AttributeError` exception saying that `error` object has no attribute `message` [here](https://github.com/minio/minio-py/blob/master/minio/parsers.py#L108)

I think that no exception defined in `_ETREE_EXCEPTIONS` [here](https://github.com/minio/minio-py/blob/master/minio/parsers.py#L48) has such an attribute. 

The only exception is the same list definition [here](https://github.com/minio/minio-py/blob/master/minio/error.py#L36) where the attribute `message` is set to `ParseError` manually.

I think the string representation of these exceptions would be enough. :-) What do you think?

Thanks

**Comment by vadmeste** [comment]
Hey @harpener,

> we are getting an `AttributeError` exception saying that `error` object has no attribute `message` [here](https://github.com/minio/minio-py/blob/master/minio/parsers.py#L108)

What Python version are you using ?

The following code works fine under Python 2.7 and 3.7.

```python
_ETREE_EXCEPTIONS = (SyntaxError, AttributeError, ValueError, TypeError)
_s = "string"

try:
    print _s.foofield
except _ETREE_EXCEPTIONS as error:
    print "Exception message:", error.message
```

**Comment by harpener** [comment]
@vadmeste Sorry, I forgot to mention this. I'm using 3.7.3 on production and 3.7.4 locally. Both behave the same and produce an error for your example. 🤔

**Comment by harpener** [comment]
@vadmeste Furthermore, it is CPython implementation, if it makes any difference. I found some mentions about this attribute being deprecated and removed for a very long time actually: https://www.python.org/dev/peps/pep-0352/#retracted-ideas 🤔

**Comment by vadmeste** [comment]
@harpener I managed to reproduce the issue using python-minimal.

It seems it is safer to use the string representation instead, would you mind sending a PR @harpener ?
