### ISSUE TITLE
Minio signature mismatch over cloudflare

### ISSUE THREAD

**Issue by bbkgh** [minio/minio-py#808]
I am using cloudflare free CDN over a self hosted minio  server but cloudflare changes some headers and for that sign_v4 of request headers doesn't match with server expected value. How can i solve this problem in python client? Is there anyway to disable signature?
Thanks.

**Comment by harshavardhana** [comment]
@bbkgh minio-py is meant to be used with AWS S3 and S3 compatible services such as MinIO - we do not support cloudflare and have no intention of doing it. 

This is out of scope of this project.
