### ISSUE TITLE
minio.error.SignatureDoesNotMatch: SignatureDoesNotMatch: message: The request signature we calculated does not match the signature you provided.  when upload to ceph radosgw

### ISSUE THREAD

**Issue by phchoi** [minio/minio-py#809]
Not sure if the issue I faced is the same as this https://github.com/minio/minio-py/issues/724 , it throws the exception when a file larger than 5MB is being uploaded to ceph radosgw by using minio python API but not via mc client

Environment: 
- python 2.7.5, 
- minio python library version 4.0.17
- minio client: minio version RELEASE.2019-10-09T22-54-57Z

I followed the same troubleshoot methods mentioned in https://github.com/minio/minio-py/issues/724#issuecomment-446368069 and had the log attached ([minio-py.log](https://github.com/minio/minio-py/files/3747698/minio-py.log)). I also attached the same debug log coming from mc client ([mc.log](https://github.com/minio/minio-py/files/3747697/mc.log)
)

Any hints or help will be much appreciated, thanks a lots.

**Comment by kannappanr** [comment]
Please use version 5.0.1 and let us know if you still see this issue. Closing this issue  as fixed
