### ISSUE TITLE
Getting multiple PreSigned Request (i.e. in Bluk) with a single Query.

### ISSUE THREAD

**Issue by gk-patel** [minio/minio-py#813]
**Is your feature request related to a problem? Please describe.**
As far as I know, it is only possible to get a single presigned download URL. I have a frontend, where user is shown a table with 500 to 1000 lines, and each row has a download button, corresponding to a file in Minio. I am using the Python Client, and I have to generate a presigned-download link for each file in a for-loop. It would be nice to generate presigned requests in Bulk. 

**Describe the solution you'd like**
We already have [presigned_get_object](https://docs.min.io/docs/python-client-api-reference.html#presigned_get_object) function in Python library. Maybe this function can be extended to recieve a list of object_names, and then MinIO can deliver presigned-requests in Bulk. 

Thank you for your time and consideration.

**Comment by harshavardhana** [comment]
Just do list_objects and call presigne_get for each output in the iterator.

**Comment by kannappanr** [comment]
@gk-patel SDK will not call minio to generate presigned url, if you set the bucket region. In that case, I do not expect the calls to take a long time and you can simply do what is mentioned in the above comment

**Comment by harshavardhana** [comment]
Also without even the region get bucket location is constant and fetched only once per bucket so optimizing this part is also frviolous and not needed.

**Comment by kannappanr** [comment]
closing this issue. Please feel free to reach out to us at https://slack.min.io for further questions

**Comment by kannappanr** [comment]
@gk-patel We do not hit the server at all if we know the region of the bucket. Even if you do not set the region of the bucket, it is queried only once. So, network delay does not come into the picture here. So, even if you have `1000` objects it will not take extra time.
