### ISSUE TITLE
Use Credentials (similar to minio-go) to enable AWS IAM

### ISSUE THREAD

**Issue by febg** [minio/minio-py#814]
At [codecov.io](https://www.codecov.io) we use minio-py for our on-prem enterprise solution. Our customers have expressed the need of being able to authenticate to AWS using IAM in order to make key rotation much more efficient.

I noticed that there was some kind of effort to add this functionality to the minio-py repository about two years ago.

See issue [#502](https://github.com/minio/minio-py/issues/502) 
See closed PR [#507](https://github.com/minio/minio-py/pull/507/files) 

I also noticed that other minio SDK have this functionality (Eg. [minio-go](https://github.com/minio/minio-go)) and I think would be nice and valuable to have this functionality in the python SDK as well.

I started making changes using PR [#507](https://github.com/minio/minio-py/pull/507/files) and minio-go PR [#646](https://github.com/minio/minio-go/pull/646/files?file-filters%5B%5D=#diff-2f280fb058ba01353aed10f15c61f848L3) as reference. 
It would be great if I can get your feedback on the changes I have done so far trying to add Credentials functionality. I would be more than happy to get all of your guys feedback and modify the changes accordingly.

Link to the changes I have made so far:
https://github.com/minio/minio-py/compare/master...febg:fb_credentials

**Comment by harshavardhana** [comment]
Thanks @febg we will get back on this soon

**Comment by febg** [comment]
Should we even need a signer type attribute for the Value class in the python version? I was thinking on removing signer type from there.

**Comment by harshavardhana** [comment]
We don't that's what I meant by v4 onlu

**Comment by febg** [comment]
Sounds good, I removed signer_type and pushed changes to branch 👍

**Comment by harshavardhana** [comment]
Can you create a PR @febg that would be easy to give feedback.

**Comment by febg** [comment]
@harshavardhana done PR [#817](https://github.com/minio/minio-py/pull/817)
