### ISSUE TITLE
blacklist: Using xml.etree.cElementTree.fromstring to parse untrusted XML data

### ISSUE THREAD

**Issue by huornlmj** [minio/minio-py#822]
Bandit 1.6.2 reports multiple uses of the blacklisted use of `xml.etree.cElementTree.fromstring`, advising to replace it with its defusedxml equivalent function or make sure `defusedxml.defuse_stdlib()` is called.

Is this seen as a FP or valid concern?

**Comment by vadmeste** [comment]
It seems even the standard xml documentation says it has some vulnerabilities and encourage using defused xml https://docs.python.org/2/library/xml.html#xml-vulnerabilities

Even if this is a client and not a server, it looks like it is better to secure it. I guess if http is used, some data can be injected that can affect the normal behavior of minio-py.

**Comment by vadmeste** [comment]
@huornlmj 

I don't think bandit is correct by saying importing xml.etree.ElementTree is discouraged.

If I understood well, fusedxml only rewrites some functions that have vulnerabilities. Other functions such as xml.etree.ElementTree.Element() are still needed for code to work.

Any insights about this ? shall we alert bandit developers ?

**Comment by balamurugana** [comment]
Moved to `xml.etree.ElementTree`. If this is still valid concern, please reopen with possible options. Appreciated if reopened with fix in a PR
