### ISSUE TITLE
Allow using Google Cloud Storage

### ISSUE THREAD

**Issue by danilobellini** [minio/minio-py#823]
When using with `mc`, I can list/copy the contents from Google Cloud Storage.

However, using this Python client instead (Python 3.7.4, minio 5.0.5), I get an empty list when calling `client.list_buckets()`, and `client.list_objects("bucket-name-here")` returns a generator. When I try to get the first element from that generator, it raises this:

```
Traceback (most recent call last):
  File "/home/danilo/.../venv/lib/python3.7/site-packages/minio/parsers.py", line 99, in get_child_text
    return self.element.find('s3:{}'.format(name), _S3_NS).text
AttributeError: 'NoneType' object has no attribute 'text'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/danilo/.../venv/lib/python3.7/site-packages/minio/api.py", line 945, in list_objects
    bucket_name=bucket_name)
  File "/home/danilo/.../lib/python3.7/site-packages/minio/parsers.py", line 233, in parse_list_objects
    is_truncated = root.get_child_text('IsTruncated').lower() == 'true'
  File "/home/danilo/.../venv/lib/python3.7/site-packages/minio/parsers.py", line 103, in get_child_text
    'Message: {}').format(self.root_name, name, error)
minio.error.InvalidXMLError: InvalidXMLError: message: Invalid XML provided for "ListObjectResult" - erroring tag <IsTruncated>. Message: 'NoneType' object has no attribute 'text'
```

**Comment by harshavardhana** [comment]
minio-py is meant for AWS S3 and MinIO not Google Cloud Storage. You should use GCS python SDK for this.

**Comment by danilobellini** [comment]
Minio Client works with Google Cloud Storage using the S3 API: https://docs.min.io/docs/minio-client-quickstart-guide

Google Cloud Storage documentation says it should be compatible with tools that works with S3: https://cloud.google.com/storage/docs/interoperability

That said, if minio-py is really meant for S3, then it should work with GCS (using S3v4) like Minio Client, doesn't it? What makes Minio Client work with GCS but not minio-py?

**Comment by harshavardhana** [comment]
mc works is a coincidence, minio-py works with S3 and MinIO that is sufficient for minio-py and its scope as an SDK @danilobellini
