### ISSUE TITLE
fget_object() creates temporary file in `append` mode

### ISSUE THREAD

**Issue by amedveshchek** [minio/minio-py#824]
Hi.

1. Method `fget_object()` creates temporary file in append (`ab`) mode with stable name.
That means, if you've received an error (e.g. `InvalidSizeError`) and decided to retry, the new object will be appended to previously invalid object. As a result -- invalid object with no error.
2. I propose to overwrite previously created file.

Of course there are alternatives: for example to create real temp autodeleting file with temp name.

**Comment by harshavardhana** [comment]
Good idea, feel free to send a PR.

**Comment by balamurugana** [comment]
fixed by https://github.com/minio/minio-py/pull/825
