### ISSUE TITLE
Support for Amazon S3 Transfer Acceleration?

### ISSUE THREAD

**Issue by cosmosgenius** [minio/minio-py#826]
Minio-go already has support for it. Is there any plan to incorporate the same in python binding?

**Comment by harshavardhana** [comment]
Definitely we can add, feel free to send a PR @cosmosgenius

**Comment by cosmosgenius** [comment]
Hey i have opened a PR(#827) with a rough implementation. Let me know

**Comment by harshavardhana** [comment]
Fixed by https://github.com/minio/minio-py/pull/827
