### ISSUE TITLE
Python admin api

### ISSUE THREAD

**Issue by ruiztulio** [minio/minio-py#829]
Hi, is it possible to access the admin api via the python package? I don't find it in the documetation neither the code (probbably not looking in the right place).

I'm trying to write an app that uses minio. The users, groups and policies will be managed from there. I know I can do it using minio client, but it'd be nice to handle everything from the api itself

If there is no way to do it from the minio-py package, the admin api is documented anywhere? I could only find the mc

Thanks for the work dedicated to this package btw!

**Comment by harshavardhana** [comment]
It is not possible yet, we may do it in the future but not for now.

**Comment by ruiztulio** [comment]
@harshavardhana thanks for the answer...is it documented somewhere?  I wouldn't mind to implement it by myself

**Comment by harshavardhana** [comment]
https://github.com/minio/minio/tree/master/pkg/madmin @ruiztulio

**Comment by ruiztulio** [comment]
@harshavardhana Thanks! I'll close this then

**Comment by jhadjar** [comment]
Hey, @ruiztulio... Did you end up implementing this? We implemented something in that sense here https://big-mama-tech.gitlab.io/bmc/. Would this API suit you? No external libraries, provided you have the `mc` and `minio` command line tools on your machine.

It's still a prototype for our work for https://iko.ai and does not yet completely match `mc` and `minio` CLIs but we'll probably beef it up and share it.

@harshavardhana Is this on the roadmap?

**Comment by harshavardhana** [comment]
> Hey, @ruiztulio... Did you end up implementing this? We implemented something in that sense here https://big-mama-tech.gitlab.io/bmc/. Would this API suit you? No external libraries, provided you have the `mc` and `minio` command line tools on your machine.
> 

This is correct usage.

> It's still a prototype for our work for https://iko.ai and does not yet completely match `mc` and `minio` CLIs but we'll probably beef it up and share it.
> 
> @harshavardhana Is this on the roadmap?

No @jhadjar

**Comment by ThyMakra** [comment]
Hi. @jhadjar that was very helpful though is there anyway to use `bmc` to manipulate `mc admin` to configure the bucket (for example: `bucket quota`)

**Comment by ruiztulio** [comment]
@jhadjar Hi, sorry for reaching you so late, but I did not implement it, actually a few months ago revisited the thread and started using bmc, just works great so far! Cheers!

**Comment by jhadjar** [comment]
> Hi. @jhadjar that was very helpful though is there anyway to use `bmc` to manipulate `mc admin` to configure the bucket (for example: `bucket quota`)?

Hi, @ThyMakra ... Sorry I missed your reply. Yes, I'll implement it and bump the version to `0.0.4`. As of now, it's `0.0.3` at https://pypi.org/project/bmc

Do you want to do things like `mc admin bucket quota myminio/mybucket --fifo 10GB`?

I'll notify you when it's done.

**Comment by djmattyg007** [comment]
@jhadjar Where is the code for bmc stored? The Gitlab links don't work.

**Comment by jhadjar** [comment]
Hi, The homepage on PyPI should be this: https://big-mama-tech.gitlab.io/bmc

You can install it with `pip install bmc`.

**Comment by djmattyg007** [comment]
@jhadjar That's a link to the documentation. Where is the code repository?

And now that I'm thinking about it, what is the license? PyPI just says "other".

**Comment by djmattyg007** [comment]
I can't use software without a license. I wasn't able to find a license in the tarball, and everything else (PyPI, setup.py, etc) doesn't indicate anything other than "Proprietary". This could mean anything at all.

**Comment by jhadjar** [comment]
@djmattyg007 I understand.

**Comment by jhadjar** [comment]
@djmattyg007 When I said "I understand", I meant that I understand that you can't use software without a license. I made a note to add a license and put the project in a GitHub repository.

I also understand that when someone refrains from using a childish tone and a thumbs down, the thought of telling them to go suck a bag of dicks would be less likely to have crossed someone else's mind.

The repo is at https://github.com/ikodotai/bmc

**Comment by chxclyde** [comment]
https://github.com/minio/minio-py/blob/master/minio/minioadmin.py

I think this is a good one.
