### ISSUE TITLE
How not to apply a quote charcter setting in CSVInput

### ISSUE THREAD

**Issue by larandvit** [minio/minio-py#830]
Hello,

1. I'm trying not to apply a quote character in CSVInput but it seems doesn't work. How tell CSVInput that I don't want to apply any quote character? I tried to use None and empty string (''). What value should be for QuoteEscapeCharacter setting in that case?
```
csv=CSVInput(FileHeaderInfo="USE",
                     RecordDelimiter="\n",
                     FieldDelimiter=MINIO_DELIMITER,
                     QuoteCharacter=None,
                     QuoteEscapeCharacter='"',
                     Comments="#",
                     AllowQuotedRecordDelimiter="FALSE",
                     ),
        ),
```

2. What characters are acceptable as quote ones? I tried \t, single quote ('), and r character and received the error message: "minio.error.MalformedXML: MalformedXML: message: This happens when the user sends malformed xml (xml that doesn't conform to the published xsd) for the configuration.".

Minio version is 5.0.1.

Thanks.

**Comment by vadmeste** [comment]
Those seem like issues in minio-py, I was able to reproduce them

**Comment by larandvit** [comment]
Thank you, @vadmeste, for confirmation.
Do you have any ticket to fix it or the Minio team is planning to do it? What is the protocol in those cases?

**Comment by vadmeste** [comment]
Taking this to fix

**Comment by vadmeste** [comment]
Could we close this ? This is already fixed in server's side.

**Comment by larandvit** [comment]
Hi @vadmeste 
Do you want this issue to be tested on our side? If so, we need to wait until a new version has been rolled out in my company.

**Comment by vadmeste** [comment]
> Hi @vadmeste
> Do you want this issue to be tested on our side? If so, we need to wait until a new version has been rolled out in my company.

@larandvit the feature is already released in server's side. This issue actually belongs to minio/minio and not minio/minio-py.

**Comment by larandvit** [comment]
Hi @vadmeste 
As per our discussion, closing this issue.
Thank you, Anis.
