### ISSUE TITLE
Support STS Client Grants authentication flow

### ISSUE THREAD

**Issue by Leletir** [minio/minio-py#831]
Hello,

Minio Go client sdk supports sts authentication flow and using jwt/session tokens for authentication, amd I was wondering if the support on the Python SDK is planned ? 

Thank you.

**Comment by kannappanr** [comment]
@Leletir We do not have anything planned for `minio-py` as of now. Will have to do this feature request in the future, when we have cycles to get to this. Closing this issue as of now
