### ISSUE TITLE
is_valid_endpoint(endpoint)

### ISSUE THREAD

**Issue by AthrunIJ** [minio/minio-py#835]
Just want to clarify with the function as shown in title.
Python version: 3.7.6
Minio version: 5.0.5

ipaddr = '43.74.4.35:9000', my server ip address

mio = Minio(ipaddr, access_key=id,secret_key=pass,secure=False)
mio.fput_object(bucketname,filename,pathtofile)

returns error InvalidEndpointError:message: Hostname cannot have a scheme.

I did some digging and when send through the is_valid_endpoint(endpoint) function it will return:-
scheme: urlsplit(endpoint)[0] is 43.74.4.35
netloc: urlsplit(endpoint)[1] is empty
path: urlsplit(endpoint)[2] is 9000
query: urlsplit(endpoint)[3] is empty
fragment: urlsplit(endpoint)[4] is empty

I think the urlsplit is recognizing the ip address as scheme because it is before the ':'

Is it a bug or it is just my environment?
I just pip install minio.

EDIT:

i remove the port from ip address
ipaddr = '43.74.4.35'
but it return error
ResponseError: code: , message: , bucket_name: broadcast, object_name: None, request_id: , host_id: , region:

**Comment by vadmeste** [comment]
@AthrunIJ can you do this in your system ?

```
12:05 $ python3
Python 3.7.3 (default, Apr  3 2019, 05:39:12)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib.parse
>>> urlsplit = urllib.parse.urlsplit
>>> urlsplit('43.74.4.35:9000')
SplitResult(scheme='', netloc='', path='43.74.4.35:9000', query='', fragment='')
>>>

```

**Comment by AthrunIJ** [comment]
> @AthrunIJ can you do this in your system ?
> 
> ```
> 12:05 $ python3
> Python 3.7.3 (default, Apr  3 2019, 05:39:12)
> [GCC 8.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import urllib.parse
> >>> urlsplit = urllib.parse.urlsplit
> >>> urlsplit('43.74.4.35:9000')
> SplitResult(scheme='', netloc='', path='43.74.4.35:9000', query='', fragment='')
> >>>
> ```

Hi, thanks for your reply. Unfortunately, I am on a long holiday until the new year from my company. But I will try your suggestion once I am back to work.

**Comment by toabi** [comment]
In our staging environment I suddenly saw the same issue. We are running something in a docker-compose environment so the hostname given to the function should be `media:9000`.

```
>>> urlsplit = urllib.parse.urlsplit
>>> urlsplit("media:9000")
SplitResult(scheme='media', netloc='', path='9000', query='', fragment='')
```

Does that mean the parsing of the python library changed?

On the failing system the current python release would be `Python 3.7.6 (default, Dec 20 2019, 22:50:33) 
`

On the still running staging server it's `Python 3.7.5 (default, Nov 23 2019, 06:10:46)` - So my guess is that 3.7.6 introduced that.

**Comment by AthrunIJ** [comment]
> In our staging environment I suddenly saw the same issue. We are running something in a docker-compose environment so the hostname given to the function should be `media:9000`.
> 
> ```
> >>> urlsplit = urllib.parse.urlsplit
> >>> urlsplit("media:9000")
> SplitResult(scheme='media', netloc='', path='9000', query='', fragment='')
> ```
> 
> Does that mean the parsing of the python library changed?
> 
> On the failing system the current python release would be `Python 3.7.6 (default, Dec 20 2019, 22:50:33) `
> 
> On the still running staging server it's `Python 3.7.5 (default, Nov 23 2019, 06:10:46)` - So my guess is that 3.7.6 introduced that.
> 
> (update with full outputs)
> 
> ```
> Python 3.7.5 (default, Nov 23 2019, 06:10:46) 
> [GCC 8.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import urllib.parse
> >>> urlsplit = urllib.parse.urlsplit
> >>> urlsplit("media:9000")
> SplitResult(scheme='', netloc='', path='media:9000', query='', fragment='')
> ```
> 
> ```
> Python 3.7.6 (default, Dec 20 2019, 22:50:33) 
> [GCC 8.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import urllib.parse
> >>> urlsplit = urllib.parse.urlsplit
> >>> urlsplit('media:9000')
> SplitResult(scheme='media', netloc='', path='9000', query='', fragment='')
> ```

Hi, yes. This issue also happened when I updated python to v3.7.6 while it seems to be working fine with v3.7.5.
Thabk you for your confirmation.

**Comment by toabi** [comment]
I dug a bit more and it's actually in the [changelog for python 3.7.6](https://docs.python.org/3.7/whatsnew/changelog.html#id3) => https://bugs.python.org/issue27657

**Comment by AthrunIJ** [comment]
O, interesting. Probably will need to code a work around for my system for now.

**Comment by vadmeste** [comment]
If I understood well this issue https://bugs.python.org/issue27657, the faulty code was reverted, so it looks like this will be fixed when 3.7.7 will be released and we won't do anything in our side.

**Comment by AthrunIJ** [comment]
> If I understood well this issue https://bugs.python.org/issue27657, the faulty code was reverted, so it looks like this will be fixed when 3.7.7 will be released and we won't do anything in our side.

OK, thank you for your time.

**Comment by vadmeste** [comment]
I also found this in url parse python documentation:

```
Following the syntax specifications in RFC 1808, urlparse recognizes a netloc only if it is properly introduced by ‘//’. Otherwise the input is presumed to be a relative URL and thus to start with a path component.
```

@toabi can you do this?

```
urlsplit('//media:90') 
```
?

**Comment by anehx** [comment]
@vadmeste 

`urlsplit('//media:90')` works fine as expected, however the `_ALLOWED_HOSTNAME_REGEX` fails with that configuration...

**Comment by wtayyeb** [comment]
I have read https://bugs.python.org/issue27657 and don't think they will revert it. because it was wrong all the time. the spec ( mentioned in python issue ) tell that // is a part of netloc and if it isnt exist the : is for scheme!
one proof for this is following example:
open your browser console and run `new URL('example.com:443')`  in it. you will see that `example.com:` will goes to protocol (scheme) and 443 will be the path.

![image](https://user-images.githubusercontent.com/1420290/71363250-cac99580-25ad-11ea-992e-27e5d59185b1.png)

**Comment by wtayyeb** [comment]
it seems in short time we must stick to python 3.7.5 until this resolved in minio-py itself. no way to pass through the `is_valid_endpoint`

**Comment by vadmeste** [comment]
> I have read https://bugs.python.org/issue27657 and don't think they will revert it.

yes, you are right. With this "revert" https://github.com/python/cpython/commit/82b5f6b16e051f8a2ac6e87ba86b082fa1c4a77f, it looks like 'path:80' returns scheme = 'path'.

This seems a high priority issue for minio-py now
