### ISSUE TITLE
Create option for ignoring S3 naming rules

### ISSUE THREAD

**Issue by glenndekhayser** [minio/minio-py#838]
Minio supports exposing existing datasets on NAS (for the NAS gateway function).  The data that's already there, especially if it was created in a Windows environment, but certainly possible in a Linux environment, likely isn't going to conform to S3 standards- meaning it will likely have capital letters, or symbols that don't adhere to the standard. 

It would be MOST useful if there was a "relaxed" setting that allowed more, if not all, POSIX-compliant file and directory names to be used, specifically for API calls. 

I.E. My NAS has a directory of testing data called "WindowsUpdateLogs".  That's not compliant.  But when I start Minio against that directory, the browser shows it fine and will serve it up fine. 

Performing a list_buckets() from Python shows the bucket with the "invalid" name.  But if I try to list the objects in that bucket, it errors out as the bucket name I've passed is... invalid.  So that's a problem. 

Any ideas? or am I right to be requesting this as an RFE?

**Comment by harshavardhana** [comment]
minio-py should do two types of validation

- existing buckets should not perform strict bucket name validation
- make_bucket should disallow creating non-compliant bucket names

This should be done across all our SDKs - minio-go/mc already support this behavior.

**Comment by glenndekhayser** [comment]
Thanks, I wasn’t sure if this was by design or not.
