### ISSUE TITLE
minio get_object failing with <class 'TypeError'>

### ISSUE THREAD

**Issue by ansuabraham** [minio/minio-py#841]
minioClient.get_object('local-media', 'zip_configuration_files/challenge_zip/'+artifact_name) fails with this exception:

<class 'TypeError'>
pop() takes 2 positional arguments but 3 were given

Libraries being used are: (These are installed via pip ni
django==1.11.23
django-allauth==0.40.0
django-filter==2.1.0
django-import-export==0.5.1
djangorestframework==3.9.3
djangorestframework-expiring-authtoken==0.1.4
django-cors-headers==1.3.1
django-rest-auth[with_social]==0.9.2 
django-ses==0.8.5
docker-compose==1.21.0
django-minio-storage==0.2.2

The exact code used to work until mid-December.

**Comment by kannappanr** [comment]
@ansuabraham Please try after you have removed the extra comma, closing this issue as answered. Please feel free to reach out to us at https://slack.min.io if you have further questions

**Comment by ansuabraham** [comment]
Hi @harshavardhana and @kannappanr, 

The extra comma is not the issue. Removing it makes no difference. I get the same "pop() takes 2 positional arguments but 3 were given" error.

I had to change secure to **True** to make this work. Any idea if something related to SSL changed recently to cause **secure=False** stop working?

**Comment by ivsanro1** [comment]
I solved this by modifying the file of urllib3 (near the line 400) of `site-packages\urllib3\poolmanager.py`:
```
if header.lower() in retries.remove_headers_on_redirect:
    kw["headers"].pop(header, None)
```

Change it to:

```
if header.lower() in retries.remove_headers_on_redirect:
    if header in kw:
        kw["headers"].pop(header)
```
