### ISSUE TITLE
[Feature request] More explicit memory management for object uploads 

### ISSUE THREAD

**Issue by mykola-mokhnach** [minio/minio-py#843]
Currently the `put_object` method might be quite memory demanding in some situations and this is not very obvious. For example the minimal part size is 5 MiB and the `_do_stream_upload` method uses the private pool to perform partial uploads with private hardcoded max workers value of 3 (the `_PARALLEL_UPLOADERS` constant). This means that a single object upload process would take minimum 15 MiB of RAM for data objects whose size is >= 15MiB. In reality this number would be greater (perhaps, about 20 MiB if we also count the size of all the helper objects). 

I assume this should be at least mentioned somewhere in the documentation. Also it would be nice to have a possibility to control the multipart upload process deeper, so there would be no unexpected memory usage spikes.

**Comment by harshavardhana** [comment]
> I assume this should be at least mentioned somewhere in the documentation. Also it would be nice to have a possibility to control the multipart upload process deeper, so there would be no unexpected memory usage spikes.

if this is what you want perhaps boto3 is the best choice, we will definitely profile and see if we can reuse the buffers here but we are not certainly not going down the road of providing an HTTP API layer by exposing all the gritty details of S3 API.  That is not the intention of this library.

**Comment by mykola-mokhnach** [comment]
> we are not certainly not going down the road of providing an HTTP API layer by exposing all the gritty details of S3 API

I did not say this is required. Just a bit more control on what is going on, so users don't unexpectedly face memory issues while uploading objects. For example an ability to change the size of the uploads pool would be nice.

**Comment by harshavardhana** [comment]
> I did not say this is required. Just a bit more control on what is going on, so users don't unexpectedly face memory issues while uploading objects. For example an ability to change the size of the uploads pool would be nice.

We would like to avoid making our SDKs cockpit-style configurations,  it uses sane values for all these to cater for a variety of use cases - if it's really such a big deal just fork the project and use it in your project with relevant changes. 

Even better provide a proposal PR, we won't have cycles to work on these features due to other priorities for the near future.
