### ISSUE TITLE
Deprecation warning due to invalid escape sequences in Python 3.8

### ISSUE THREAD

**Issue by tirkarthi** [minio/minio-py#852]
Deprecation warnings are raised due to invalid escape sequences in Python 3.8 . Below is a log of the warnings raised during compiling all the python files. Using raw strings or escaping them will fix this issue.

```
find . -iname '*.py'  | xargs -P 4 -I{} python -Walways -m py_compile {}

./minio/helpers.py:63: DeprecationWarning: invalid escape sequence \d
  '^(\d+\.){3}\d+$')
```

**Comment by harshavardhana** [comment]
Thanks for the work @tirkarthi - feel free to send a PR

**Comment by tirkarthi** [comment]
Sure, created #853
