### ISSUE TITLE
fget_object has race

### ISSUE THREAD

**Issue by jahodfra** [minio/minio-py#854]
When the `fget_object` is called twice it tries to download object into the same file and fails on the second call of the `os.rename`.

Expected behavior - the temporary filename shouldn't have etag in the name and instead it should use `uuid.uuid4()`.

**Comment by harshavardhana** [comment]
feel free to send a PR @jahodfra

**Comment by harshavardhana** [comment]
NOTE the same name is used to resume the operation @jahodfra using UUID is not an option.

**Comment by jahodfra** [comment]
I don't see how to solve it except using something like https://github.com/WoLpH/portalocker/tree/develop/portalocker

**Comment by jahodfra** [comment]
I'm using https://pypi.org/project/filelock/ in the calling code to avoid that. I'm not sure if it makes sense to do it in the client, because filelock needs extra empty file for the lock.

**Comment by balamurugana** [comment]
@jahodfra I see no problem if multiple `fget_object()` is called to download an object sequentially.

It is user responsibility If same object (or different object) is downloaded in parallel for same file name. You could use different file name of such requests and pick the latest one (or at your choice) for actual file.

**Comment by jahodfra** [comment]
@balamurugana It's probably fine to leave it. I'm not sure if it makes sense to document it.
What bit surprised me is that the continuation on already partial file is not working as well. The file is open with "wb". #824. Therefore it is not even necessary for name of temporary file to be stable.

**Comment by balamurugana** [comment]
@jahodfra `fget_object()` should work to resume partial download like other minio SDKs. Not working is an issue and will be fixed soon.

The idea of using `<FILENAME>.<ETAG>.part.minio` is like a web browser download/resume functionality i.e. the browser deals with fixed name `<FILENAME>.part`.
