### ISSUE TITLE
download folder

### ISSUE THREAD

**Issue by spinelsun** [minio/minio-py#859]
add the ability to download a folder and all of its content recursively from a specified bucket.

example of the API call may be get_object('my_buckt', myFolder/*) or get_object('my_buckt', myFolder/**)
where one * means to get the first level of files under the folder and double * means o get all objects recursively.

Same thing for fget_object function

**Comment by harshavardhana** [comment]
Application level code cannot exist in our SDKs, our SDKs implement basic higher level primitives.

You need to write this in your application.
