### ISSUE TITLE
Unable to create bucket using python SDK with HTTPS enabled

### ISSUE THREAD

**Issue by pransen** [minio/minio-py#861]
1. HTTPS is enabled for MinIO following the instructions in the docs.
2. I am able to open the MinIO browser and create a bucket.
3. However, using python SDK, MinIO bucket creation fails with the following error with 'secure' set to False in client created using minio.Minio()
InvalidXMLError: message: "Error" XML is not parsable. Message: syntax error: line 1, column 0

## Expected Behavior
Bucket should get created. Without HTTPS, it gets created as expected

## Current Behavior
With 'secure' set to False in client created using minio.Minio(), it throws the following error:
InvalidXMLError: message: "Error" XML is not parsable. Message: syntax error: line 1, column 0

with 'secure' set to True in client created using minio.Minio(), it throws the usual SSL error.

## Steps to Reproduce (for bugs)
1. enable https for minio
2. create a python client and try creating a bucket

## Your Environment

* Version used (`minio version`): minio docker latest image version is used from dockerhub
* Environment name and version (e.g. nginx 1.9.1): 
* Server type and version:
* Operating System and version (`uname -a`): x86_64 x86_64 x86_64 GNU/Linux

**Comment by nitisht** [comment]
@pransen can you paste sample code to help us reproduce the error, also can you paste the exact error you see in case of https enabled in py client

**Comment by pransen** [comment]
Sample code:
client = Minio(minio_host + ":" + minio_port, minio_user, minio_pw, secure=False)
    try:
        client.make_bucket("test-bucket")
    except Exception as err:
        print(err)

Error:
InvalidXMLError: message: "Error" XML is not parsable. Message: syntax error: line 1, column 0

**Comment by nitisht** [comment]
Why would you enable https on the server and then set secure=False in client?

**Comment by pransen** [comment]
I tried that initially setting secure=True. That still gave the ssl error.

**Comment by kannappanr** [comment]
@pransen That means it is either not https enabled or you are not hitting the correct IP address. 

```
from minio import Minio
from minio.error import ResponseError

client = Minio('localhost:9000',
               access_key='Q3AM3UQ867SPQQA43P2F',
               secret_key='zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG', secure=False)

# Make a new bucket
try:
    client.make_bucket('my-bucketname')
except ResponseError as err:
    print(err)
```

**Comment by kannappanr** [comment]
@pransen Closing this issue as answered. Please feel free to get back to us and we can take a look.
