### ISSUE TITLE
xml.etree.cElementTree was removed in Python 3.9

### ISSUE THREAD

**Issue by tirkarthi** [minio/minio-py#863]
There are instances in the code base where cElementTree is used. This was deprecated and removed in Python 3.9.

Ref : https://github.com/python/cpython/pull/19108
Slightly related : https://github.com/minio/minio-py/issues/822

**Comment by kannappanr** [comment]
@tirkarthi Thanks for reporting the issue. We will take a look at it.

**Comment by harshavardhana** [comment]
We don't get support python 3.9 so we should be mindful of that.
