### ISSUE TITLE
Create a new directory including its missing parents

### ISSUE THREAD

**Issue by guesswh0** [minio/minio-py#864]
I want to achieve this: 
`mc mb minio/bucket1/bucket2/` 
But i cannot perform this action with minio-py due to `is_valid_bucket_name` helper function restrictions of `bucket_name` argument.
`>>> client.make_bucket('bucket1/bucket2/')`
`minio.error.InvalidBucketError: InvalidBucketError: message: Bucket name contains invalid characters (strictly enforced).`

**Comment by harshavardhana** [comment]
minio-py is not meant for these higher level functionality, you need to do this on your own in your application.

minio-py exposes primitives to implement this functionality yourself.
