### ISSUE TITLE
IamEc2MetaData slows down get operations with anonymus access

### ISSUE THREAD

**Issue by hodossy** [minio/minio-py#873]
## Problem description

When trying to access a bucket anonymusy, the `IamEc2MetaData` class slows down the process if the target **hard coded** endpoint is not reachable or returns some error. That adds about 4.5 min overhead to a single request in my case.

## Steps to reproduce

1. Start the minio server docker:
```
docker run -p 9000:9000 --name minio minio/minio server /data
```
2. Start a client docker container to create a bucket with a file and set it to public.
```
docker run -it --network=host --entrypoint=/bin/sh minio/mc
/ # mc config host rm local
/ # mc config host add local http://127.0.0.1:9000 minioadmin minioadmin
/ # mc mb local/testbucket
/ # mc policy set public local/testbucket
/ # mc cp /data/file local/testbucket/path/to/file
```
3. Disconnect your network or have a corporate proxy
4. Try to access the file:
```python
client = Minio(
    '127.0.0.1:9000',
    secure=False
)

buffer = client.get_object('testbucket', 'path/to/file')
```

## Workaround

Just initialize with creds without the `IamEc2MetaData` provider:

```python
client = Minio(
    '127.0.0.1:9000',
    secure=False,
    credentials=Credentials(
        provider= Chain(
            providers=[
                Static(access_key, secret_key, session_token),
                EnvAWS(),
                EnvMinio(),
            ]
        )
    )
)
```

It actually blocks the program for like 2 mins when `self._credentials.get()` is called, which happens twice for a single `get_object` call.

**Comment by Praveenrajmani** [comment]
@hodossy I cannot understand the point here

Are you saying adding `IamEc2MetaData` in the provider chain slows down the request?

**Comment by Praveenrajmani** [comment]
@hodossy This test here does not make sense. You should provide necessary keys while initiating the client

```
client = Minio(
    '127.0.0.1:9000',
    secure=False
)

buffer = client.get_object('testbucket', 'path/to/file')
```

By default credentials is configured to be 

```
 Credentials(
            provider=Chain(
                providers=[
                    Static(access_key, secret_key, session_token),
                    EnvAWS(),
                    EnvMinio(),
                    IamEc2MetaData(),
                ]
            )
        )
```

Here, if you dont provide necessary credentials or access/secret pairs. minio-py will sequentially check the provider list in the chain and fails finally if it did not find any creds set. 

It will finally ping the hardcoded url for `IamEc2MetaData` and fails

**Comment by harshavardhana** [comment]
> @hodossy This test here does not make sense. You should provide necessary keys while initiating the client
> 
> ```
> client = Minio(
>     '127.0.0.1:9000',
>     secure=False
> )
> 
> buffer = client.get_object('testbucket', 'path/to/file')
> ```
> 
> By default credentials is configured to be
> 
> ```
>  Credentials(
>             provider=Chain(
>                 providers=[
>                     Static(access_key, secret_key, session_token),
>                     EnvAWS(),
>                     EnvMinio(),
>                     IamEc2MetaData(),
>                 ]
>             )
>         )
> ```
> 
> Here, if you dont provide necessary credentials or access/secret pairs. minio-py will sequentially check the provider list in the chain and fails finally if it did not find any creds set. It will fail with `AccessDenied` error which definitely make sense.
> 
> It will finally ping the hardcoded url for `IamEc2MetaData` and fails

Based on this closing the issue.

**Comment by hodossy** [comment]
Hello,

Could you please elaborate on what credentails shall I supply when accessing a bucket **anonymously**? Empy string? Is it documented somewhere?

And my problem is not that the `IamEc2MetaData` provider fails, but that failure takes 2 minutes. And there is no way to tweak that, since that provider uses its on `PoolManager`.

**Comment by Praveenrajmani** [comment]
@hodossy Anonymous buckets can be accessed directly through the URL. For eg, `https://play.mini.io/bucketname/objectname` 

You dont need client SDKs for this simple curl.. clients will always sign the requests with credentials which is not needed here.

And the slowness is because of the metadata server. The client here does nothing special.
