### ISSUE TITLE
Add method to clear connection pool

### ISSUE THREAD

**Issue by RazerM** [minio/minio-py#879]
The client uses a connection pool internally, but does not provide `Minio.close` or something to explicitly clear it. The constructor lets me pass `http_client`, but then I have to repeat the defaults that Minio uses. I could access `Minio._http`, but that is not part of the public API.

**Comment by vadmeste** [comment]
> but then I have to repeat the defaults that Minio uses

Could you elaborate on that please ?

**Comment by harshavardhana** [comment]
> The client uses a connection pool internally, but does not provide `Minio.close` or something to explicitly clear it. The constructor lets me pass `http_client`, but then I have to repeat the defaults that Minio uses. I could access `Minio._http`, but that is not part of the public API.

You shouldn't be doing that @RazerM what is the reasoning to clear connection pool?

**Comment by RazerM** [comment]
> Could you elaborate on that please ?

Minio uses good defaults for the `PoolManager`, which I'd have to duplicate in my code if I want to own it myself. I don't really want to own it, I just need to be able to access `.clear()`.

https://github.com/minio/minio-py/blob/aa0a0791fbf3339c435292ca412a8c1feb6efc7e/minio/api.py#L220-L230

**Comment by harshavardhana** [comment]
> Minio uses good defaults for the `PoolManager`, which I'd have to duplicate in my code if I want to own it myself. I don't really want to own it, I just need to be able to access `.clear()`.

Since you want to own the PoolManager by trying to clear() it, you should own it.

**Comment by RazerM** [comment]
If I use a requests [`Session`](https://2.python-requests.org/en/master/api/#request-sessions) for making HTTP requests, it provides a [`close()`](https://2.python-requests.org/en/master/api/#requests.Session.close) method that clears its connection pool (which is also a urllib3 `PoolManager`).

Why should the Minio client be different?

---

> Since you want to own the PoolManager by trying to clear() it, you should own it.

Well, I don't want to clear it in the sense that I don't care how the Minio client works internally. I want to tell Minio to clear up the resources it has open.

**Comment by harshavardhana** [comment]
> Well, I don't want to clear it in the sense that I don't care how the Minio client works internally. I want to tell Minio to clear up the resources it has open.

That is not the usage of minio-py SDK @RazerM I don't see you provided a good reason for this public API - what we already have is a way to provide custom PoolManager, where you can close, clear whatever you wish by keeping this pool in your application space.

Pease conclusively provide evidence on why you need this, what issue you are trying to tackle?. We don't want to add unexpected APIs which are not meant for our SDK.

**Comment by balamurugana** [comment]
@RazerM As you mentioned `Minio` constructor provides an option for customized HTTP client, this option needs to be used for any such requirements.
