### ISSUE TITLE
Breaking changes to 6.0.0

### ISSUE THREAD

**Issue by vadmeste** [minio/minio-py#902]
This is a list of breaking changes that we want to do before releasing 6.0.0

- [ ] The modtime type of list_objects v1 & v2 is different to stat_object 
- [ ] Change JsonOutput to JSONOutput
- [ ] Making sure that SQL API differentiate between sending an empty option and not sending the parameter at all for JSON/CSV input/output options
- [ ] Credentials refactoring
- [ ] Assume role design fix 
- [ ] Fix all pylint error C0103 invalid-name

**Comment by Praveenrajmani** [comment]
We can also add the credentials refactoring and assume role design fix in the version bump @vadmeste

**Comment by balamurugana** [comment]
* Fix all `pylint` error `C0103 invalid-name`

**Comment by plankthom** [comment]
got confused by this issue description: 6.0.0 is already released. I assume this is about changes in 7.0.0 ?

**Comment by vadmeste** [comment]
> got confused by the issue description: 6.0.0 is already released. I assume this is about changes in 7.0.0 ?
> 
> >

yes, the issue was created before the release of minio-py 6.0. Some of the items are already done.

@Praveenrajmani @balamurugana could you confirm items in the above list that are done ?

**Comment by balamurugana** [comment]
The issue is invalid for the latest release. v7.0.0 comes with many refactors. Please refer release notes https://github.com/minio/minio-py/releases/tag/7.0.0
