### ISSUE TITLE
Accessing Minio Azure Gateway through Apache Reverse Proxy

### ISSUE THREAD

**Issue by michaelschmit** [minio/minio-py#924]
I have a minio azure gateway running on kubernetes.  I access the instance through an apache reverse proxy.  It is secured via self generated certificates.  I am able to access the minio instance via the web and do not receive a warning after importing the root cert.  I am able to login, create, and delete buckets, and the changes persist between tear downs of the kubernetes instances.

The issue I have is connecting with the python client.  When attempting to connect with secure enabled, I get the error:

`minio.error.SignatureDoesNotMatch: SignatureDoesNotMatch: message: The request signature we calculated does not match the signature you provided.`

I did some more research and found the recipe on the minio website for a minio http proxy:

(https://docs.min.io/docs/setup-apache-http-proxy-with-minio-server.html)

I've followed this example, specifically adding `ProxyPreserveHost On` and the signature error goes away.  However, if I try to make a bucket or check if a bucket exists, I get bad results.  In the case of making a bucket I get an error saying the bucket does not exist.  If I check if a bucket exists, I get a `False` even though the bucket actually exists.  I believe this is due to 404s being returned and being incorrectly interpreted by the python client as a legitimate result.

Overall, I am stumped why the web version works flawlessly but I am unable to get the python client to work.  Any debugging ideas or thoughts would be appreciated.

**Comment by michaelschmit** [comment]
I should also note, that I have spun up a local docker instance of minio going against the same azure instance and was able to connect via the python client using the same credentials, just a different endpoint.

**Comment by balamurugana** [comment]
@michaelschmit could you enable debugging by `minio_client.trace_on(sys.stdout)` and share the output here. This will help to understand what's going on at HTTP level.

**Comment by michaelschmit** [comment]
@balamurugana sorry for not getting back to you today.  I noticed that I had istio in the mix as well.  I am going to remove that from the equation for now and see where I stand before debugging further.  I will report back as soon as I have the results.

**Comment by michaelschmit** [comment]
Previously, I had istio setup to perform TLS termination at the gateway.  I instead setup minio to do tls and setup the gateway to perform passthrough.  This allowed the python client to connect and not return the 404 not founds I was running into previously.  I also had to set `ProxyPreserveHost On` on the apache reverse proxy for the client to connect as well.

I'm not sure why the web UI works differently than the python client, since the javascript likely performs the exact same API calls, but I was able to get things to work so I will close this issue.

**Comment by harshavardhana** [comment]
> I'm not sure why the web UI works differently than the python client, since the javascript likely performs the exact same API calls, but I was able to get things to work so I will close this issue.

It does not @michaelschmit UI uses a different protocol that is not relying on S3 semantics.
