### ISSUE TITLE
async get_object throwing issue

### ISSUE THREAD

**Issue by srinivaskotamraju** [minio/minio-py#925]
I would like to use async await calls and trigger multiple get_object calls and improve the throughput of my code (accessing objects in the minio store hoisted on azure).

Below is the sample code. However i am receiving the below error. Not sure if my approach is correct

TypeError: object HTTPResponse can't be used in 'await' expression

I would like to attempt similar to what this URL suggests: https://towardsdatascience.com/stop-waiting-start-using-async-and-await-18fcd1c28fd0

**The code that is failing** 

async def get_image(obj):
    print("start obj.name: "+obj.object_name)
    #out = await get_image_object(obj)
    out = await minioClient.get_object('imagelist', obj.object_name)
    print("fetched obj.name: " + obj.object_name)
    return out

async def get_all_images_async():
    print("get_all_images asynchronously")
    objects = minioClient.list_objects('imagelist', recursive=False)
    await asyncio.gather(*[get_image(obj) for count,obj in enumerate(objects)])

start = timer()
asyncio.run(get_all_images_async())
end = timer()

print(end - start)

**Comment by balamurugana** [comment]
`minioClient.get_object()` is not await-able.  Below is the working code.

```python
import asyncio
from time import time
from minio import Minio

minioClient = Minio(
    "localhost:9000", access_key="minio", secret_key="minio123", secure=False,
)


async def get_image(obj):
    print("start obj.name: "+obj.object_name)
    out = minioClient.get_object('b-1', obj.object_name)
    print("fetched obj.name: " + obj.object_name)
    return out


async def get_all_images_async():
    print("get_all_images asynchronously")
    objects = minioClient.list_objects('b-1', recursive=False)
    return await asyncio.gather(
        *[get_image(obj) for count, obj in enumerate(objects)],
    )


start = time()
print(asyncio.run(get_all_images_async()))
end = time()

print(end - start)
```

**Comment by kannappanr** [comment]
@srinivaskotamraju Closing this issue as answered. Please feel free to reach out to us at https://slack.min.io fir further questions

**Comment by srinivaskotamraju** [comment]
Hi balamurugana, thanks for replying. The above code however results in sequential download, i would like to increase the through put by using the multiple requests getting fired for the download. It is ok if get_object cannot be awaited. however what are the standard ways of doing this parallel get_object (through asyncio or anything package), can you please share the approach.

If i have do this using https://slack.min.io , i would goind head

**Comment by balamurugana** [comment]
@srinivaskotamraju As `minio-py` is thread-safe. you could use `threading` module to get multiple objects in parallel.

**Comment by srinivaskotamraju** [comment]
Sure, thanks we would think approach. We are using uvicorn and fastapi as our REST infrastructure (with asyncio). Introducing threading module into this infrastructure, we are have to carefully plan and implement, so that we don't end up into messy threading issues. Thanks once again for a quick response
