### ISSUE TITLE
Implement Lifecycle Management API Calls

### ISSUE THREAD

**Issue by trenta3** [minio/minio-py#931]
Hi! I noticed that the lifecycle management API are missing in the python client docs and in the code, but are implemented in the Go and the Java clients (search for SetBucketLifecycle, GetBucketLifecycle, DeleteBucketLifecycle in https://docs.minio.io/docs/golang-client-api-reference.html ).
Would it be possible to add their implementation here too?

Thanks for the great work!

**Comment by kannappanr** [comment]
The PRs for Lifecycle management APIs has been merged, so closing this PR
