### ISSUE TITLE
Offline presigned URL generation

### ISSUE THREAD

**Issue by gitpushdashf** [minio/minio-py#940]
Is there a way to generated presigned URLs offline in Minio?

**Comment by harshavardhana** [comment]
@gitpushdashf set the right region then we won't perform get_bucket_location

**Comment by gitpushdashf** [comment]
Ah, thank you!

```
import minio
import datetime

minio_client = Minio("http://localhost:9000", access_key="minioadmin", secret_key="minioadmin", secure=False)
minio_client._set_bucket_region("bucket")
print(minio_client.presigned_get_object("bucket", "object", datetime.timedelta(days=1)))
```

Gives me: `http://localhost:9000/bucket/object?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minioadmin%2F20200722%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200722T171834Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=1d87b29675a889cee377d7f7fb1065baa2b45efa9899fab939eab0caebdec767`


(Note that Minio is not running here, credentials are bogus, etc.)

**Comment by harshavardhana** [comment]
> minio_client._set_bucket_region("bucket")

Don't access internal methods 



> minio_client = Minio("http://localhost:9000", access_key="minioadmin", secret_key="minioadmin", region="bucket", secure=False)

^^ correct approach @gitpushdashf

**Comment by gitpushdashf** [comment]
Oops, that makes a lot more sense!

**Comment by septatrix** [comment]
Which region should I use for self-hosted MinIO instances?
