### ISSUE TITLE
nose is unmaintained and will stop working under future versions of Python

### ISSUE THREAD

**Issue by tirkarthi** [minio/minio-py#942]
Nose has been unmaintained and will stop working in version like Python 3.10 due to ABC import from collections. Ref : https://github.com/nose-devs/nose/issues/1099

**Comment by harshavardhana** [comment]
> Nose has been unmaintained and will stop working in version like Python 3.10 due to ABC import from collections. Ref : [nose-devs/nose#1099](https://github.com/nose-devs/nose/issues/1099)

Good idea feel free to send PR @tirkarthi

**Comment by balamurugana** [comment]
`minio-py` works fine with `nose v1.3.7` in python 3.9.0. We will move away from `nose` if it breaks in future.
