### ISSUE TITLE
When the "PutBucketVersioning" API will be enabled ?

### ISSUE THREAD

**Issue by pavo-tusker** [minio/minio-py#943]
Hi,

Right now we are working on Minio Bucket versioning. In Server, the Bucket version is there.  But we didn't find API for enabling bucket versioning. When the API to enable bucket versioning will available in Minio Python?

**Comment by harshavardhana** [comment]
Soon it's merged in master #923 - we are finishing up the docs in #941

**Comment by kannappanr** [comment]
closing this issue as answered. We hope to make a release soon once the documentation and examples are updated
