### ISSUE TITLE
Mix of timezone-aware and naive datetime objects with AssumeRoleProvider

### ISSUE THREAD

**Issue by wilko77** [minio/minio-py#957]
I was trying to update our code base to use minio 6.0.0 and ran into the following problem:

```
self = <minio.credentials.credentials.Credentials object at 0x110fad610>
force = False

    def get(self, force=False):
        """Get credentials from provider if needed."""
        if (
                force or
                not self._value or
>               (self._expiry and self._expiry < datetime.utcnow())
        ):
E       TypeError: can't compare offset-naive and offset-aware datetimes
```

I could track it down to the following code:
```
credentials_provider = AssumeRoleProvider( lambda: some_minio_client.get_assume_role_creds(restricted_upload_policy))
temp_credentials = Credentials(provider=credentials_provider)

restricted_mc_client = Minio(upload_endpoint, credentials=temp_credentials, region='us-east-1', secure=False)
```

The problem seems to be that `get_assume_role_creds` calls `parse_assume_role` which returns the expiry as a timezone-aware datetime object https://github.com/minio/minio-py/blob/e1d58b2599fed979fa8459cd6a22f1699dd919a6/minio/parsers.py#L531
However, in the `Credentials` class in the `get` method there is a test against a naive datetime object: https://github.com/minio/minio-py/blob/e1d58b2599fed979fa8459cd6a22f1699dd919a6/minio/credentials/credentials.py#L71

Am I using the `AssumeRoleProvider` incorrectly or is there a bug?

**Comment by balamurugana** [comment]
Fixed by https://github.com/minio/minio-py/pull/963
