### ISSUE TITLE
Minio 6.0 no longer includes config*sample

### ISSUE THREAD

**Issue by s-t-e-v-e-n-k** [minio/minio-py#961]
Since the configuration sample files were moved from the credentials directory to test/unit, MANIFEST.in was not updated to include them in the sdist.

**Comment by harshavardhana** [comment]
> Since the configuration sample files were moved from the credentials directory to test/unit, MANIFEST.in was not updated to include them in the sdist.

There are no configuration files for minio-py and never has been not sure what are you talking about here ?

**Comment by s-t-e-v-e-n-k** [comment]
Sorry, I should have been more clear -- By configuration samples I mean ``config.json.sample`` and ``credentials.sample``. They are not shipped in the sdist on pypi, and therefore tests fail.
