### ISSUE TITLE
Function Notification

### ISSUE THREAD

**Issue by 2020testuser** [minio/minio-py#964]
Hi,
Currently, set_bucket_notification() doesn't support Function notification.

Could you please let me know whether this feature is in the minio python roadmap and if so, when (month/year) this feature would be available for use by minio customers? 

Also, if this is not in the roadmap, could you please include it?

Thanks in advance!

**Comment by balamurugana** [comment]
Fixed by https://github.com/minio/minio-py/pull/990. Please refer https://github.com/minio/minio-py/blob/7.0.0/minio/notificationconfig.py
