### ISSUE TITLE
Access S3 without Access Key and Secret

### ISSUE THREAD

**Issue by nileshbhadana** [minio/minio-py#978]
I am trying to access my s3 bucket using minio, but I want to use role instead of AccessKeyId and Secret.
Can any one help?
Thanks in Advance

**Comment by balamurugana** [comment]
You could use credential providers for that. Please refer `minio_with_*_provider.py` in [examples](https://github.com/minio/minio-py/tree/master/examples) For more detail, refer [providers.py](https://github.com/minio/minio-py/blob/master/minio/credentials/providers.py)
